=== REGISTERED PATTERNS ===
===========================
// Auto-generated by MIRR compiler (Phase 6)
// Do not edit — regenerate from .mirr source.
// Target: SystemVerilog (.sv)

  // source: <unknown>:4
module pressure_monitor (
  input  logic        clk,
  input  logic        rst_n,
  input  logic [15:0] airway_pressure,
  output logic        clamp_valve
);

  // Temporal signals
  logic        pressure_low_sr_0;
  logic        pressure_low_sr_1;
  logic        pressure_low_sr_2;
  logic        pressure_low_out;

  // ── Temporal Guards ──


  // source: <unknown>:8
  // Guard: pressure_low — when airway_pressure < 50 for 3 cycles
  logic [2:0] pressure_low_sr;
  logic pressure_low_cond;
  assign pressure_low_cond = (airway_pressure < 50);
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n)
      pressure_low_sr <= '0;
    else
      pressure_low_sr <= {pressure_low_cond, pressure_low_sr[2:1]};
  end
  assign pressure_low_out = &pressure_low_sr;

  // ── Reflex Assignments ──

  logic pressure_low_out;

  // Unified Reflex Block for: clamp_valve
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      clamp_valve <= '0;
    end else begin
  // source: <unknown>:13
      if (pressure_low_out) clamp_valve <= 1'b1;
    end
  end

  // ── Safety Properties (SVA) ──

  // source: <unknown>:19
  // property: pressure_bounded
  assert property (@(posedge clk) ((airway_pressure > 10)));

  // source: <unknown>:23
  // property: no_spurious_clamp
  assert property (@(posedge clk) !((clamp_valve & (airway_pressure > 200))));

  // source: <unknown>:27
  // property: low_triggers_clamp
  assert property (@(posedge clk) ((airway_pressure < 50)) |-> (clamp_valve));

  // source: <unknown>:31
  // property: clamp_reachable
  reg [31:0] prop_clamp_reachable_timer;
  always @(posedge clk) begin
    if (clamp_valve) prop_clamp_reachable_timer <= 0;
    else prop_clamp_reachable_timer <= prop_clamp_reachable_timer + 1;
  end
  cover property (@(posedge clk) (prop_clamp_reachable_timer < 100));

  // source: <unknown>:35
  // property: clamp_follows_drop
  reg [4:0] prop_clamp_follows_drop_trig_shift;
  always @(posedge clk) begin
    prop_clamp_follows_drop_trig_shift <= {prop_clamp_follows_drop_trig_shift[3:0], (airway_pressure < 50)};
  end
  assert property (@(posedge clk) (prop_clamp_follows_drop_trig_shift[4]) |-> (clamp_valve));

endmodule
