// Auto-generated by MIRR compiler (Phase 6)
// Do not edit — regenerate from .mirr source.
// Target: SystemVerilog (.sv)

module HlsTest (
);

  // Internal signals
  logic signed [ 7:0] a;
  logic signed [ 7:0] b;
  logic signed [ 7:0] c;
  logic signed [ 7:0] d;
  logic signed [ 7:0] e;
  logic signed [ 7:0] out1;
  logic signed [ 7:0] out2;

  // Temporal signals
  logic        always_out;

  // ── Temporal Guards ──


  // Guard: always — always for 0 cycle (combinational)
  logic always_cond;
  assign always_cond = 1'b1;
  assign always_out = always_cond;

  // ── Reflex Assignments ──

  logic always_out;

  // ── HLS Finite State Machine ──
  logic [31:0] hls_state;
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      hls_state <= 0;
      out1 <= '0;
      out2 <= '0;
    end else begin
      case (hls_state)
        0: begin
          if (always_out) out1 <= (a + b);
          if (always_out) out2 <= (c + d);
          hls_state <= 0;
        end
      endcase
    end
  end

endmodule
