/* Generated by Yosys 0.64 (git sha1 d8dab5b32666564eca8e18f412973853ce006e61, clang++ 21.0.0 -fPIC -O3) */

module ScienceHls(clk, rst_n, a, b, c, out_val);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input [7:0] a;
  wire [7:0] a;
  input [7:0] b;
  wire [7:0] b;
  input [7:0] c;
  wire [7:0] c;
  output [16:0] out_val;
  reg [16:0] out_val;
  wire [31:0] _00_;
  wire [16:0] _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire [16:0] _12_;
  wire _13_;
  wire _14_;
  reg [7:0] a_d1;
  reg [7:0] a_d2;
  reg [7:0] a_d3;
  wire always_cond;
  wire always_out;
  reg [7:0] b_d1;
  reg [7:0] b_d2;
  reg [7:0] b_d3;
  reg [7:0] c_d1;
  reg [7:0] c_d2;
  reg [7:0] c_d3;
  reg [31:0] hls_state;
  reg rst_n_d1;
  reg rst_n_d2;
  reg rst_n_d3;
  assign _01_ = $signed(a) + $signed(b);
  always @(posedge clk, negedge rst_n)
    if (!rst_n) a_d1 <= 8'h00;
    else if (_14_) a_d1 <= a;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) b_d2 <= 8'h00;
    else if (_14_) b_d2 <= b_d1;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rst_n_d1 <= 1'h0;
    else if (_14_) rst_n_d1 <= rst_n;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) c_d2 <= 8'h00;
    else if (_14_) c_d2 <= c_d1;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) a_d2 <= 8'h00;
    else if (_14_) a_d2 <= a_d1;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) b_d1 <= 8'h00;
    else if (_14_) b_d1 <= b;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) c_d1 <= 8'h00;
    else if (_14_) c_d1 <= c;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rst_n_d2 <= 1'h0;
    else if (_14_) rst_n_d2 <= rst_n_d1;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rst_n_d3 <= 1'h0;
    else if (_14_) rst_n_d3 <= rst_n_d2;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) hls_state <= 32'd0;
    else if (_03_) hls_state <= _00_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) b_d3 <= 8'h00;
    else if (_14_) b_d3 <= b_d2;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) out_val <= 17'h00000;
    else if (_13_) out_val <= _12_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) a_d3 <= 8'h00;
    else if (_14_) a_d3 <= a_d2;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) c_d3 <= 8'h00;
    else if (_14_) c_d3 <= c_d2;
  assign _03_ = | { _13_, _14_ };
  assign _04_ = $signed(out_val) == $signed(_12_);
  assign _05_ = $signed(a_d3) == $signed(a);
  assign _06_ = $signed(b_d3) == $signed(b);
  assign _07_ = $signed(c_d3) == $signed(c);
  assign _08_ = _11_ && _07_;
  assign _09_ = _08_ && rst_n_d3;
  assign _10_ = rst_n && _09_;
  assign _11_ = _05_ && _06_;
  assign _12_ = $signed(_01_) * $signed(c);
  assign _02_ = _10_ ? 1'h1 : 1'h0;
  function [31:0] _42_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _42_ = b[31:0];
      2'b1?:
        _42_ = b[63:32];
      default:
        _42_ = a;
    endcase
  endfunction
  assign _00_ = _42_(32'hxxxxxxxx, 64'h0000000100000000, { _14_, _13_ });
  assign _14_ = ! hls_state;
  assign _13_ = hls_state == 32'd1;
  always @(posedge clk) begin
    if (_02_) begin
      assert (_04_);
    end
  end
  assign always_cond = 1'h1;
  assign always_out = 1'h1;
endmodule
