// Auto-generated by MIRR compiler (Phase 6)
// Do not edit — regenerate from .mirr source.
// Target: SystemVerilog (.sv)

module ScienceHls (
);

  // Internal signals
  logic signed [ 7:0] a;
  logic signed [ 7:0] b;
  logic signed [ 7:0] c;
  logic signed [ 7:0] out_val;

  // Temporal signals
  logic        always_out;

  // ── Temporal Guards ──

  // Guard: always — always for 0 cycle (combinational)
  logic always_cond;
  assign always_cond = 1'b1;
  assign always_out = always_cond;

  // ── Reflex Assignments ──

  logic always_out;

  // Unified Reflex Block for: out_val
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      out_val <= '0;
    end else begin
      if (always_out) out_val <= ((a + b) * c);
    end
  end

endmodule
