#![forbid(unsafe_code)]

use nasa_rust_project::pipeline::{run_pipeline, PipelineConfig};

#[test]
fn test_expand_cycle_detection_deep() {
    let src = r#"
        def A() { reflect { B(); } }
        def B() { reflect { C(); } }
        def C() { reflect { D(); } }
        def D() { reflect { E(); } }
        def E() { reflect { A(); } } // 5-hop cycle
        
        module m { A(); }
    "#;
    let res = run_pipeline(src, &PipelineConfig::default());
    assert!(res.is_err());
    assert!(res.unwrap_err().to_string().contains("Circular"));
}

#[test]
fn test_expand_substitution_engine() {
    let src = r#"
        def Mux(sel: signal in bool, a: signal in bool, b: signal in bool, out: signal out bool) {
            reflect {
                signal _internal_mux: internal bool;
                guard g_mux { when sel for 1 cycles; }
                reflex r_mux {
                    on g_mux { out = a; }
                }
            }
        }
        
        module m {
            signal sel: in bool;
            signal a: in bool;
            signal b: in bool;
            signal out: out bool;
            
            Mux(sel, a, b, out);
        }
    "#;

    let res = run_pipeline(src, &PipelineConfig::default());
    assert!(res.is_ok(), "{:?}", res.unwrap_err());

    // The pipeline successfully expanded and hydrated the ECS registry (which built the AST guards).
    let prog = res.unwrap().program;

    assert_eq!(prog.module.guards.len(), 1);
    assert!(prog.module.guards[0].name.contains("Mux"));
    assert!(prog.module.guards[0].name.contains("g_mux"));
    assert_eq!(prog.module.reflexes.len(), 1);
}

#[test]
fn test_expand_rename_collision_avoidance() {
    let src = r#"
        def DoubleDelay(sig: signal in bool) {
            reflect {
                signal _temp: internal bool;
                guard g1 { when sig for 1 cycles; }
                reflex r1 { on g1 { _temp = true; } }
            }
        }
        
        module m {
            signal a: in bool;
            signal b: in bool;
            
            // Call twice. Both will generate `_temp`, `g1`, `r1`.
            // The rename engine must suffix or prefix them to prevent collisions in semantic validation (E213/E212)
            DoubleDelay(a);
            DoubleDelay(b);
        }
    "#;

    let res = run_pipeline(src, &PipelineConfig::default());
    assert!(res.is_ok(), "{:?}", res.unwrap_err());

    let prog = res.unwrap().program;

    // Find internal signals generated by expansion
    let internal_sigs: Vec<_> =
        prog.module.signals.iter().filter(|sig| sig.name.contains("_temp")).collect();

    assert_eq!(internal_sigs.len(), 2, "Expected 2 distinct internal signals");
    assert_ne!(
        internal_sigs[0].name, internal_sigs[1].name,
        "Internal signals must be uniquely renamed"
    );

    assert_eq!(prog.module.guards.len(), 2, "Expected 2 distinct guards");
    assert_ne!(prog.module.guards[0].name, prog.module.guards[1].name);
}

#[test]
fn test_expand_undefined_pattern() {
    let src = r#"
        module m {
            NonExistent();
        }
    "#;

    let res = run_pipeline(src, &PipelineConfig::default());
    assert!(res.is_err());
    assert!(res.unwrap_err().to_string().contains("undefined"));
}

#[test]
fn test_expand_wrong_argument_count() {
    let src = r#"
        def p(a: u8, b: u8) { reflect { signal dummy: internal bool; } }
        module m { p(42); }
    "#;
    let res = run_pipeline(src, &PipelineConfig::default());
    assert!(res.is_err());
    assert!(res.unwrap_err().to_string().contains("expects"));
}

#[test]
fn test_expand_constant_substitution() {
    let src = r#"
        def Threshold(val: u16) {
            reflect {
                signal s: internal u16;
                guard g { when s == ${val} for 1 cycles; }
            }
        }
        module m {
            Threshold(999);
        }
    "#;
    // Parameter interpolation using `${val}` syntax
    let res = run_pipeline(src, &PipelineConfig::default());
    assert!(res.is_ok(), "{:?}", res.unwrap_err());
}

// --- AUTO GENERATED EXPANSION TESTS ---

macro_rules! test_expand_valid {
    ($name:ident, $src:expr) => {
        #[test]
        fn $name() -> Result<(), Box<dyn std::error::Error>> {
            run_pipeline($src, &PipelineConfig::default())?;
            Ok(())
        }
    };
}
test_expand_valid!(
    test_expand_1,
    "def P1() { reflect { signal s: internal bool; } } module m { P1(); }"
);
test_expand_valid!(
    test_expand_2,
    "def P2() { reflect { signal s: internal bool; } } module m { P2(); }"
);
test_expand_valid!(
    test_expand_3,
    "def P3() { reflect { signal s: internal bool; } } module m { P3(); }"
);
test_expand_valid!(
    test_expand_4,
    "def P4() { reflect { signal s: internal bool; } } module m { P4(); }"
);
test_expand_valid!(
    test_expand_5,
    "def P5() { reflect { signal s: internal bool; } } module m { P5(); }"
);
test_expand_valid!(
    test_expand_6,
    "def P6() { reflect { signal s: internal bool; } } module m { P6(); }"
);
test_expand_valid!(
    test_expand_7,
    "def P7() { reflect { signal s: internal bool; } } module m { P7(); }"
);
test_expand_valid!(
    test_expand_8,
    "def P8() { reflect { signal s: internal bool; } } module m { P8(); }"
);
test_expand_valid!(
    test_expand_9,
    "def P9() { reflect { signal s: internal bool; } } module m { P9(); }"
);
test_expand_valid!(
    test_expand_10,
    "def P10() { reflect { signal s: internal bool; } } module m { P10(); }"
);
test_expand_valid!(
    test_expand_11,
    "def P11() { reflect { signal s: internal bool; } } module m { P11(); }"
);
test_expand_valid!(
    test_expand_12,
    "def P12() { reflect { signal s: internal bool; } } module m { P12(); }"
);
test_expand_valid!(
    test_expand_13,
    "def P13() { reflect { signal s: internal bool; } } module m { P13(); }"
);
test_expand_valid!(
    test_expand_14,
    "def P14() { reflect { signal s: internal bool; } } module m { P14(); }"
);
test_expand_valid!(
    test_expand_15,
    "def P15() { reflect { signal s: internal bool; } } module m { P15(); }"
);
test_expand_valid!(
    test_expand_16,
    "def P16() { reflect { signal s: internal bool; } } module m { P16(); }"
);
test_expand_valid!(
    test_expand_17,
    "def P17() { reflect { signal s: internal bool; } } module m { P17(); }"
);
test_expand_valid!(
    test_expand_18,
    "def P18() { reflect { signal s: internal bool; } } module m { P18(); }"
);
test_expand_valid!(
    test_expand_19,
    "def P19() { reflect { signal s: internal bool; } } module m { P19(); }"
);
test_expand_valid!(
    test_expand_20,
    "def P20() { reflect { signal s: internal bool; } } module m { P20(); }"
);
test_expand_valid!(
    test_expand_21,
    "def P21() { reflect { signal s: internal bool; } } module m { P21(); }"
);
test_expand_valid!(
    test_expand_22,
    "def P22() { reflect { signal s: internal bool; } } module m { P22(); }"
);
test_expand_valid!(
    test_expand_23,
    "def P23() { reflect { signal s: internal bool; } } module m { P23(); }"
);
test_expand_valid!(
    test_expand_24,
    "def P24() { reflect { signal s: internal bool; } } module m { P24(); }"
);
test_expand_valid!(
    test_expand_25,
    "def P25() { reflect { signal s: internal bool; } } module m { P25(); }"
);
test_expand_valid!(
    test_expand_26,
    "def P26() { reflect { signal s: internal bool; } } module m { P26(); }"
);
test_expand_valid!(
    test_expand_27,
    "def P27() { reflect { signal s: internal bool; } } module m { P27(); }"
);
test_expand_valid!(
    test_expand_28,
    "def P28() { reflect { signal s: internal bool; } } module m { P28(); }"
);
test_expand_valid!(
    test_expand_29,
    "def P29() { reflect { signal s: internal bool; } } module m { P29(); }"
);
test_expand_valid!(
    test_expand_30,
    "def P30() { reflect { signal s: internal bool; } } module m { P30(); }"
);
test_expand_valid!(
    test_expand_31,
    "def P31() { reflect { signal s: internal bool; } } module m { P31(); }"
);
test_expand_valid!(
    test_expand_32,
    "def P32() { reflect { signal s: internal bool; } } module m { P32(); }"
);
test_expand_valid!(
    test_expand_33,
    "def P33() { reflect { signal s: internal bool; } } module m { P33(); }"
);
test_expand_valid!(
    test_expand_34,
    "def P34() { reflect { signal s: internal bool; } } module m { P34(); }"
);
test_expand_valid!(
    test_expand_35,
    "def P35() { reflect { signal s: internal bool; } } module m { P35(); }"
);
test_expand_valid!(
    test_expand_36,
    "def P36() { reflect { signal s: internal bool; } } module m { P36(); }"
);
test_expand_valid!(
    test_expand_37,
    "def P37() { reflect { signal s: internal bool; } } module m { P37(); }"
);
test_expand_valid!(
    test_expand_38,
    "def P38() { reflect { signal s: internal bool; } } module m { P38(); }"
);
test_expand_valid!(
    test_expand_39,
    "def P39() { reflect { signal s: internal bool; } } module m { P39(); }"
);
test_expand_valid!(
    test_expand_40,
    "def P40() { reflect { signal s: internal bool; } } module m { P40(); }"
);
test_expand_valid!(
    test_expand_41,
    "def P41() { reflect { signal s: internal bool; } } module m { P41(); }"
);
test_expand_valid!(
    test_expand_42,
    "def P42() { reflect { signal s: internal bool; } } module m { P42(); }"
);
test_expand_valid!(
    test_expand_43,
    "def P43() { reflect { signal s: internal bool; } } module m { P43(); }"
);
test_expand_valid!(
    test_expand_44,
    "def P44() { reflect { signal s: internal bool; } } module m { P44(); }"
);
test_expand_valid!(
    test_expand_45,
    "def P45() { reflect { signal s: internal bool; } } module m { P45(); }"
);
test_expand_valid!(
    test_expand_46,
    "def P46() { reflect { signal s: internal bool; } } module m { P46(); }"
);
test_expand_valid!(
    test_expand_47,
    "def P47() { reflect { signal s: internal bool; } } module m { P47(); }"
);
test_expand_valid!(
    test_expand_48,
    "def P48() { reflect { signal s: internal bool; } } module m { P48(); }"
);
test_expand_valid!(
    test_expand_49,
    "def P49() { reflect { signal s: internal bool; } } module m { P49(); }"
);
test_expand_valid!(
    test_expand_50,
    "def P50() { reflect { signal s: internal bool; } } module m { P50(); }"
);
test_expand_valid!(
    test_expand_51,
    "def P51() { reflect { signal s: internal bool; } } module m { P51(); }"
);
test_expand_valid!(
    test_expand_52,
    "def P52() { reflect { signal s: internal bool; } } module m { P52(); }"
);
test_expand_valid!(
    test_expand_53,
    "def P53() { reflect { signal s: internal bool; } } module m { P53(); }"
);
test_expand_valid!(
    test_expand_54,
    "def P54() { reflect { signal s: internal bool; } } module m { P54(); }"
);
test_expand_valid!(
    test_expand_55,
    "def P55() { reflect { signal s: internal bool; } } module m { P55(); }"
);
test_expand_valid!(
    test_expand_56,
    "def P56() { reflect { signal s: internal bool; } } module m { P56(); }"
);
test_expand_valid!(
    test_expand_57,
    "def P57() { reflect { signal s: internal bool; } } module m { P57(); }"
);
test_expand_valid!(
    test_expand_58,
    "def P58() { reflect { signal s: internal bool; } } module m { P58(); }"
);
test_expand_valid!(
    test_expand_59,
    "def P59() { reflect { signal s: internal bool; } } module m { P59(); }"
);
test_expand_valid!(
    test_expand_60,
    "def P60() { reflect { signal s: internal bool; } } module m { P60(); }"
);
test_expand_valid!(
    test_expand_61,
    "def P61() { reflect { signal s: internal bool; } } module m { P61(); }"
);
test_expand_valid!(
    test_expand_62,
    "def P62() { reflect { signal s: internal bool; } } module m { P62(); }"
);
test_expand_valid!(
    test_expand_63,
    "def P63() { reflect { signal s: internal bool; } } module m { P63(); }"
);
test_expand_valid!(
    test_expand_64,
    "def P64() { reflect { signal s: internal bool; } } module m { P64(); }"
);
test_expand_valid!(
    test_expand_65,
    "def P65() { reflect { signal s: internal bool; } } module m { P65(); }"
);
test_expand_valid!(
    test_expand_66,
    "def P66() { reflect { signal s: internal bool; } } module m { P66(); }"
);
test_expand_valid!(
    test_expand_67,
    "def P67() { reflect { signal s: internal bool; } } module m { P67(); }"
);
test_expand_valid!(
    test_expand_68,
    "def P68() { reflect { signal s: internal bool; } } module m { P68(); }"
);
test_expand_valid!(
    test_expand_69,
    "def P69() { reflect { signal s: internal bool; } } module m { P69(); }"
);
test_expand_valid!(
    test_expand_70,
    "def P70() { reflect { signal s: internal bool; } } module m { P70(); }"
);
test_expand_valid!(
    test_expand_71,
    "def P71() { reflect { signal s: internal bool; } } module m { P71(); }"
);
test_expand_valid!(
    test_expand_72,
    "def P72() { reflect { signal s: internal bool; } } module m { P72(); }"
);
test_expand_valid!(
    test_expand_73,
    "def P73() { reflect { signal s: internal bool; } } module m { P73(); }"
);
test_expand_valid!(
    test_expand_74,
    "def P74() { reflect { signal s: internal bool; } } module m { P74(); }"
);
test_expand_valid!(
    test_expand_75,
    "def P75() { reflect { signal s: internal bool; } } module m { P75(); }"
);
test_expand_valid!(
    test_expand_76,
    "def P76() { reflect { signal s: internal bool; } } module m { P76(); }"
);
test_expand_valid!(
    test_expand_77,
    "def P77() { reflect { signal s: internal bool; } } module m { P77(); }"
);
test_expand_valid!(
    test_expand_78,
    "def P78() { reflect { signal s: internal bool; } } module m { P78(); }"
);
test_expand_valid!(
    test_expand_79,
    "def P79() { reflect { signal s: internal bool; } } module m { P79(); }"
);
test_expand_valid!(
    test_expand_80,
    "def P80() { reflect { signal s: internal bool; } } module m { P80(); }"
);
test_expand_valid!(
    test_expand_81,
    "def P81() { reflect { signal s: internal bool; } } module m { P81(); }"
);
test_expand_valid!(
    test_expand_82,
    "def P82() { reflect { signal s: internal bool; } } module m { P82(); }"
);
test_expand_valid!(
    test_expand_83,
    "def P83() { reflect { signal s: internal bool; } } module m { P83(); }"
);
test_expand_valid!(
    test_expand_84,
    "def P84() { reflect { signal s: internal bool; } } module m { P84(); }"
);
test_expand_valid!(
    test_expand_85,
    "def P85() { reflect { signal s: internal bool; } } module m { P85(); }"
);
test_expand_valid!(
    test_expand_86,
    "def P86() { reflect { signal s: internal bool; } } module m { P86(); }"
);
test_expand_valid!(
    test_expand_87,
    "def P87() { reflect { signal s: internal bool; } } module m { P87(); }"
);
test_expand_valid!(
    test_expand_88,
    "def P88() { reflect { signal s: internal bool; } } module m { P88(); }"
);
test_expand_valid!(
    test_expand_89,
    "def P89() { reflect { signal s: internal bool; } } module m { P89(); }"
);
test_expand_valid!(
    test_expand_90,
    "def P90() { reflect { signal s: internal bool; } } module m { P90(); }"
);
test_expand_valid!(
    test_expand_91,
    "def P91() { reflect { signal s: internal bool; } } module m { P91(); }"
);
test_expand_valid!(
    test_expand_92,
    "def P92() { reflect { signal s: internal bool; } } module m { P92(); }"
);
test_expand_valid!(
    test_expand_93,
    "def P93() { reflect { signal s: internal bool; } } module m { P93(); }"
);
test_expand_valid!(
    test_expand_94,
    "def P94() { reflect { signal s: internal bool; } } module m { P94(); }"
);
