// Auto-generated by MIRR compiler (Phase 6)
// Do not edit — regenerate from .mirr source.
// Target: SystemVerilog (.sv)

module pressure_monitor (
  input  logic        clk,
  input  logic        rst_n,
  input  logic [15:0] airway_pressure,
  output logic        clamp_valve
);

  // Temporal signals
  logic        pressure_low_sr_0;
  logic        pressure_low_sr_1;
  logic        pressure_low_sr_2;
  logic        pressure_low_out;

  // ── Temporal Guards ──

  // Guard: pressure_low — when airway_pressure < 50 for 3 cycles
  logic [2:0] pressure_low_sr;
  logic pressure_low_cond;
  assign pressure_low_cond = (airway_pressure < 50);
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n)
      pressure_low_sr <= '0;
    else
      pressure_low_sr <= {pressure_low_cond, pressure_low_sr[2:1]};
  end
  assign pressure_low_out = &pressure_low_sr;

  // ── Reflex Assignments ──

  logic pressure_low_out;

  // Unified Reflex Block for: clamp_valve
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      clamp_valve <= '0;
    end else begin
      if (pressure_low_out) clamp_valve <= 1'b1;
    end
  end

endmodule
