[package]
name = "mirrc-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.mirrc]
path = ".."

[[bin]]
name = "fuzz_parse_mirr"
path = "fuzz_targets/fuzz_parse_mirr.rs"
test = false
doc = false

[[bin]]
name = "fuzz_pipeline"
path = "fuzz_targets/fuzz_pipeline.rs"
test = false
doc = false

[[bin]]
name = "fuzz_typeck"
path = "fuzz_targets/fuzz_typeck.rs"
test = false
doc = false

[[bin]]
name = "fuzz_width"
path = "fuzz_targets/fuzz_width.rs"
test = false
doc = false

[[bin]]
name = "fuzz_sexpr_roundtrip"
path = "fuzz_targets/fuzz_sexpr_roundtrip.rs"
test = false
doc = false

[[bin]]
name = "fuzz_temporal"
path = "fuzz_targets/fuzz_temporal.rs"
test = false
doc = false

[workspace]
members = ["."]
