// Auto-generated by MIRR compiler (Phase 6)
// Do not edit — regenerate from .mirr source.
// Target: SystemVerilog (.sv)

// ── Pattern Expansions ──
// Pattern: external_logic(clk, a, b)

module test_link (
  input  logic        clk,
  input  logic        rst_n,
  input  logic        a,
  output logic        b
);

  // ── Temporal Guards ──

  // ── Structural Module Instantiations ──

  external_logic external_logic_0 (
    clk,
    a,
    b
  );

endmodule
