// Auto-generated by MIRR compiler (Phase 6)
// Do not edit — regenerate from .mirr source.
// Target: SystemVerilog (.sv)

// ── Pattern Expansions ──
// Pattern: router_mod::noc_router(clk, rst_n, port_tx_valid_0, port_tx_data_0, port_tx_valid_1, port_tx_data_1, port_tx_valid_2, port_tx_data_2, port_tx_valid_3, port_tx_data_3, port_tx_valid_4, port_tx_data_4, port_tx_valid_5, port_tx_data_5, port_tx_valid_6, port_tx_data_6, port_tx_valid_7, port_tx_data_7, port_tx_valid_8, port_tx_data_8, port_tx_valid_9, port_tx_data_9, port_tx_valid_10, port_tx_data_10, port_tx_valid_11, port_tx_data_11, port_tx_valid_12, port_tx_data_12, port_tx_valid_13, port_tx_data_13, port_tx_valid_14, port_tx_data_14, port_tx_valid_15, port_tx_data_15, port_rx_valid_0, port_rx_data_0, port_rx_valid_1, port_rx_data_1, port_rx_valid_2, port_rx_data_2, port_rx_valid_3, port_rx_data_3, port_rx_valid_4, port_rx_data_4, port_rx_valid_5, port_rx_data_5, port_rx_valid_6, port_rx_data_6, port_rx_valid_7, port_rx_data_7, port_rx_valid_8, port_rx_data_8, port_rx_valid_9, port_rx_data_9, port_rx_valid_10, port_rx_data_10, port_rx_valid_11, port_rx_data_11, port_rx_valid_12, port_rx_data_12, port_rx_valid_13, port_rx_data_13, port_rx_valid_14, port_rx_data_14, port_rx_valid_15, port_rx_data_15)

module noc_test_wrapper (
  input  logic        clk,
  input  logic        rst_n,
  input  logic        port_tx_valid_0,
  input  logic [63:0] port_tx_data_0,
  input  logic        port_tx_valid_1,
  input  logic [63:0] port_tx_data_1,
  input  logic        port_tx_valid_2,
  input  logic [63:0] port_tx_data_2,
  input  logic        port_tx_valid_3,
  input  logic [63:0] port_tx_data_3,
  input  logic        port_tx_valid_4,
  input  logic [63:0] port_tx_data_4,
  input  logic        port_tx_valid_5,
  input  logic [63:0] port_tx_data_5,
  input  logic        port_tx_valid_6,
  input  logic [63:0] port_tx_data_6,
  input  logic        port_tx_valid_7,
  input  logic [63:0] port_tx_data_7,
  input  logic        port_tx_valid_8,
  input  logic [63:0] port_tx_data_8,
  input  logic        port_tx_valid_9,
  input  logic [63:0] port_tx_data_9,
  input  logic        port_tx_valid_10,
  input  logic [63:0] port_tx_data_10,
  input  logic        port_tx_valid_11,
  input  logic [63:0] port_tx_data_11,
  input  logic        port_tx_valid_12,
  input  logic [63:0] port_tx_data_12,
  input  logic        port_tx_valid_13,
  input  logic [63:0] port_tx_data_13,
  input  logic        port_tx_valid_14,
  input  logic [63:0] port_tx_data_14,
  input  logic        port_tx_valid_15,
  input  logic [63:0] port_tx_data_15,
  output logic        port_rx_valid_0,
  output logic [63:0] port_rx_data_0,
  output logic        port_rx_valid_1,
  output logic [63:0] port_rx_data_1,
  output logic        port_rx_valid_2,
  output logic [63:0] port_rx_data_2,
  output logic        port_rx_valid_3,
  output logic [63:0] port_rx_data_3,
  output logic        port_rx_valid_4,
  output logic [63:0] port_rx_data_4,
  output logic        port_rx_valid_5,
  output logic [63:0] port_rx_data_5,
  output logic        port_rx_valid_6,
  output logic [63:0] port_rx_data_6,
  output logic        port_rx_valid_7,
  output logic [63:0] port_rx_data_7,
  output logic        port_rx_valid_8,
  output logic [63:0] port_rx_data_8,
  output logic        port_rx_valid_9,
  output logic [63:0] port_rx_data_9,
  output logic        port_rx_valid_10,
  output logic [63:0] port_rx_data_10,
  output logic        port_rx_valid_11,
  output logic [63:0] port_rx_data_11,
  output logic        port_rx_valid_12,
  output logic [63:0] port_rx_data_12,
  output logic        port_rx_valid_13,
  output logic [63:0] port_rx_data_13,
  output logic        port_rx_valid_14,
  output logic [63:0] port_rx_data_14,
  output logic        port_rx_valid_15,
  output logic [63:0] port_rx_data_15
);

  // Internal signals
  // Pattern: router_mod_noc_router_0
  logic        router_mod_noc_router_0_sv0;
  // Pattern: router_mod_noc_router_0
  logic [63:0] router_mod_noc_router_0_sd0;
  // Pattern: router_mod_noc_router_0
  logic        router_mod_noc_router_0_sv1;
  // Pattern: router_mod_noc_router_0
  logic [63:0] router_mod_noc_router_0_sd1;
  // Pattern: router_mod_noc_router_0
  logic        router_mod_noc_router_0_sv2;
  // Pattern: router_mod_noc_router_0
  logic [63:0] router_mod_noc_router_0_sd2;
  // Pattern: router_mod_noc_router_0
  logic        router_mod_noc_router_0_sv3;
  // Pattern: router_mod_noc_router_0
  logic [63:0] router_mod_noc_router_0_sd3;
  // Pattern: router_mod_noc_router_0
  logic        router_mod_noc_router_0_sv4;
  // Pattern: router_mod_noc_router_0
  logic [63:0] router_mod_noc_router_0_sd4;
  // Pattern: router_mod_noc_router_0
  logic        router_mod_noc_router_0_sv5;
  // Pattern: router_mod_noc_router_0
  logic [63:0] router_mod_noc_router_0_sd5;
  // Pattern: router_mod_noc_router_0
  logic        router_mod_noc_router_0_sv6;
  // Pattern: router_mod_noc_router_0
  logic [63:0] router_mod_noc_router_0_sd6;
  // Pattern: router_mod_noc_router_0
  logic        router_mod_noc_router_0_sv7;
  // Pattern: router_mod_noc_router_0
  logic [63:0] router_mod_noc_router_0_sd7;
  // Pattern: router_mod_noc_router_0
  logic        router_mod_noc_router_0_sv8;
  // Pattern: router_mod_noc_router_0
  logic [63:0] router_mod_noc_router_0_sd8;
  // Pattern: router_mod_noc_router_0
  logic        router_mod_noc_router_0_sv9;
  // Pattern: router_mod_noc_router_0
  logic [63:0] router_mod_noc_router_0_sd9;
  // Pattern: router_mod_noc_router_0
  logic        router_mod_noc_router_0_sv10;
  // Pattern: router_mod_noc_router_0
  logic [63:0] router_mod_noc_router_0_sd10;
  // Pattern: router_mod_noc_router_0
  logic        router_mod_noc_router_0_sv11;
  // Pattern: router_mod_noc_router_0
  logic [63:0] router_mod_noc_router_0_sd11;
  // Pattern: router_mod_noc_router_0
  logic        router_mod_noc_router_0_sv12;
  // Pattern: router_mod_noc_router_0
  logic [63:0] router_mod_noc_router_0_sd12;
  // Pattern: router_mod_noc_router_0
  logic        router_mod_noc_router_0_sv13;
  // Pattern: router_mod_noc_router_0
  logic [63:0] router_mod_noc_router_0_sd13;
  // Pattern: router_mod_noc_router_0
  logic        router_mod_noc_router_0_sv14;
  // Pattern: router_mod_noc_router_0
  logic [63:0] router_mod_noc_router_0_sd14;
  // Pattern: router_mod_noc_router_0
  logic        router_mod_noc_router_0_sv15;
  // Pattern: router_mod_noc_router_0
  logic [63:0] router_mod_noc_router_0_sd15;
  // Pattern: router_mod_noc_router_0
  logic [63:0] router_mod_noc_router_0_dest_id;
  // Pattern: router_mod_noc_router_0
  logic [63:0] router_mod_noc_router_0_payload;

  // Temporal signals
  logic        router_mod_noc_router_0_n1_sr_0;
  logic        router_mod_noc_router_0_n1_out;
  logic        router_mod_noc_router_0_n2_sr_0;
  logic        router_mod_noc_router_0_n2_out;
  logic        router_mod_noc_router_0_n3_sr_0;
  logic        router_mod_noc_router_0_n3_out;
  logic        router_mod_noc_router_0_n4_sr_0;
  logic        router_mod_noc_router_0_n4_out;
  logic        router_mod_noc_router_0_n5_sr_0;
  logic        router_mod_noc_router_0_n5_out;
  logic        router_mod_noc_router_0_n6_sr_0;
  logic        router_mod_noc_router_0_n6_out;
  logic        router_mod_noc_router_0_n7_sr_0;
  logic        router_mod_noc_router_0_n7_out;
  logic        router_mod_noc_router_0_n8_sr_0;
  logic        router_mod_noc_router_0_n8_out;
  logic        router_mod_noc_router_0_n9_sr_0;
  logic        router_mod_noc_router_0_n9_out;
  logic        router_mod_noc_router_0_n10_sr_0;
  logic        router_mod_noc_router_0_n10_out;
  logic        router_mod_noc_router_0_n11_sr_0;
  logic        router_mod_noc_router_0_n11_out;
  logic        router_mod_noc_router_0_n12_sr_0;
  logic        router_mod_noc_router_0_n12_out;
  logic        router_mod_noc_router_0_n13_sr_0;
  logic        router_mod_noc_router_0_n13_out;
  logic        router_mod_noc_router_0_n14_sr_0;
  logic        router_mod_noc_router_0_n14_out;
  logic        router_mod_noc_router_0_n15_sr_0;
  logic        router_mod_noc_router_0_n15_out;
  logic        always_out;

  // ── Temporal Guards ──

  // Guard: router_mod_noc_router_0_n1 — when !port_tx_valid_1 (low) for 1 cycle (combinational)
  logic router_mod_noc_router_0_n1_cond;
  assign router_mod_noc_router_0_n1_cond = !port_tx_valid_1;
  assign router_mod_noc_router_0_n1_out = router_mod_noc_router_0_n1_cond;

  // Guard: router_mod_noc_router_0_n2 — when !port_tx_valid_2 (low) for 1 cycle (combinational)
  logic router_mod_noc_router_0_n2_cond;
  assign router_mod_noc_router_0_n2_cond = !port_tx_valid_2;
  assign router_mod_noc_router_0_n2_out = router_mod_noc_router_0_n2_cond;

  // Guard: router_mod_noc_router_0_n3 — when !port_tx_valid_3 (low) for 1 cycle (combinational)
  logic router_mod_noc_router_0_n3_cond;
  assign router_mod_noc_router_0_n3_cond = !port_tx_valid_3;
  assign router_mod_noc_router_0_n3_out = router_mod_noc_router_0_n3_cond;

  // Guard: router_mod_noc_router_0_n4 — when !port_tx_valid_4 (low) for 1 cycle (combinational)
  logic router_mod_noc_router_0_n4_cond;
  assign router_mod_noc_router_0_n4_cond = !port_tx_valid_4;
  assign router_mod_noc_router_0_n4_out = router_mod_noc_router_0_n4_cond;

  // Guard: router_mod_noc_router_0_n5 — when !port_tx_valid_5 (low) for 1 cycle (combinational)
  logic router_mod_noc_router_0_n5_cond;
  assign router_mod_noc_router_0_n5_cond = !port_tx_valid_5;
  assign router_mod_noc_router_0_n5_out = router_mod_noc_router_0_n5_cond;

  // Guard: router_mod_noc_router_0_n6 — when !port_tx_valid_6 (low) for 1 cycle (combinational)
  logic router_mod_noc_router_0_n6_cond;
  assign router_mod_noc_router_0_n6_cond = !port_tx_valid_6;
  assign router_mod_noc_router_0_n6_out = router_mod_noc_router_0_n6_cond;

  // Guard: router_mod_noc_router_0_n7 — when !port_tx_valid_7 (low) for 1 cycle (combinational)
  logic router_mod_noc_router_0_n7_cond;
  assign router_mod_noc_router_0_n7_cond = !port_tx_valid_7;
  assign router_mod_noc_router_0_n7_out = router_mod_noc_router_0_n7_cond;

  // Guard: router_mod_noc_router_0_n8 — when !port_tx_valid_8 (low) for 1 cycle (combinational)
  logic router_mod_noc_router_0_n8_cond;
  assign router_mod_noc_router_0_n8_cond = !port_tx_valid_8;
  assign router_mod_noc_router_0_n8_out = router_mod_noc_router_0_n8_cond;

  // Guard: router_mod_noc_router_0_n9 — when !port_tx_valid_9 (low) for 1 cycle (combinational)
  logic router_mod_noc_router_0_n9_cond;
  assign router_mod_noc_router_0_n9_cond = !port_tx_valid_9;
  assign router_mod_noc_router_0_n9_out = router_mod_noc_router_0_n9_cond;

  // Guard: router_mod_noc_router_0_n10 — when !port_tx_valid_10 (low) for 1 cycle (combinational)
  logic router_mod_noc_router_0_n10_cond;
  assign router_mod_noc_router_0_n10_cond = !port_tx_valid_10;
  assign router_mod_noc_router_0_n10_out = router_mod_noc_router_0_n10_cond;

  // Guard: router_mod_noc_router_0_n11 — when !port_tx_valid_11 (low) for 1 cycle (combinational)
  logic router_mod_noc_router_0_n11_cond;
  assign router_mod_noc_router_0_n11_cond = !port_tx_valid_11;
  assign router_mod_noc_router_0_n11_out = router_mod_noc_router_0_n11_cond;

  // Guard: router_mod_noc_router_0_n12 — when !port_tx_valid_12 (low) for 1 cycle (combinational)
  logic router_mod_noc_router_0_n12_cond;
  assign router_mod_noc_router_0_n12_cond = !port_tx_valid_12;
  assign router_mod_noc_router_0_n12_out = router_mod_noc_router_0_n12_cond;

  // Guard: router_mod_noc_router_0_n13 — when !port_tx_valid_13 (low) for 1 cycle (combinational)
  logic router_mod_noc_router_0_n13_cond;
  assign router_mod_noc_router_0_n13_cond = !port_tx_valid_13;
  assign router_mod_noc_router_0_n13_out = router_mod_noc_router_0_n13_cond;

  // Guard: router_mod_noc_router_0_n14 — when !port_tx_valid_14 (low) for 1 cycle (combinational)
  logic router_mod_noc_router_0_n14_cond;
  assign router_mod_noc_router_0_n14_cond = !port_tx_valid_14;
  assign router_mod_noc_router_0_n14_out = router_mod_noc_router_0_n14_cond;

  // Guard: router_mod_noc_router_0_n15 — when !port_tx_valid_15 (low) for 1 cycle (combinational)
  logic router_mod_noc_router_0_n15_cond;
  assign router_mod_noc_router_0_n15_cond = !port_tx_valid_15;
  assign router_mod_noc_router_0_n15_out = router_mod_noc_router_0_n15_cond;

  // Guard: always — always for 0 cycle (combinational)
  logic always_cond;
  assign always_cond = 1'b1;
  assign always_out = always_cond;

  // ── Reflex Assignments ──

  logic always_out;
  logic port_tx_valid_1_out;
  logic router_mod_noc_router_0_n1_out;
  logic port_tx_valid_2_out;
  logic router_mod_noc_router_0_n2_out;
  logic port_tx_valid_3_out;
  logic router_mod_noc_router_0_n3_out;
  logic port_tx_valid_4_out;
  logic router_mod_noc_router_0_n4_out;
  logic port_tx_valid_5_out;
  logic router_mod_noc_router_0_n5_out;
  logic port_tx_valid_6_out;
  logic router_mod_noc_router_0_n6_out;
  logic port_tx_valid_7_out;
  logic router_mod_noc_router_0_n7_out;
  logic port_tx_valid_8_out;
  logic router_mod_noc_router_0_n8_out;
  logic port_tx_valid_9_out;
  logic router_mod_noc_router_0_n9_out;
  logic port_tx_valid_10_out;
  logic router_mod_noc_router_0_n10_out;
  logic port_tx_valid_11_out;
  logic router_mod_noc_router_0_n11_out;
  logic port_tx_valid_12_out;
  logic router_mod_noc_router_0_n12_out;
  logic port_tx_valid_13_out;
  logic router_mod_noc_router_0_n13_out;
  logic port_tx_valid_14_out;
  logic router_mod_noc_router_0_n14_out;
  logic port_tx_valid_15_out;
  logic router_mod_noc_router_0_n15_out;

  // Unified Reflex Block for: port_rx_data_0
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_data_0 <= '0;
    end else begin
      if (always_out) port_rx_data_0 <= router_mod_noc_router_0_payload;
    end
  end

  // Unified Reflex Block for: port_rx_data_1
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_data_1 <= '0;
    end else begin
      if (always_out) port_rx_data_1 <= router_mod_noc_router_0_payload;
    end
  end

  // Unified Reflex Block for: port_rx_data_10
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_data_10 <= '0;
    end else begin
      if (always_out) port_rx_data_10 <= router_mod_noc_router_0_payload;
    end
  end

  // Unified Reflex Block for: port_rx_data_11
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_data_11 <= '0;
    end else begin
      if (always_out) port_rx_data_11 <= router_mod_noc_router_0_payload;
    end
  end

  // Unified Reflex Block for: port_rx_data_12
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_data_12 <= '0;
    end else begin
      if (always_out) port_rx_data_12 <= router_mod_noc_router_0_payload;
    end
  end

  // Unified Reflex Block for: port_rx_data_13
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_data_13 <= '0;
    end else begin
      if (always_out) port_rx_data_13 <= router_mod_noc_router_0_payload;
    end
  end

  // Unified Reflex Block for: port_rx_data_14
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_data_14 <= '0;
    end else begin
      if (always_out) port_rx_data_14 <= router_mod_noc_router_0_payload;
    end
  end

  // Unified Reflex Block for: port_rx_data_15
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_data_15 <= '0;
    end else begin
      if (always_out) port_rx_data_15 <= router_mod_noc_router_0_payload;
    end
  end

  // Unified Reflex Block for: port_rx_data_2
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_data_2 <= '0;
    end else begin
      if (always_out) port_rx_data_2 <= router_mod_noc_router_0_payload;
    end
  end

  // Unified Reflex Block for: port_rx_data_3
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_data_3 <= '0;
    end else begin
      if (always_out) port_rx_data_3 <= router_mod_noc_router_0_payload;
    end
  end

  // Unified Reflex Block for: port_rx_data_4
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_data_4 <= '0;
    end else begin
      if (always_out) port_rx_data_4 <= router_mod_noc_router_0_payload;
    end
  end

  // Unified Reflex Block for: port_rx_data_5
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_data_5 <= '0;
    end else begin
      if (always_out) port_rx_data_5 <= router_mod_noc_router_0_payload;
    end
  end

  // Unified Reflex Block for: port_rx_data_6
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_data_6 <= '0;
    end else begin
      if (always_out) port_rx_data_6 <= router_mod_noc_router_0_payload;
    end
  end

  // Unified Reflex Block for: port_rx_data_7
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_data_7 <= '0;
    end else begin
      if (always_out) port_rx_data_7 <= router_mod_noc_router_0_payload;
    end
  end

  // Unified Reflex Block for: port_rx_data_8
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_data_8 <= '0;
    end else begin
      if (always_out) port_rx_data_8 <= router_mod_noc_router_0_payload;
    end
  end

  // Unified Reflex Block for: port_rx_data_9
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_data_9 <= '0;
    end else begin
      if (always_out) port_rx_data_9 <= router_mod_noc_router_0_payload;
    end
  end

  // Unified Reflex Block for: port_rx_valid_0
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_valid_0 <= '0;
    end else begin
      if (always_out) port_rx_valid_0 <= (router_mod_noc_router_0_sv15 & (router_mod_noc_router_0_dest_id == 0));
    end
  end

  // Unified Reflex Block for: port_rx_valid_1
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_valid_1 <= '0;
    end else begin
      if (always_out) port_rx_valid_1 <= (router_mod_noc_router_0_sv15 & (router_mod_noc_router_0_dest_id == 1));
    end
  end

  // Unified Reflex Block for: port_rx_valid_10
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_valid_10 <= '0;
    end else begin
      if (always_out) port_rx_valid_10 <= (router_mod_noc_router_0_sv15 & (router_mod_noc_router_0_dest_id == 10));
    end
  end

  // Unified Reflex Block for: port_rx_valid_11
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_valid_11 <= '0;
    end else begin
      if (always_out) port_rx_valid_11 <= (router_mod_noc_router_0_sv15 & (router_mod_noc_router_0_dest_id == 11));
    end
  end

  // Unified Reflex Block for: port_rx_valid_12
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_valid_12 <= '0;
    end else begin
      if (always_out) port_rx_valid_12 <= (router_mod_noc_router_0_sv15 & (router_mod_noc_router_0_dest_id == 12));
    end
  end

  // Unified Reflex Block for: port_rx_valid_13
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_valid_13 <= '0;
    end else begin
      if (always_out) port_rx_valid_13 <= (router_mod_noc_router_0_sv15 & (router_mod_noc_router_0_dest_id == 13));
    end
  end

  // Unified Reflex Block for: port_rx_valid_14
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_valid_14 <= '0;
    end else begin
      if (always_out) port_rx_valid_14 <= (router_mod_noc_router_0_sv15 & (router_mod_noc_router_0_dest_id == 14));
    end
  end

  // Unified Reflex Block for: port_rx_valid_15
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_valid_15 <= '0;
    end else begin
      if (always_out) port_rx_valid_15 <= (router_mod_noc_router_0_sv15 & (router_mod_noc_router_0_dest_id == 15));
    end
  end

  // Unified Reflex Block for: port_rx_valid_2
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_valid_2 <= '0;
    end else begin
      if (always_out) port_rx_valid_2 <= (router_mod_noc_router_0_sv15 & (router_mod_noc_router_0_dest_id == 2));
    end
  end

  // Unified Reflex Block for: port_rx_valid_3
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_valid_3 <= '0;
    end else begin
      if (always_out) port_rx_valid_3 <= (router_mod_noc_router_0_sv15 & (router_mod_noc_router_0_dest_id == 3));
    end
  end

  // Unified Reflex Block for: port_rx_valid_4
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_valid_4 <= '0;
    end else begin
      if (always_out) port_rx_valid_4 <= (router_mod_noc_router_0_sv15 & (router_mod_noc_router_0_dest_id == 4));
    end
  end

  // Unified Reflex Block for: port_rx_valid_5
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_valid_5 <= '0;
    end else begin
      if (always_out) port_rx_valid_5 <= (router_mod_noc_router_0_sv15 & (router_mod_noc_router_0_dest_id == 5));
    end
  end

  // Unified Reflex Block for: port_rx_valid_6
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_valid_6 <= '0;
    end else begin
      if (always_out) port_rx_valid_6 <= (router_mod_noc_router_0_sv15 & (router_mod_noc_router_0_dest_id == 6));
    end
  end

  // Unified Reflex Block for: port_rx_valid_7
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_valid_7 <= '0;
    end else begin
      if (always_out) port_rx_valid_7 <= (router_mod_noc_router_0_sv15 & (router_mod_noc_router_0_dest_id == 7));
    end
  end

  // Unified Reflex Block for: port_rx_valid_8
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_valid_8 <= '0;
    end else begin
      if (always_out) port_rx_valid_8 <= (router_mod_noc_router_0_sv15 & (router_mod_noc_router_0_dest_id == 8));
    end
  end

  // Unified Reflex Block for: port_rx_valid_9
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      port_rx_valid_9 <= '0;
    end else begin
      if (always_out) port_rx_valid_9 <= (router_mod_noc_router_0_sv15 & (router_mod_noc_router_0_dest_id == 9));
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_dest_id
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_dest_id <= '0;
    end else begin
      if (always_out) router_mod_noc_router_0_dest_id <= ((router_mod_noc_router_0_sd15 >> 48) & 4095);
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_payload
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_payload <= '0;
    end else begin
      if (always_out) router_mod_noc_router_0_payload <= (router_mod_noc_router_0_sd15 & 281474976710655);
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sd0
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sd0 <= '0;
    end else begin
      if (always_out) router_mod_noc_router_0_sd0 <= port_tx_data_0;
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sd1
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sd1 <= '0;
    end else begin
      if (port_tx_valid_1_out) router_mod_noc_router_0_sd1 <= port_tx_data_1;
      if (router_mod_noc_router_0_n1_out) router_mod_noc_router_0_sd1 <= router_mod_noc_router_0_sd0;
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sd10
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sd10 <= '0;
    end else begin
      if (port_tx_valid_10_out) router_mod_noc_router_0_sd10 <= port_tx_data_10;
      if (router_mod_noc_router_0_n10_out) router_mod_noc_router_0_sd10 <= router_mod_noc_router_0_sd9;
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sd11
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sd11 <= '0;
    end else begin
      if (port_tx_valid_11_out) router_mod_noc_router_0_sd11 <= port_tx_data_11;
      if (router_mod_noc_router_0_n11_out) router_mod_noc_router_0_sd11 <= router_mod_noc_router_0_sd10;
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sd12
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sd12 <= '0;
    end else begin
      if (port_tx_valid_12_out) router_mod_noc_router_0_sd12 <= port_tx_data_12;
      if (router_mod_noc_router_0_n12_out) router_mod_noc_router_0_sd12 <= router_mod_noc_router_0_sd11;
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sd13
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sd13 <= '0;
    end else begin
      if (port_tx_valid_13_out) router_mod_noc_router_0_sd13 <= port_tx_data_13;
      if (router_mod_noc_router_0_n13_out) router_mod_noc_router_0_sd13 <= router_mod_noc_router_0_sd12;
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sd14
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sd14 <= '0;
    end else begin
      if (port_tx_valid_14_out) router_mod_noc_router_0_sd14 <= port_tx_data_14;
      if (router_mod_noc_router_0_n14_out) router_mod_noc_router_0_sd14 <= router_mod_noc_router_0_sd13;
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sd15
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sd15 <= '0;
    end else begin
      if (port_tx_valid_15_out) router_mod_noc_router_0_sd15 <= port_tx_data_15;
      if (router_mod_noc_router_0_n15_out) router_mod_noc_router_0_sd15 <= router_mod_noc_router_0_sd14;
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sd2
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sd2 <= '0;
    end else begin
      if (port_tx_valid_2_out) router_mod_noc_router_0_sd2 <= port_tx_data_2;
      if (router_mod_noc_router_0_n2_out) router_mod_noc_router_0_sd2 <= router_mod_noc_router_0_sd1;
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sd3
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sd3 <= '0;
    end else begin
      if (port_tx_valid_3_out) router_mod_noc_router_0_sd3 <= port_tx_data_3;
      if (router_mod_noc_router_0_n3_out) router_mod_noc_router_0_sd3 <= router_mod_noc_router_0_sd2;
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sd4
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sd4 <= '0;
    end else begin
      if (port_tx_valid_4_out) router_mod_noc_router_0_sd4 <= port_tx_data_4;
      if (router_mod_noc_router_0_n4_out) router_mod_noc_router_0_sd4 <= router_mod_noc_router_0_sd3;
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sd5
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sd5 <= '0;
    end else begin
      if (port_tx_valid_5_out) router_mod_noc_router_0_sd5 <= port_tx_data_5;
      if (router_mod_noc_router_0_n5_out) router_mod_noc_router_0_sd5 <= router_mod_noc_router_0_sd4;
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sd6
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sd6 <= '0;
    end else begin
      if (port_tx_valid_6_out) router_mod_noc_router_0_sd6 <= port_tx_data_6;
      if (router_mod_noc_router_0_n6_out) router_mod_noc_router_0_sd6 <= router_mod_noc_router_0_sd5;
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sd7
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sd7 <= '0;
    end else begin
      if (port_tx_valid_7_out) router_mod_noc_router_0_sd7 <= port_tx_data_7;
      if (router_mod_noc_router_0_n7_out) router_mod_noc_router_0_sd7 <= router_mod_noc_router_0_sd6;
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sd8
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sd8 <= '0;
    end else begin
      if (port_tx_valid_8_out) router_mod_noc_router_0_sd8 <= port_tx_data_8;
      if (router_mod_noc_router_0_n8_out) router_mod_noc_router_0_sd8 <= router_mod_noc_router_0_sd7;
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sd9
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sd9 <= '0;
    end else begin
      if (port_tx_valid_9_out) router_mod_noc_router_0_sd9 <= port_tx_data_9;
      if (router_mod_noc_router_0_n9_out) router_mod_noc_router_0_sd9 <= router_mod_noc_router_0_sd8;
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sv0
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sv0 <= '0;
    end else begin
      if (always_out) router_mod_noc_router_0_sv0 <= port_tx_valid_0;
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sv1
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sv1 <= '0;
    end else begin
      if (port_tx_valid_1_out) router_mod_noc_router_0_sv1 <= 1'b1;
      if (router_mod_noc_router_0_n1_out) router_mod_noc_router_0_sv1 <= router_mod_noc_router_0_sv0;
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sv10
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sv10 <= '0;
    end else begin
      if (port_tx_valid_10_out) router_mod_noc_router_0_sv10 <= 1'b1;
      if (router_mod_noc_router_0_n10_out) router_mod_noc_router_0_sv10 <= router_mod_noc_router_0_sv9;
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sv11
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sv11 <= '0;
    end else begin
      if (port_tx_valid_11_out) router_mod_noc_router_0_sv11 <= 1'b1;
      if (router_mod_noc_router_0_n11_out) router_mod_noc_router_0_sv11 <= router_mod_noc_router_0_sv10;
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sv12
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sv12 <= '0;
    end else begin
      if (port_tx_valid_12_out) router_mod_noc_router_0_sv12 <= 1'b1;
      if (router_mod_noc_router_0_n12_out) router_mod_noc_router_0_sv12 <= router_mod_noc_router_0_sv11;
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sv13
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sv13 <= '0;
    end else begin
      if (port_tx_valid_13_out) router_mod_noc_router_0_sv13 <= 1'b1;
      if (router_mod_noc_router_0_n13_out) router_mod_noc_router_0_sv13 <= router_mod_noc_router_0_sv12;
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sv14
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sv14 <= '0;
    end else begin
      if (port_tx_valid_14_out) router_mod_noc_router_0_sv14 <= 1'b1;
      if (router_mod_noc_router_0_n14_out) router_mod_noc_router_0_sv14 <= router_mod_noc_router_0_sv13;
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sv15
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sv15 <= '0;
    end else begin
      if (port_tx_valid_15_out) router_mod_noc_router_0_sv15 <= 1'b1;
      if (router_mod_noc_router_0_n15_out) router_mod_noc_router_0_sv15 <= router_mod_noc_router_0_sv14;
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sv2
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sv2 <= '0;
    end else begin
      if (port_tx_valid_2_out) router_mod_noc_router_0_sv2 <= 1'b1;
      if (router_mod_noc_router_0_n2_out) router_mod_noc_router_0_sv2 <= router_mod_noc_router_0_sv1;
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sv3
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sv3 <= '0;
    end else begin
      if (port_tx_valid_3_out) router_mod_noc_router_0_sv3 <= 1'b1;
      if (router_mod_noc_router_0_n3_out) router_mod_noc_router_0_sv3 <= router_mod_noc_router_0_sv2;
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sv4
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sv4 <= '0;
    end else begin
      if (port_tx_valid_4_out) router_mod_noc_router_0_sv4 <= 1'b1;
      if (router_mod_noc_router_0_n4_out) router_mod_noc_router_0_sv4 <= router_mod_noc_router_0_sv3;
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sv5
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sv5 <= '0;
    end else begin
      if (port_tx_valid_5_out) router_mod_noc_router_0_sv5 <= 1'b1;
      if (router_mod_noc_router_0_n5_out) router_mod_noc_router_0_sv5 <= router_mod_noc_router_0_sv4;
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sv6
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sv6 <= '0;
    end else begin
      if (port_tx_valid_6_out) router_mod_noc_router_0_sv6 <= 1'b1;
      if (router_mod_noc_router_0_n6_out) router_mod_noc_router_0_sv6 <= router_mod_noc_router_0_sv5;
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sv7
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sv7 <= '0;
    end else begin
      if (port_tx_valid_7_out) router_mod_noc_router_0_sv7 <= 1'b1;
      if (router_mod_noc_router_0_n7_out) router_mod_noc_router_0_sv7 <= router_mod_noc_router_0_sv6;
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sv8
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sv8 <= '0;
    end else begin
      if (port_tx_valid_8_out) router_mod_noc_router_0_sv8 <= 1'b1;
      if (router_mod_noc_router_0_n8_out) router_mod_noc_router_0_sv8 <= router_mod_noc_router_0_sv7;
    end
  end

  // Unified Reflex Block for: router_mod_noc_router_0_sv9
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      router_mod_noc_router_0_sv9 <= '0;
    end else begin
      if (port_tx_valid_9_out) router_mod_noc_router_0_sv9 <= 1'b1;
      if (router_mod_noc_router_0_n9_out) router_mod_noc_router_0_sv9 <= router_mod_noc_router_0_sv8;
    end
  end

endmodule
