// Auto-generated by MIRR compiler (Phase 6)
// Do not edit — regenerate from .mirr source.
// Target: SystemVerilog (.sv)

/* verilator lint_off UNOPTFLAT */
/* verilator lint_off DECLFILENAME */
/* verilator lint_off WIDTH */
/* verilator lint_off WIDTHTRUNC */
/* verilator lint_off WIDTHEXPAND */
/* verilator lint_off SYNCASYNCNET */
/* verilator lint_off PINCONNECTEMPTY */
/* verilator lint_off UNDRIVEN */
/* verilator lint_off UNUSED */

module alu_formal (
  input  logic        clk,
  input  logic        rst_n,
  input  logic [31:0] op,
  input  logic [63:0] d1,
  input  logic [63:0] t1,
  input  logic [63:0] p1,
  input  logic [63:0] d2,
  input  logic [63:0] t2,
  input  logic [63:0] p2,
  output logic [63:0] out_data,
  output logic [63:0] out_tag,
  output logic [63:0] out_prov,
  output logic        trap
);

  // Internal signals
  logic [63:0] alu_core_call_31_res_data;
  logic [63:0] alu_core_call_31_res_tag;
  logic [63:0] alu_core_call_31_res_prov;
  logic        alu_core_call_31_is_trap;
  logic        alu_core_call_31_is_add;
  logic        alu_core_call_31_is_sub;
  logic        alu_core_call_31_is_relu_pos;
  logic        alu_core_call_31_is_relu_neg;
  logic        alu_core_call_31_is_tag_gate;
  logic        alu_core_call_31_is_invalid;

  // Physical Power-On Reset Initialization (Matches FPGA target reality)
  initial begin
    alu_core_call_31_res_data = '0;
    alu_core_call_31_res_tag = '0;
    alu_core_call_31_res_prov = '0;
    alu_core_call_31_is_trap = '0;
    alu_core_call_31_is_add = '0;
    alu_core_call_31_is_sub = '0;
    alu_core_call_31_is_relu_pos = '0;
    alu_core_call_31_is_relu_neg = '0;
    alu_core_call_31_is_tag_gate = '0;
    alu_core_call_31_is_invalid = '0;
  end

  // ── Input Synchronizer Chains ──

  // 2-stage synchronizer for op (@clk)
  logic [63:0] op_sync;
  initial begin
    op_sync = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n)
      op_sync <= '0;
    else
      op_sync <= {op, op_sync[63:32]};
  end
  logic [31:0] op_s = op_sync[31:0];

  // 2-stage synchronizer for d1 (@clk)
  logic [127:0] d1_sync;
  initial begin
    d1_sync = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n)
      d1_sync <= '0;
    else
      d1_sync <= {d1, d1_sync[127:64]};
  end
  logic [63:0] d1_s = d1_sync[63:0];

  // 2-stage synchronizer for t1 (@clk)
  logic [127:0] t1_sync;
  initial begin
    t1_sync = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n)
      t1_sync <= '0;
    else
      t1_sync <= {t1, t1_sync[127:64]};
  end
  logic [63:0] t1_s = t1_sync[63:0];

  // 2-stage synchronizer for p1 (@clk)
  logic [127:0] p1_sync;
  initial begin
    p1_sync = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n)
      p1_sync <= '0;
    else
      p1_sync <= {p1, p1_sync[127:64]};
  end
  logic [63:0] p1_s = p1_sync[63:0];

  // 2-stage synchronizer for d2 (@clk)
  logic [127:0] d2_sync;
  initial begin
    d2_sync = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n)
      d2_sync <= '0;
    else
      d2_sync <= {d2, d2_sync[127:64]};
  end
  logic [63:0] d2_s = d2_sync[63:0];

  // 2-stage synchronizer for t2 (@clk)
  logic [127:0] t2_sync;
  initial begin
    t2_sync = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n)
      t2_sync <= '0;
    else
      t2_sync <= {t2, t2_sync[127:64]};
  end
  logic [63:0] t2_s = t2_sync[63:0];

  // 2-stage synchronizer for p2 (@clk)
  logic [127:0] p2_sync;
  initial begin
    p2_sync = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n)
      p2_sync <= '0;
    else
      p2_sync <= {p2, p2_sync[127:64]};
  end
  logic [63:0] p2_s = p2_sync[63:0];

  // Temporal signals
  logic        alu_core_call_31_is_add_g_sr_0;
  logic        alu_core_call_31_is_add_g_out;
  logic        alu_core_call_31_is_sub_g_sr_0;
  logic        alu_core_call_31_is_sub_g_out;
  logic        alu_core_call_31_is_relu_pos_g_sr_0;
  logic        alu_core_call_31_is_relu_pos_g_out;
  logic        alu_core_call_31_is_relu_neg_g_sr_0;
  logic        alu_core_call_31_is_relu_neg_g_out;
  logic        alu_core_call_31_is_tag_gate_g_sr_0;
  logic        alu_core_call_31_is_tag_gate_g_out;
  logic        alu_core_call_31_is_invalid_g_sr_0;
  logic        alu_core_call_31_is_invalid_g_out;
  logic        alu_core_call_15_is_add_g_sr_0;
  logic        alu_core_call_15_is_add_g_out;
  logic        alu_core_call_15_is_sub_g_sr_0;
  logic        alu_core_call_15_is_sub_g_out;
  logic        alu_core_call_15_is_relu_pos_g_sr_0;
  logic        alu_core_call_15_is_relu_pos_g_out;
  logic        alu_core_call_15_is_relu_neg_g_sr_0;
  logic        alu_core_call_15_is_relu_neg_g_out;
  logic        alu_core_call_15_is_tag_gate_g_sr_0;
  logic        alu_core_call_15_is_tag_gate_g_out;
  logic        alu_core_call_15_is_invalid_g_sr_0;
  logic        alu_core_call_15_is_invalid_g_out;

  // ── Temporal Guards ──


  // Guard: alu_core_call_31_is_add_g (len 25, bytes [97, 108, 117, 95, 99, 111, 114, 101, 95, 99, 97, 108, 108, 95, 51, 49, 95, 105, 115, 95, 97, 100, 100, 95, 103]) — when alu_core_call_31_is_add (high) for 1 cycle (combinational)
  logic alu_core_call_31_is_add_g_cond;
  assign alu_core_call_31_is_add_g_cond = alu_core_call_31_is_add;
  assign alu_core_call_31_is_add_g_out = alu_core_call_31_is_add_g_cond;

  // Guard: alu_core_call_31_is_sub_g (len 25, bytes [97, 108, 117, 95, 99, 111, 114, 101, 95, 99, 97, 108, 108, 95, 51, 49, 95, 105, 115, 95, 115, 117, 98, 95, 103]) — when alu_core_call_31_is_sub (high) for 1 cycle (combinational)
  logic alu_core_call_31_is_sub_g_cond;
  assign alu_core_call_31_is_sub_g_cond = alu_core_call_31_is_sub;
  assign alu_core_call_31_is_sub_g_out = alu_core_call_31_is_sub_g_cond;

  // Guard: alu_core_call_31_is_relu_pos_g (len 30, bytes [97, 108, 117, 95, 99, 111, 114, 101, 95, 99, 97, 108, 108, 95, 51, 49, 95, 105, 115, 95, 114, 101, 108, 117, 95, 112, 111, 115, 95, 103]) — when alu_core_call_31_is_relu_pos (high) for 1 cycle (combinational)
  logic alu_core_call_31_is_relu_pos_g_cond;
  assign alu_core_call_31_is_relu_pos_g_cond = alu_core_call_31_is_relu_pos;
  assign alu_core_call_31_is_relu_pos_g_out = alu_core_call_31_is_relu_pos_g_cond;

  // Guard: alu_core_call_31_is_relu_neg_g (len 30, bytes [97, 108, 117, 95, 99, 111, 114, 101, 95, 99, 97, 108, 108, 95, 51, 49, 95, 105, 115, 95, 114, 101, 108, 117, 95, 110, 101, 103, 95, 103]) — when alu_core_call_31_is_relu_neg (high) for 1 cycle (combinational)
  logic alu_core_call_31_is_relu_neg_g_cond;
  assign alu_core_call_31_is_relu_neg_g_cond = alu_core_call_31_is_relu_neg;
  assign alu_core_call_31_is_relu_neg_g_out = alu_core_call_31_is_relu_neg_g_cond;

  // Guard: alu_core_call_31_is_tag_gate_g (len 30, bytes [97, 108, 117, 95, 99, 111, 114, 101, 95, 99, 97, 108, 108, 95, 51, 49, 95, 105, 115, 95, 116, 97, 103, 95, 103, 97, 116, 101, 95, 103]) — when alu_core_call_31_is_tag_gate (high) for 1 cycle (combinational)
  logic alu_core_call_31_is_tag_gate_g_cond;
  assign alu_core_call_31_is_tag_gate_g_cond = alu_core_call_31_is_tag_gate;
  assign alu_core_call_31_is_tag_gate_g_out = alu_core_call_31_is_tag_gate_g_cond;

  // Guard: alu_core_call_31_is_invalid_g (len 29, bytes [97, 108, 117, 95, 99, 111, 114, 101, 95, 99, 97, 108, 108, 95, 51, 49, 95, 105, 115, 95, 105, 110, 118, 97, 108, 105, 100, 95, 103]) — when alu_core_call_31_is_invalid (high) for 1 cycle (combinational)
  logic alu_core_call_31_is_invalid_g_cond;
  assign alu_core_call_31_is_invalid_g_cond = alu_core_call_31_is_invalid;
  assign alu_core_call_31_is_invalid_g_out = alu_core_call_31_is_invalid_g_cond;

  // ── Reflex Assignments ──

  // ── Reflex Signal Drivers ──

  // Unified Reflex Block for: alu_core_call_31_is_add (@clk)
  initial begin
    alu_core_call_31_is_add = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      alu_core_call_31_is_add <= '0;
    end else begin
      if (1'b1) alu_core_call_31_is_add <= ((op_s == 0) & (t1_s == t2_s));
    end
  end

  // Unified Reflex Block for: alu_core_call_31_is_invalid (@clk)
  initial begin
    alu_core_call_31_is_invalid = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      alu_core_call_31_is_invalid <= '0;
    end else begin
      if (1'b1) alu_core_call_31_is_invalid <= (((((op_s != 0) & (op_s != 1)) & (op_s != 3)) & (op_s != 5)) & (op_s != 6));
    end
  end

  // Unified Reflex Block for: alu_core_call_31_is_relu_neg (@clk)
  initial begin
    alu_core_call_31_is_relu_neg = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      alu_core_call_31_is_relu_neg <= '0;
    end else begin
      if (1'b1) alu_core_call_31_is_relu_neg <= ((op_s == 3) & ((d1_s >> 31) == 1));
    end
  end

  // Unified Reflex Block for: alu_core_call_31_is_relu_pos (@clk)
  initial begin
    alu_core_call_31_is_relu_pos = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      alu_core_call_31_is_relu_pos <= '0;
    end else begin
      if (1'b1) alu_core_call_31_is_relu_pos <= ((op_s == 3) & ((d1_s >> 31) == 0));
    end
  end

  // Unified Reflex Block for: alu_core_call_31_is_sub (@clk)
  initial begin
    alu_core_call_31_is_sub = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      alu_core_call_31_is_sub <= '0;
    end else begin
      if (1'b1) alu_core_call_31_is_sub <= ((op_s == 1) & (t1_s == t2_s));
    end
  end

  // Unified Reflex Block for: alu_core_call_31_is_tag_gate (@clk)
  initial begin
    alu_core_call_31_is_tag_gate = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      alu_core_call_31_is_tag_gate <= '0;
    end else begin
      if (1'b1) alu_core_call_31_is_tag_gate <= (op_s == 5);
    end
  end

  // Unified Reflex Block for: alu_core_call_31_is_trap (@clk)
  initial begin
    alu_core_call_31_is_trap = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      alu_core_call_31_is_trap <= '0;
    end else begin
      if (1'b1) alu_core_call_31_is_trap <= 1'b0;
      if (alu_core_call_31_is_invalid_g_out) alu_core_call_31_is_trap <= 1'b1;
    end
  end

  // Unified Reflex Block for: alu_core_call_31_res_data (@clk)
  initial begin
    alu_core_call_31_res_data = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      alu_core_call_31_res_data <= '0;
    end else begin
      if (1'b1) alu_core_call_31_res_data <= d2_s;
      if (alu_core_call_31_is_add_g_out) alu_core_call_31_res_data <= ((d1_s & 4294967295) + (d2_s & 4294967295));
      if (alu_core_call_31_is_sub_g_out) alu_core_call_31_res_data <= ((d1_s & 4294967295) - (d2_s & 4294967295));
      if (alu_core_call_31_is_relu_pos_g_out) alu_core_call_31_res_data <= d1_s;
      if (alu_core_call_31_is_relu_neg_g_out) alu_core_call_31_res_data <= 0;
      if (alu_core_call_31_is_tag_gate_g_out) alu_core_call_31_res_data <= (((d1_s & 4294967295) * (p1_s & 15)) >> 4);
    end
  end

  // Unified Reflex Block for: alu_core_call_31_res_prov (@clk)
  initial begin
    alu_core_call_31_res_prov = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      alu_core_call_31_res_prov <= '0;
    end else begin
      if (1'b1) alu_core_call_31_res_prov <= p1_s;
    end
  end

  // Unified Reflex Block for: alu_core_call_31_res_tag (@clk)
  initial begin
    alu_core_call_31_res_tag = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      alu_core_call_31_res_tag <= '0;
    end else begin
      if (1'b1) alu_core_call_31_res_tag <= t1_s;
    end
  end

  // Unified Reflex Block for: out_data (@clk)
  initial begin
    out_data = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      out_data <= '0;
    end else begin
      if (1'b1) out_data <= (alu_core_call_31_res_data & 4294967295);
    end
  end

  // Unified Reflex Block for: out_prov (@clk)
  initial begin
    out_prov = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      out_prov <= '0;
    end else begin
      if (1'b1) out_prov <= (alu_core_call_31_res_prov & 15);
    end
  end

  // Unified Reflex Block for: out_tag (@clk)
  initial begin
    out_tag = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      out_tag <= '0;
    end else begin
      if (1'b1) out_tag <= (alu_core_call_31_res_tag & 15);
    end
  end

  // Unified Reflex Block for: trap (@clk)
  initial begin
    trap = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      trap <= '0;
    end else begin
      if (1'b1) trap <= alu_core_call_31_is_trap;
    end
  end

  // ── Safety Properties (SVA) ──

  // Enforce reset sequence for formal verification
  reg f_past_valid = 0;
  always_ff @(posedge clk) begin
    f_past_valid <= 1;
  end
  always_comb begin
    if (!f_past_valid) assume (!rst_n);
  end

  // source: <unknown>:23
  // property: invalid_op_traps
  reg [2:0] prop_invalid_op_traps_trig_shift;
  always @(posedge clk) begin
    if (!rst_n) prop_invalid_op_traps_trig_shift <= 0;
    else prop_invalid_op_traps_trig_shift <= {prop_invalid_op_traps_trig_shift[1:0], (!(((((op_s == 0) | (op_s == 1)) | (op_s == 3)) | (op_s == 5)) | (op_s == 6)))};
  end
  always @(posedge clk) begin
    if (rst_n) begin
      invalid_op_traps: assert((!(prop_invalid_op_traps_trig_shift[2])) || ((trap == 1'b1)));
    end
  end

  // source: <unknown>:28
  // property: valid_op_safe
  reg [2:0] prop_valid_op_safe_trig_shift;
  always @(posedge clk) begin
    if (!rst_n) prop_valid_op_safe_trig_shift <= 0;
    else prop_valid_op_safe_trig_shift <= {prop_valid_op_safe_trig_shift[1:0], (((((op_s == 0) | (op_s == 1)) | (op_s == 3)) | (op_s == 5)) | (op_s == 6))};
  end
  always @(posedge clk) begin
    if (rst_n) begin
      valid_op_safe: assert((!(prop_valid_op_safe_trig_shift[2])) || ((trap == 1'b0)));
    end
  end

endmodule
