// Auto-generated by MIRR compiler (Phase 6)
// Do not edit — regenerate from .mirr source.
// Target: SystemVerilog (.sv)

/* verilator lint_off UNOPTFLAT */
/* verilator lint_off DECLFILENAME */
/* verilator lint_off WIDTH */
/* verilator lint_off WIDTHTRUNC */
/* verilator lint_off WIDTHEXPAND */
/* verilator lint_off SYNCASYNCNET */
/* verilator lint_off PINCONNECTEMPTY */
/* verilator lint_off UNDRIVEN */
/* verilator lint_off UNUSED */

module regfile_formal (
  input  logic        clk,
  input  logic        rst_n,
  output logic [63:0] dout1,
  output logic [63:0] dout2
);

  // Internal signals
  // source: <unknown>:7
  logic [ 9:0] rs1;
  // source: <unknown>:8
  logic [ 9:0] rs2;
  // source: <unknown>:9
  logic [ 9:0] rd;
  // source: <unknown>:10
  logic        we;
  // source: <unknown>:11
  logic [63:0] din;
  // source: <unknown>:18
  logic        we_d1;
  // source: <unknown>:19
  logic [ 9:0] rd_d1;
  // source: <unknown>:20
  logic [63:0] din_d1;

  // Physical Power-On Reset Initialization (Matches FPGA target reality)
  initial begin
    rs1 = '0;
    rs2 = '0;
    rd = '0;
    we = '0;
    din = '0;
    we_d1 = '0;
    rd_d1 = '0;
    din_d1 = '0;
  end

  // ── Input Synchronizer Chains ──

  // Temporal signals
  logic        always_out;

  // ── Temporal Guards ──


  // Guard: always (len 6, bytes [97, 108, 119, 97, 121, 115]) — always for 0 cycle (combinational)
  logic always_cond;
  assign always_cond = 1'b1;
  assign always_out = always_cond;

  // ── Reflex Assignments ──

  // ── Reflex Signal Drivers ──

  // Unified Reflex Block for: din_d1 (@clk)
  initial begin
    din_d1 = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      din_d1 <= '0;
    end else begin
  // source: <unknown>:22
      if (always_out) din_d1 <= din;
    end
  end

  // Unified Reflex Block for: rd_d1 (@clk)
  initial begin
    rd_d1 = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rd_d1 <= '0;
    end else begin
  // source: <unknown>:22
      if (always_out) rd_d1 <= rd;
    end
  end

  // Unified Reflex Block for: we_d1 (@clk)
  initial begin
    we_d1 = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      we_d1 <= '0;
    end else begin
  // source: <unknown>:22
      if (always_out) we_d1 <= we;
    end
  end

  // ── Structural Module Instantiations ──

  regfile rf_regfile_inst_12 (
    .clk(clk),
    .rs1(rs1),
    .rs2(rs2),
    .rd(rd),
    .we(we),
    .din(din),
    .dout1(dout1),
    .dout2(dout2)
  );

  // ── Safety Properties (SVA) ──

  // Enforce reset sequence for formal verification
  reg f_past_valid = 0;
  always_ff @(posedge clk) begin
    f_past_valid <= 1;
  end
  always_comb begin
    if (!f_past_valid) assume (!rst_n);
  end

  // source: <unknown>:31
  // property: read_after_write_1
  always @(posedge clk) begin
    if (rst_n) begin
      read_after_write_1: assert((!((we_d1 & (rs1 == rd_d1)))) || ((dout1 == din_d1)));
    end
  end

  // source: <unknown>:35
  // property: read_after_write_2
  always @(posedge clk) begin
    if (rst_n) begin
      read_after_write_2: assert((!((we_d1 & (rs2 == rd_d1)))) || ((dout2 == din_d1)));
    end
  end

endmodule
