// Auto-generated by MIRR compiler (Phase 6)
// Do not edit — regenerate from .mirr source.
// Target: SystemVerilog (.sv)

/* verilator lint_off UNOPTFLAT */
/* verilator lint_off DECLFILENAME */
/* verilator lint_off WIDTH */
/* verilator lint_off WIDTHTRUNC */
/* verilator lint_off WIDTHEXPAND */
/* verilator lint_off SYNCASYNCNET */
/* verilator lint_off PINCONNECTEMPTY */
/* verilator lint_off UNDRIVEN */
/* verilator lint_off UNUSED */

module test_fail (
  input  logic        clk,
  input  logic        rst_n,
  input  logic        a,
  output logic        b
);

  // ── Input Synchronizer Chains ──

  // 2-stage synchronizer for a (@clk)
  logic [1:0] a_sync;
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n)
      a_sync <= '0;
    else
      a_sync <= {a, a_sync[1:1]};
  end
  logic        a_s = a_sync[0:0];

  // Temporal signals
  logic        always_out;

  // ── Temporal Guards ──


  // Guard: always — always for 0 cycle (combinational)
  logic always_cond;
  assign always_cond = 1'b1;
  assign always_out = always_cond;

  // ── Reflex Assignments ──

  // ── Reflex Signal Drivers ──

  // Unified Reflex Block for: b (@clk)
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      b <= '0;
    end else begin
  // source: <unknown>:12
      if (always_out) b <= a_s;
    end
  end

  // ── Safety Properties (SVA) ──

  // source: <unknown>:18
  // property: must_be_false
  always @(posedge clk) begin
    must_be_false: assert((b == 1'b0));
  end

endmodule
