// Auto-generated by MIRR compiler (Phase 6)
// Do not edit — regenerate from .mirr source.
// Target: SystemVerilog (.sv)

/* verilator lint_off UNOPTFLAT */
/* verilator lint_off DECLFILENAME */
/* verilator lint_off WIDTH */
/* verilator lint_off WIDTHTRUNC */
/* verilator lint_off WIDTHEXPAND */
/* verilator lint_off SYNCASYNCNET */
/* verilator lint_off PINCONNECTEMPTY */
/* verilator lint_off UNDRIVEN */
/* verilator lint_off UNUSED */

module test_fail2 (
  input  logic        clk,
  input  logic        rst_n,
  output logic        b
);

  // ── Input Synchronizer Chains ──

  // Temporal signals
  logic        always_out;

  // ── Temporal Guards ──


  // Guard: always — always for 0 cycle (combinational)
  logic always_cond;
  assign always_cond = 1'b1;
  assign always_out = always_cond;

  // ── Reflex Assignments ──

  // ── Reflex Signal Drivers ──

  // Unified Reflex Block for: b (@clk)
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      b <= '0;
    end else begin
  // source: <unknown>:11
      if (always_out) b <= 1'b1;
    end
  end

  // ── Safety Properties (SVA) ──

  // source: <unknown>:17
  // property: must_be_false
  always @(posedge clk) begin
    must_be_false: assert((b == 1'b0));
  end

endmodule
