// Auto-generated by MIRR compiler (Phase 6)
// Do not edit — regenerate from .mirr source.
// Target: SystemVerilog (.sv)

/* verilator lint_off UNOPTFLAT */
/* verilator lint_off DECLFILENAME */
/* verilator lint_off WIDTH */
/* verilator lint_off WIDTHTRUNC */
/* verilator lint_off WIDTHEXPAND */
/* verilator lint_off SYNCASYNCNET */
/* verilator lint_off PINCONNECTEMPTY */
/* verilator lint_off UNDRIVEN */
/* verilator lint_off UNUSED */

module watchdog_timer (
  input  logic        clk,
  input  logic        rst_n,
  input  logic        heartbeat,
  output logic        watchdog_reset,
  output logic        system_alive
);

  // ── Input Synchronizer Chains ──

  // 2-stage synchronizer for heartbeat (@clk)
  logic [1:0] heartbeat_sync;
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n)
      heartbeat_sync <= '0;
    else
      heartbeat_sync <= {heartbeat, heartbeat_sync[1:1]};
  end
  logic        heartbeat_s = heartbeat_sync[0:0];

  // Temporal signals
  logic [10:0] heartbeat_missing_counter;
  logic        heartbeat_missing_cmp;
  logic        heartbeat_missing_out;
  logic [ 9:0] heartbeat_slow_counter;
  logic        heartbeat_slow_cmp;
  logic        heartbeat_slow_out;

  // ── Temporal Guards ──


  // Guard: heartbeat_missing — when !heartbeat (low) for 1000 cycles (counter)
  logic [10:0] heartbeat_missing_counter;
  logic heartbeat_missing_cond;
  assign heartbeat_missing_cond = !heartbeat;
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n)
      heartbeat_missing_counter <= '0;
    else if (!heartbeat_missing_cond)
      heartbeat_missing_counter <= '0;
    else if (heartbeat_missing_counter < 1000)
      heartbeat_missing_counter <= heartbeat_missing_counter + 1;
  end
  assign heartbeat_missing_out = (heartbeat_missing_counter >= 1000);

  // Guard: heartbeat_slow — when !heartbeat (low) for 500 cycles (counter)
  logic [9:0] heartbeat_slow_counter;
  logic heartbeat_slow_cond;
  assign heartbeat_slow_cond = !heartbeat;
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n)
      heartbeat_slow_counter <= '0;
    else if (!heartbeat_slow_cond)
      heartbeat_slow_counter <= '0;
    else if (heartbeat_slow_counter < 500)
      heartbeat_slow_counter <= heartbeat_slow_counter + 1;
  end
  assign heartbeat_slow_out = (heartbeat_slow_counter >= 500);

  // ── Reflex Assignments ──

  // ── Reflex Signal Drivers ──

  // Unified Reflex Block for: system_alive (@clk)
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      system_alive <= '0;
    end else begin
      if (heartbeat_slow_out) system_alive <= 1'b0;
    end
  end

  // Unified Reflex Block for: watchdog_reset (@clk)
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      watchdog_reset <= '0;
    end else begin
      if (heartbeat_missing_out) watchdog_reset <= 1'b1;
    end
  end

endmodule
