// Auto-generated by MIRR compiler (Phase 6)
// Do not edit — regenerate from .mirr source.
// Target: SystemVerilog (.sv)

module watchdog_timer (
  input  logic        clk,
  input  logic        rst_n,
  input  logic        heartbeat,
  output logic        watchdog_reset,
  output logic        system_alive
);

  // Temporal signals
  logic [10:0] heartbeat_missing_counter;
  logic        heartbeat_missing_cmp;
  logic        heartbeat_missing_out;
  logic [ 9:0] heartbeat_slow_counter;
  logic        heartbeat_slow_cmp;
  logic        heartbeat_slow_out;

  // ── Temporal Guards ──

  // Guard: heartbeat_missing — when !heartbeat (low) for 1000 cycles (counter)
  logic [10:0] heartbeat_missing_counter;
  logic heartbeat_missing_cond;
  assign heartbeat_missing_cond = !heartbeat;
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n)
      heartbeat_missing_counter <= '0;
    else if (!heartbeat_missing_cond)
      heartbeat_missing_counter <= '0;
    else if (heartbeat_missing_counter < 1000)
      heartbeat_missing_counter <= heartbeat_missing_counter + 1;
  end
  assign heartbeat_missing_out = (heartbeat_missing_counter >= 1000);

  // Guard: heartbeat_slow — when !heartbeat (low) for 500 cycles (counter)
  logic [9:0] heartbeat_slow_counter;
  logic heartbeat_slow_cond;
  assign heartbeat_slow_cond = !heartbeat;
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n)
      heartbeat_slow_counter <= '0;
    else if (!heartbeat_slow_cond)
      heartbeat_slow_counter <= '0;
    else if (heartbeat_slow_counter < 500)
      heartbeat_slow_counter <= heartbeat_slow_counter + 1;
  end
  assign heartbeat_slow_out = (heartbeat_slow_counter >= 500);

  // ── Reflex Assignments ──

  logic heartbeat_missing_out;
  logic heartbeat_slow_out;

  // Unified Reflex Block for: system_alive
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      system_alive <= '0;
    end else begin
      if (heartbeat_slow_out) system_alive <= 1'b0;
    end
  end

  // Unified Reflex Block for: watchdog_reset
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      watchdog_reset <= '0;
    end else begin
      if (heartbeat_missing_out) watchdog_reset <= 1'b1;
    end
  end

endmodule
