// Auto-generated by MIRR compiler (Phase 6)
// Do not edit — regenerate from .mirr source.
// Target: SystemVerilog (.sv)

/* verilator lint_off UNOPTFLAT */
/* verilator lint_off DECLFILENAME */
/* verilator lint_off WIDTH */
/* verilator lint_off WIDTHTRUNC */
/* verilator lint_off WIDTHEXPAND */
/* verilator lint_off SYNCASYNCNET */
/* verilator lint_off PINCONNECTEMPTY */
/* verilator lint_off UNDRIVEN */
/* verilator lint_off UNUSED */

module core_top_formal (
  input  logic        clk,
  input  logic        rst_n,
  output logic [63:0] io_out_0,
  output logic [31:0] pc_out,
  output logic [63:0] data_out,
  output logic        noc_tx_valid,
  output logic [63:0] noc_tx_data
);

  // Internal signals
  // source: <unknown>:7
  logic [63:0] io_in_0;
  // source: <unknown>:13
  logic        noc_rx_valid;
  // source: <unknown>:14
  logic [63:0] noc_rx_data;
  logic        core_top_call_41_trap_signal;
  logic [63:0] core_top_call_41_current_instr;
  logic [ 2:0] core_top_call_41_wake_timer;
  logic        core_top_call_41_core_awake;
  logic        core_top_call_41_gated_clk;
  logic        core_top_call_41_core_halted;
  logic [31:0] rspu_pipeline_call_110_if_id_pc;
  logic [63:0] rspu_pipeline_call_110_if_id_instr;
  logic [31:0] rspu_pipeline_call_110_id_ex_pc;
  logic [63:0] rspu_pipeline_call_110_id_ex_rs1;
  logic [63:0] rspu_pipeline_call_110_id_ex_rs2;
  logic [63:0] rspu_pipeline_call_110_id_ex_rd;
  logic [63:0] rspu_pipeline_call_110_id_ex_val1;
  logic [63:0] rspu_pipeline_call_110_id_ex_val2;
  logic [63:0] rspu_pipeline_call_110_id_ex_op;
  logic [63:0] rspu_pipeline_call_110_ex_mem_rd;
  logic [63:0] rspu_pipeline_call_110_ex_mem_res;
  logic [63:0] rspu_pipeline_call_110_ex_mem_op;
  logic [63:0] rspu_pipeline_call_110_mem_wb_rd;
  logic [63:0] rspu_pipeline_call_110_mem_wb_res;
  logic        rspu_pipeline_call_110_mem_wb_we;
  logic [31:0] rspu_pipeline_call_110_pipe_pc;
  logic        rspu_pipeline_call_110_pcc_valid;
  logic        rspu_pipeline_call_110_pcc_fault;
  logic [15:0] rspu_pipeline_call_110_cert_i;
  logic [15:0] rspu_pipeline_call_110_cert_r;
  logic [15:0] rspu_pipeline_call_110_cert_g;
  logic [63:0] rspu_pipeline_call_110_id_val1;
  logic [63:0] rspu_pipeline_call_110_id_val2;
  logic [63:0] rspu_pipeline_call_110_dec_rs1;
  logic [63:0] rspu_pipeline_call_110_dec_rs2;
  logic [63:0] rspu_pipeline_call_110_dec_rd;
  logic [63:0] rspu_pipeline_call_110_dec_op;
  logic [63:0] rspu_pipeline_call_110_ex_d1;
  logic [63:0] rspu_pipeline_call_110_ex_t1;
  logic [63:0] rspu_pipeline_call_110_ex_p1;
  logic [63:0] rspu_pipeline_call_110_ex_d2;
  logic [63:0] rspu_pipeline_call_110_ex_t2;
  logic [63:0] rspu_pipeline_call_110_ex_p2;
  logic [63:0] rspu_pipeline_call_110_ex_out_d;
  logic [63:0] rspu_pipeline_call_110_ex_out_t;
  logic [63:0] rspu_pipeline_call_110_ex_out_p;
  logic        rspu_pipeline_call_110_ex_trap;
  logic [63:0] rspu_pipeline_call_110_ex_packed;
  logic        rspu_pipeline_call_110_is_load_in;
  logic        rspu_pipeline_call_110_is_store_out;
  logic        rspu_pipeline_call_110_is_normal_ex;
  logic [63:0] rspu_pipeline_call_110_mem_out;
  logic [31:0] rspu_pipeline_call_110_ram_addr;
  logic        rspu_pipeline_call_110_is_load;
  logic        rspu_pipeline_call_110_is_not_load;
  logic        ram_call_330__interface_active;
  logic [63:0] alu_core_call_328_res_data;
  logic [63:0] alu_core_call_328_res_tag;
  logic [63:0] alu_core_call_328_res_prov;
  logic        alu_core_call_328_is_trap;
  logic        alu_core_call_328_is_add;
  logic        alu_core_call_328_is_sub;
  logic        alu_core_call_328_is_relu_pos;
  logic        alu_core_call_328_is_relu_neg;
  logic        alu_core_call_328_is_tag_gate;
  logic        alu_core_call_328_is_invalid;
  logic [15:0] pcc_verifier_call_312_MAX_INSTRUCTIONS;
  logic [15:0] pcc_verifier_call_312_MAX_REGISTERS;
  logic [15:0] pcc_verifier_call_312_MAX_GUARDS;
  logic        pcc_verifier_call_312_is_invalid;

  // Physical Power-On Reset Initialization (Matches FPGA target reality)
  initial begin
    io_in_0 = '0;
    noc_rx_valid = '0;
    noc_rx_data = '0;
    core_top_call_41_trap_signal = '0;
    core_top_call_41_current_instr = '0;
    core_top_call_41_wake_timer = '0;
    core_top_call_41_core_awake = '0;
    core_top_call_41_gated_clk = '0;
    core_top_call_41_core_halted = '0;
    rspu_pipeline_call_110_if_id_pc = '0;
    rspu_pipeline_call_110_if_id_instr = '0;
    rspu_pipeline_call_110_id_ex_pc = '0;
    rspu_pipeline_call_110_id_ex_rs1 = '0;
    rspu_pipeline_call_110_id_ex_rs2 = '0;
    rspu_pipeline_call_110_id_ex_rd = '0;
    rspu_pipeline_call_110_id_ex_val1 = '0;
    rspu_pipeline_call_110_id_ex_val2 = '0;
    rspu_pipeline_call_110_id_ex_op = '0;
    rspu_pipeline_call_110_ex_mem_rd = '0;
    rspu_pipeline_call_110_ex_mem_res = '0;
    rspu_pipeline_call_110_ex_mem_op = '0;
    rspu_pipeline_call_110_mem_wb_rd = '0;
    rspu_pipeline_call_110_mem_wb_res = '0;
    rspu_pipeline_call_110_mem_wb_we = '0;
    rspu_pipeline_call_110_pipe_pc = '0;
    rspu_pipeline_call_110_pcc_valid = '0;
    rspu_pipeline_call_110_pcc_fault = '0;
    rspu_pipeline_call_110_cert_i = '0;
    rspu_pipeline_call_110_cert_r = '0;
    rspu_pipeline_call_110_cert_g = '0;
    rspu_pipeline_call_110_id_val1 = '0;
    rspu_pipeline_call_110_id_val2 = '0;
    rspu_pipeline_call_110_dec_rs1 = '0;
    rspu_pipeline_call_110_dec_rs2 = '0;
    rspu_pipeline_call_110_dec_rd = '0;
    rspu_pipeline_call_110_dec_op = '0;
    rspu_pipeline_call_110_ex_d1 = '0;
    rspu_pipeline_call_110_ex_t1 = '0;
    rspu_pipeline_call_110_ex_p1 = '0;
    rspu_pipeline_call_110_ex_d2 = '0;
    rspu_pipeline_call_110_ex_t2 = '0;
    rspu_pipeline_call_110_ex_p2 = '0;
    rspu_pipeline_call_110_ex_out_d = '0;
    rspu_pipeline_call_110_ex_out_t = '0;
    rspu_pipeline_call_110_ex_out_p = '0;
    rspu_pipeline_call_110_ex_trap = '0;
    rspu_pipeline_call_110_ex_packed = '0;
    rspu_pipeline_call_110_is_load_in = '0;
    rspu_pipeline_call_110_is_store_out = '0;
    rspu_pipeline_call_110_is_normal_ex = '0;
    rspu_pipeline_call_110_mem_out = '0;
    rspu_pipeline_call_110_ram_addr = '0;
    rspu_pipeline_call_110_is_load = '0;
    rspu_pipeline_call_110_is_not_load = '0;
    ram_call_330__interface_active = '0;
    alu_core_call_328_res_data = '0;
    alu_core_call_328_res_tag = '0;
    alu_core_call_328_res_prov = '0;
    alu_core_call_328_is_trap = '0;
    alu_core_call_328_is_add = '0;
    alu_core_call_328_is_sub = '0;
    alu_core_call_328_is_relu_pos = '0;
    alu_core_call_328_is_relu_neg = '0;
    alu_core_call_328_is_tag_gate = '0;
    alu_core_call_328_is_invalid = '0;
    pcc_verifier_call_312_MAX_INSTRUCTIONS = '0;
    pcc_verifier_call_312_MAX_REGISTERS = '0;
    pcc_verifier_call_312_MAX_GUARDS = '0;
    pcc_verifier_call_312_is_invalid = '0;
  end

  // ── Input Synchronizer Chains ──

  // Temporal signals
  logic        core_top_call_41_rx_only_sr_0;
  logic        core_top_call_41_rx_only_out;
  logic        sub_g_not_noc_rx_valid_f07eb4674d02d1f8_sr_0;
  logic        sub_g_not_noc_rx_valid_f07eb4674d02d1f8_out;
  logic        sub_g_core_top_call_41_wake_ti_a5a6f7e268f4353d_sr_0;
  logic        sub_g_core_top_call_41_wake_ti_a5a6f7e268f4353d_out;
  logic        core_top_call_41_dec_only_out;
  logic        core_top_call_41_trap_active_sr_0;
  logic        core_top_call_41_trap_active_out;
  logic        rspu_pipeline_call_110_fetch_active_sr_0;
  logic        rspu_pipeline_call_110_fetch_active_out;
  logic        rspu_pipeline_call_110_fetch_fault_sr_0;
  logic        rspu_pipeline_call_110_fetch_fault_out;
  logic        rspu_pipeline_call_110_is_load_in_g_sr_0;
  logic        rspu_pipeline_call_110_is_load_in_g_out;
  logic        rspu_pipeline_call_110_is_store_out_g_sr_0;
  logic        rspu_pipeline_call_110_is_store_out_g_out;
  logic        rspu_pipeline_call_110_is_normal_ex_g_sr_0;
  logic        rspu_pipeline_call_110_is_normal_ex_g_out;
  logic        rspu_pipeline_call_110_is_load_g_sr_0;
  logic        rspu_pipeline_call_110_is_load_g_out;
  logic        rspu_pipeline_call_110_is_not_load_g_sr_0;
  logic        rspu_pipeline_call_110_is_not_load_g_out;
  logic        alu_core_call_328_is_add_g_sr_0;
  logic        alu_core_call_328_is_add_g_out;
  logic        alu_core_call_328_is_sub_g_sr_0;
  logic        alu_core_call_328_is_sub_g_out;
  logic        alu_core_call_328_is_relu_pos_g_sr_0;
  logic        alu_core_call_328_is_relu_pos_g_out;
  logic        alu_core_call_328_is_relu_neg_g_sr_0;
  logic        alu_core_call_328_is_relu_neg_g_out;
  logic        alu_core_call_328_is_tag_gate_g_sr_0;
  logic        alu_core_call_328_is_tag_gate_g_out;
  logic        alu_core_call_328_is_invalid_g_sr_0;
  logic        alu_core_call_328_is_invalid_g_out;
  logic        alu_core_call_19_is_add_g_sr_0;
  logic        alu_core_call_19_is_add_g_out;
  logic        alu_core_call_19_is_sub_g_sr_0;
  logic        alu_core_call_19_is_sub_g_out;
  logic        alu_core_call_19_is_relu_pos_g_sr_0;
  logic        alu_core_call_19_is_relu_pos_g_out;
  logic        alu_core_call_19_is_relu_neg_g_sr_0;
  logic        alu_core_call_19_is_relu_neg_g_out;
  logic        alu_core_call_19_is_tag_gate_g_sr_0;
  logic        alu_core_call_19_is_tag_gate_g_out;
  logic        alu_core_call_19_is_invalid_g_sr_0;
  logic        alu_core_call_19_is_invalid_g_out;

  // ── Temporal Guards ──


  // Guard: core_top_call_41_rx_only (len 24, bytes [99, 111, 114, 101, 95, 116, 111, 112, 95, 99, 97, 108, 108, 95, 52, 49, 95, 114, 120, 95, 111, 110, 108, 121]) — when noc_rx_valid (high) for 1 cycle (combinational)
  logic core_top_call_41_rx_only_cond;
  assign core_top_call_41_rx_only_cond = noc_rx_valid;
  assign core_top_call_41_rx_only_out = core_top_call_41_rx_only_cond;

  // Complex guard: core_top_call_41_dec_only (sub-guards combined)
  assign core_top_call_41_dec_only_out = (sub_g_not_noc_rx_valid_f07eb4674d02d1f8_out && sub_g_core_top_call_41_wake_ti_a5a6f7e268f4353d_out);

  // Guard: core_top_call_41_trap_active (len 28, bytes [99, 111, 114, 101, 95, 116, 111, 112, 95, 99, 97, 108, 108, 95, 52, 49, 95, 116, 114, 97, 112, 95, 97, 99, 116, 105, 118, 101]) — when core_top_call_41_trap_signal (high) for 1 cycle (combinational)
  logic core_top_call_41_trap_active_cond;
  assign core_top_call_41_trap_active_cond = core_top_call_41_trap_signal;
  assign core_top_call_41_trap_active_out = core_top_call_41_trap_active_cond;

  // Guard: rspu_pipeline_call_110_fetch_active (len 35, bytes [114, 115, 112, 117, 95, 112, 105, 112, 101, 108, 105, 110, 101, 95, 99, 97, 108, 108, 95, 49, 49, 48, 95, 102, 101, 116, 99, 104, 95, 97, 99, 116, 105, 118, 101]) — when rspu_pipeline_call_110_pcc_valid (high) for 1 cycle (combinational)
  logic rspu_pipeline_call_110_fetch_active_cond;
  assign rspu_pipeline_call_110_fetch_active_cond = rspu_pipeline_call_110_pcc_valid;
  assign rspu_pipeline_call_110_fetch_active_out = rspu_pipeline_call_110_fetch_active_cond;

  // Guard: rspu_pipeline_call_110_fetch_fault (len 34, bytes [114, 115, 112, 117, 95, 112, 105, 112, 101, 108, 105, 110, 101, 95, 99, 97, 108, 108, 95, 49, 49, 48, 95, 102, 101, 116, 99, 104, 95, 102, 97, 117, 108, 116]) — when rspu_pipeline_call_110_pcc_fault (high) for 1 cycle (combinational)
  logic rspu_pipeline_call_110_fetch_fault_cond;
  assign rspu_pipeline_call_110_fetch_fault_cond = rspu_pipeline_call_110_pcc_fault;
  assign rspu_pipeline_call_110_fetch_fault_out = rspu_pipeline_call_110_fetch_fault_cond;

  // Guard: rspu_pipeline_call_110_is_load_in_g (len 35, bytes [114, 115, 112, 117, 95, 112, 105, 112, 101, 108, 105, 110, 101, 95, 99, 97, 108, 108, 95, 49, 49, 48, 95, 105, 115, 95, 108, 111, 97, 100, 95, 105, 110, 95, 103]) — when rspu_pipeline_call_110_is_load_in (high) for 1 cycle (combinational)
  logic rspu_pipeline_call_110_is_load_in_g_cond;
  assign rspu_pipeline_call_110_is_load_in_g_cond = rspu_pipeline_call_110_is_load_in;
  assign rspu_pipeline_call_110_is_load_in_g_out = rspu_pipeline_call_110_is_load_in_g_cond;

  // Guard: rspu_pipeline_call_110_is_store_out_g (len 37, bytes [114, 115, 112, 117, 95, 112, 105, 112, 101, 108, 105, 110, 101, 95, 99, 97, 108, 108, 95, 49, 49, 48, 95, 105, 115, 95, 115, 116, 111, 114, 101, 95, 111, 117, 116, 95, 103]) — when rspu_pipeline_call_110_is_store_out (high) for 1 cycle (combinational)
  logic rspu_pipeline_call_110_is_store_out_g_cond;
  assign rspu_pipeline_call_110_is_store_out_g_cond = rspu_pipeline_call_110_is_store_out;
  assign rspu_pipeline_call_110_is_store_out_g_out = rspu_pipeline_call_110_is_store_out_g_cond;

  // Guard: rspu_pipeline_call_110_is_normal_ex_g (len 37, bytes [114, 115, 112, 117, 95, 112, 105, 112, 101, 108, 105, 110, 101, 95, 99, 97, 108, 108, 95, 49, 49, 48, 95, 105, 115, 95, 110, 111, 114, 109, 97, 108, 95, 101, 120, 95, 103]) — when rspu_pipeline_call_110_is_normal_ex (high) for 1 cycle (combinational)
  logic rspu_pipeline_call_110_is_normal_ex_g_cond;
  assign rspu_pipeline_call_110_is_normal_ex_g_cond = rspu_pipeline_call_110_is_normal_ex;
  assign rspu_pipeline_call_110_is_normal_ex_g_out = rspu_pipeline_call_110_is_normal_ex_g_cond;

  // Guard: rspu_pipeline_call_110_is_load_g (len 32, bytes [114, 115, 112, 117, 95, 112, 105, 112, 101, 108, 105, 110, 101, 95, 99, 97, 108, 108, 95, 49, 49, 48, 95, 105, 115, 95, 108, 111, 97, 100, 95, 103]) — when rspu_pipeline_call_110_is_load (high) for 1 cycle (combinational)
  logic rspu_pipeline_call_110_is_load_g_cond;
  assign rspu_pipeline_call_110_is_load_g_cond = rspu_pipeline_call_110_is_load;
  assign rspu_pipeline_call_110_is_load_g_out = rspu_pipeline_call_110_is_load_g_cond;

  // Guard: rspu_pipeline_call_110_is_not_load_g (len 36, bytes [114, 115, 112, 117, 95, 112, 105, 112, 101, 108, 105, 110, 101, 95, 99, 97, 108, 108, 95, 49, 49, 48, 95, 105, 115, 95, 110, 111, 116, 95, 108, 111, 97, 100, 95, 103]) — when rspu_pipeline_call_110_is_not_load (high) for 1 cycle (combinational)
  logic rspu_pipeline_call_110_is_not_load_g_cond;
  assign rspu_pipeline_call_110_is_not_load_g_cond = rspu_pipeline_call_110_is_not_load;
  assign rspu_pipeline_call_110_is_not_load_g_out = rspu_pipeline_call_110_is_not_load_g_cond;

  // Guard: alu_core_call_328_is_add_g (len 26, bytes [97, 108, 117, 95, 99, 111, 114, 101, 95, 99, 97, 108, 108, 95, 51, 50, 56, 95, 105, 115, 95, 97, 100, 100, 95, 103]) — when alu_core_call_328_is_add (high) for 1 cycle (combinational)
  logic alu_core_call_328_is_add_g_cond;
  assign alu_core_call_328_is_add_g_cond = alu_core_call_328_is_add;
  assign alu_core_call_328_is_add_g_out = alu_core_call_328_is_add_g_cond;

  // Guard: alu_core_call_328_is_sub_g (len 26, bytes [97, 108, 117, 95, 99, 111, 114, 101, 95, 99, 97, 108, 108, 95, 51, 50, 56, 95, 105, 115, 95, 115, 117, 98, 95, 103]) — when alu_core_call_328_is_sub (high) for 1 cycle (combinational)
  logic alu_core_call_328_is_sub_g_cond;
  assign alu_core_call_328_is_sub_g_cond = alu_core_call_328_is_sub;
  assign alu_core_call_328_is_sub_g_out = alu_core_call_328_is_sub_g_cond;

  // Guard: alu_core_call_328_is_relu_pos_g (len 31, bytes [97, 108, 117, 95, 99, 111, 114, 101, 95, 99, 97, 108, 108, 95, 51, 50, 56, 95, 105, 115, 95, 114, 101, 108, 117, 95, 112, 111, 115, 95, 103]) — when alu_core_call_328_is_relu_pos (high) for 1 cycle (combinational)
  logic alu_core_call_328_is_relu_pos_g_cond;
  assign alu_core_call_328_is_relu_pos_g_cond = alu_core_call_328_is_relu_pos;
  assign alu_core_call_328_is_relu_pos_g_out = alu_core_call_328_is_relu_pos_g_cond;

  // Guard: alu_core_call_328_is_relu_neg_g (len 31, bytes [97, 108, 117, 95, 99, 111, 114, 101, 95, 99, 97, 108, 108, 95, 51, 50, 56, 95, 105, 115, 95, 114, 101, 108, 117, 95, 110, 101, 103, 95, 103]) — when alu_core_call_328_is_relu_neg (high) for 1 cycle (combinational)
  logic alu_core_call_328_is_relu_neg_g_cond;
  assign alu_core_call_328_is_relu_neg_g_cond = alu_core_call_328_is_relu_neg;
  assign alu_core_call_328_is_relu_neg_g_out = alu_core_call_328_is_relu_neg_g_cond;

  // Guard: alu_core_call_328_is_tag_gate_g (len 31, bytes [97, 108, 117, 95, 99, 111, 114, 101, 95, 99, 97, 108, 108, 95, 51, 50, 56, 95, 105, 115, 95, 116, 97, 103, 95, 103, 97, 116, 101, 95, 103]) — when alu_core_call_328_is_tag_gate (high) for 1 cycle (combinational)
  logic alu_core_call_328_is_tag_gate_g_cond;
  assign alu_core_call_328_is_tag_gate_g_cond = alu_core_call_328_is_tag_gate;
  assign alu_core_call_328_is_tag_gate_g_out = alu_core_call_328_is_tag_gate_g_cond;

  // Guard: alu_core_call_328_is_invalid_g (len 30, bytes [97, 108, 117, 95, 99, 111, 114, 101, 95, 99, 97, 108, 108, 95, 51, 50, 56, 95, 105, 115, 95, 105, 110, 118, 97, 108, 105, 100, 95, 103]) — when alu_core_call_328_is_invalid (high) for 1 cycle (combinational)
  logic alu_core_call_328_is_invalid_g_cond;
  assign alu_core_call_328_is_invalid_g_cond = alu_core_call_328_is_invalid;
  assign alu_core_call_328_is_invalid_g_out = alu_core_call_328_is_invalid_g_cond;

  // ── Reflex Assignments ──

  // ── Reflex Signal Drivers ──

  // Unified Reflex Block for: alu_core_call_328_is_add (@clk)
  initial begin
    alu_core_call_328_is_add = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      alu_core_call_328_is_add <= '0;
    end else begin
      if (1'b1) alu_core_call_328_is_add <= ((rspu_pipeline_call_110_id_ex_op == 0) & (rspu_pipeline_call_110_ex_t1 == rspu_pipeline_call_110_ex_t2));
    end
  end

  // Unified Reflex Block for: alu_core_call_328_is_invalid (@clk)
  initial begin
    alu_core_call_328_is_invalid = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      alu_core_call_328_is_invalid <= '0;
    end else begin
      if (1'b1) alu_core_call_328_is_invalid <= (((((rspu_pipeline_call_110_id_ex_op != 0) & (rspu_pipeline_call_110_id_ex_op != 1)) & (rspu_pipeline_call_110_id_ex_op != 3)) & (rspu_pipeline_call_110_id_ex_op != 5)) & (rspu_pipeline_call_110_id_ex_op != 6));
    end
  end

  // Unified Reflex Block for: alu_core_call_328_is_relu_neg (@clk)
  initial begin
    alu_core_call_328_is_relu_neg = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      alu_core_call_328_is_relu_neg <= '0;
    end else begin
      if (1'b1) alu_core_call_328_is_relu_neg <= ((rspu_pipeline_call_110_id_ex_op == 3) & ((rspu_pipeline_call_110_ex_d1 >> 31) == 1));
    end
  end

  // Unified Reflex Block for: alu_core_call_328_is_relu_pos (@clk)
  initial begin
    alu_core_call_328_is_relu_pos = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      alu_core_call_328_is_relu_pos <= '0;
    end else begin
      if (1'b1) alu_core_call_328_is_relu_pos <= ((rspu_pipeline_call_110_id_ex_op == 3) & ((rspu_pipeline_call_110_ex_d1 >> 31) == 0));
    end
  end

  // Unified Reflex Block for: alu_core_call_328_is_sub (@clk)
  initial begin
    alu_core_call_328_is_sub = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      alu_core_call_328_is_sub <= '0;
    end else begin
      if (1'b1) alu_core_call_328_is_sub <= ((rspu_pipeline_call_110_id_ex_op == 1) & (rspu_pipeline_call_110_ex_t1 == rspu_pipeline_call_110_ex_t2));
    end
  end

  // Unified Reflex Block for: alu_core_call_328_is_tag_gate (@clk)
  initial begin
    alu_core_call_328_is_tag_gate = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      alu_core_call_328_is_tag_gate <= '0;
    end else begin
      if (1'b1) alu_core_call_328_is_tag_gate <= (rspu_pipeline_call_110_id_ex_op == 5);
    end
  end

  // Unified Reflex Block for: alu_core_call_328_is_trap (@clk)
  initial begin
    alu_core_call_328_is_trap = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      alu_core_call_328_is_trap <= '0;
    end else begin
      if (1'b1) alu_core_call_328_is_trap <= 1'b0;
      if (alu_core_call_328_is_invalid_g_out) alu_core_call_328_is_trap <= 1'b1;
    end
  end

  // Unified Reflex Block for: alu_core_call_328_res_data (@clk)
  initial begin
    alu_core_call_328_res_data = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      alu_core_call_328_res_data <= '0;
    end else begin
      if (1'b1) alu_core_call_328_res_data <= rspu_pipeline_call_110_ex_d2;
      if (alu_core_call_328_is_add_g_out) alu_core_call_328_res_data <= ((rspu_pipeline_call_110_ex_d1 & 4294967295) + (rspu_pipeline_call_110_ex_d2 & 4294967295));
      if (alu_core_call_328_is_sub_g_out) alu_core_call_328_res_data <= ((rspu_pipeline_call_110_ex_d1 & 4294967295) - (rspu_pipeline_call_110_ex_d2 & 4294967295));
      if (alu_core_call_328_is_relu_pos_g_out) alu_core_call_328_res_data <= rspu_pipeline_call_110_ex_d1;
      if (alu_core_call_328_is_relu_neg_g_out) alu_core_call_328_res_data <= 0;
      if (alu_core_call_328_is_tag_gate_g_out) alu_core_call_328_res_data <= (((rspu_pipeline_call_110_ex_d1 & 4294967295) * (rspu_pipeline_call_110_ex_p1 & 15)) >> 4);
    end
  end

  // Unified Reflex Block for: alu_core_call_328_res_prov (@clk)
  initial begin
    alu_core_call_328_res_prov = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      alu_core_call_328_res_prov <= '0;
    end else begin
      if (1'b1) alu_core_call_328_res_prov <= rspu_pipeline_call_110_ex_p1;
    end
  end

  // Unified Reflex Block for: alu_core_call_328_res_tag (@clk)
  initial begin
    alu_core_call_328_res_tag = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      alu_core_call_328_res_tag <= '0;
    end else begin
      if (1'b1) alu_core_call_328_res_tag <= rspu_pipeline_call_110_ex_t1;
    end
  end

  // Unified Reflex Block for: core_top_call_41_core_awake (@clk)
  initial begin
    core_top_call_41_core_awake = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      core_top_call_41_core_awake <= '0;
    end else begin
      if (1'b1) core_top_call_41_core_awake <= ((core_top_call_41_wake_timer > 0) | noc_rx_valid);
    end
  end

  // Unified Reflex Block for: core_top_call_41_core_halted (@clk)
  initial begin
    core_top_call_41_core_halted = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      core_top_call_41_core_halted <= '0;
    end else begin
      if (1'b1) core_top_call_41_core_halted <= 1'b0;
      if (core_top_call_41_trap_active_out) core_top_call_41_core_halted <= 1'b1;
    end
  end

  // Unified Reflex Block for: core_top_call_41_current_instr (@clk)
  initial begin
    core_top_call_41_current_instr = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      core_top_call_41_current_instr <= '0;
    end else begin
      if (core_top_call_41_rx_only_out) core_top_call_41_current_instr <= noc_rx_data;
    end
  end

  // Unified Reflex Block for: core_top_call_41_gated_clk (@clk)
  initial begin
    core_top_call_41_gated_clk = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      core_top_call_41_gated_clk <= '0;
    end else begin
      if (1'b1) core_top_call_41_gated_clk <= (clk & core_top_call_41_core_awake);
    end
  end

  // Unified Reflex Block for: core_top_call_41_trap_signal (@clk)
  initial begin
    core_top_call_41_trap_signal = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      core_top_call_41_trap_signal <= '0;
    end else begin
      if (1'b1) core_top_call_41_trap_signal <= (rspu_pipeline_call_110_pcc_fault | rspu_pipeline_call_110_ex_trap);
    end
  end

  // Unified Reflex Block for: core_top_call_41_wake_timer (@clk)
  initial begin
    core_top_call_41_wake_timer = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      core_top_call_41_wake_timer <= '0;
    end else begin
      if (core_top_call_41_rx_only_out) core_top_call_41_wake_timer <= 5;
      if (core_top_call_41_dec_only_out) core_top_call_41_wake_timer <= (core_top_call_41_wake_timer - 1);
    end
  end

  // Unified Reflex Block for: data_out (@clk)
  initial begin
    data_out = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      data_out <= '0;
    end else begin
      if (1'b1) data_out <= rspu_pipeline_call_110_mem_wb_res;
    end
  end

  // Unified Reflex Block for: io_out_0 (@clk)
  initial begin
    io_out_0 = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      io_out_0 <= '0;
    end else begin
      if (rspu_pipeline_call_110_is_store_out_g_out) io_out_0 <= rspu_pipeline_call_110_id_ex_val1;
    end
  end

  // Unified Reflex Block for: noc_tx_data (@clk)
  initial begin
    noc_tx_data = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      noc_tx_data <= '0;
    end else begin
      if (1'b1) noc_tx_data <= 0;
      if (core_top_call_41_trap_active_out) noc_tx_data <= ((9223372036854775808 | 60129542144) | pc_out);
    end
  end

  // Unified Reflex Block for: noc_tx_valid (@clk)
  initial begin
    noc_tx_valid = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      noc_tx_valid <= '0;
    end else begin
      if (1'b1) noc_tx_valid <= 1'b0;
      if (core_top_call_41_trap_active_out) noc_tx_valid <= 1'b1;
    end
  end

  // Unified Reflex Block for: pc_out (@clk)
  initial begin
    pc_out = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      pc_out <= '0;
    end else begin
      if (rspu_pipeline_call_110_fetch_active_out) pc_out <= rspu_pipeline_call_110_pipe_pc;
    end
  end

  // Unified Reflex Block for: pcc_verifier_call_312_is_invalid (@clk)
  initial begin
    pcc_verifier_call_312_is_invalid = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      pcc_verifier_call_312_is_invalid <= '0;
    end else begin
      if (1'b1) pcc_verifier_call_312_is_invalid <= (((!(rspu_pipeline_call_110_cert_i <= 1024)) | (!(rspu_pipeline_call_110_cert_r <= 256))) | (!(rspu_pipeline_call_110_cert_g <= 32)));
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_cert_g (@clk)
  initial begin
    rspu_pipeline_call_110_cert_g = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_cert_g <= '0;
    end else begin
      if (1'b1) rspu_pipeline_call_110_cert_g <= 0;
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_cert_i (@clk)
  initial begin
    rspu_pipeline_call_110_cert_i = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_cert_i <= '0;
    end else begin
      if (1'b1) rspu_pipeline_call_110_cert_i <= 0;
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_cert_r (@clk)
  initial begin
    rspu_pipeline_call_110_cert_r = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_cert_r <= '0;
    end else begin
      if (1'b1) rspu_pipeline_call_110_cert_r <= 0;
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_dec_op (@clk)
  initial begin
    rspu_pipeline_call_110_dec_op = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_dec_op <= '0;
    end else begin
      if (rspu_pipeline_call_110_fetch_active_out) rspu_pipeline_call_110_dec_op <= (rspu_pipeline_call_110_if_id_instr & 255);
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_dec_rd (@clk)
  initial begin
    rspu_pipeline_call_110_dec_rd = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_dec_rd <= '0;
    end else begin
      if (rspu_pipeline_call_110_fetch_active_out) rspu_pipeline_call_110_dec_rd <= ((rspu_pipeline_call_110_if_id_instr >> 16) & 1023);
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_dec_rs1 (@clk)
  initial begin
    rspu_pipeline_call_110_dec_rs1 = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_dec_rs1 <= '0;
    end else begin
      if (rspu_pipeline_call_110_fetch_active_out) rspu_pipeline_call_110_dec_rs1 <= ((rspu_pipeline_call_110_if_id_instr >> 48) & 1023);
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_dec_rs2 (@clk)
  initial begin
    rspu_pipeline_call_110_dec_rs2 = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_dec_rs2 <= '0;
    end else begin
      if (rspu_pipeline_call_110_fetch_active_out) rspu_pipeline_call_110_dec_rs2 <= ((rspu_pipeline_call_110_if_id_instr >> 32) & 1023);
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_ex_d1 (@clk)
  initial begin
    rspu_pipeline_call_110_ex_d1 = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_ex_d1 <= '0;
    end else begin
      if (1'b1) rspu_pipeline_call_110_ex_d1 <= (rspu_pipeline_call_110_id_ex_val1 & 4294967295);
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_ex_d2 (@clk)
  initial begin
    rspu_pipeline_call_110_ex_d2 = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_ex_d2 <= '0;
    end else begin
      if (1'b1) rspu_pipeline_call_110_ex_d2 <= (rspu_pipeline_call_110_id_ex_val2 & 4294967295);
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_ex_mem_op (@clk)
  initial begin
    rspu_pipeline_call_110_ex_mem_op = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_ex_mem_op <= '0;
    end else begin
      if (rspu_pipeline_call_110_fetch_active_out) rspu_pipeline_call_110_ex_mem_op <= rspu_pipeline_call_110_id_ex_op;
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_ex_mem_rd (@clk)
  initial begin
    rspu_pipeline_call_110_ex_mem_rd = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_ex_mem_rd <= '0;
    end else begin
      if (rspu_pipeline_call_110_fetch_active_out) rspu_pipeline_call_110_ex_mem_rd <= rspu_pipeline_call_110_id_ex_rd;
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_ex_mem_res (@clk)
  initial begin
    rspu_pipeline_call_110_ex_mem_res = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_ex_mem_res <= '0;
    end else begin
      if (rspu_pipeline_call_110_fetch_active_out) rspu_pipeline_call_110_ex_mem_res <= rspu_pipeline_call_110_ex_packed;
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_ex_out_d (@clk)
  initial begin
    rspu_pipeline_call_110_ex_out_d = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_ex_out_d <= '0;
    end else begin
      if (1'b1) rspu_pipeline_call_110_ex_out_d <= (alu_core_call_328_res_data & 4294967295);
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_ex_out_p (@clk)
  initial begin
    rspu_pipeline_call_110_ex_out_p = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_ex_out_p <= '0;
    end else begin
      if (1'b1) rspu_pipeline_call_110_ex_out_p <= (alu_core_call_328_res_prov & 15);
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_ex_out_t (@clk)
  initial begin
    rspu_pipeline_call_110_ex_out_t = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_ex_out_t <= '0;
    end else begin
      if (1'b1) rspu_pipeline_call_110_ex_out_t <= (alu_core_call_328_res_tag & 15);
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_ex_p1 (@clk)
  initial begin
    rspu_pipeline_call_110_ex_p1 = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_ex_p1 <= '0;
    end else begin
      if (1'b1) rspu_pipeline_call_110_ex_p1 <= ((rspu_pipeline_call_110_id_ex_val1 >> 36) & 15);
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_ex_p2 (@clk)
  initial begin
    rspu_pipeline_call_110_ex_p2 = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_ex_p2 <= '0;
    end else begin
      if (1'b1) rspu_pipeline_call_110_ex_p2 <= ((rspu_pipeline_call_110_id_ex_val2 >> 36) & 15);
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_ex_packed (@clk)
  initial begin
    rspu_pipeline_call_110_ex_packed = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_ex_packed <= '0;
    end else begin
      if (rspu_pipeline_call_110_is_normal_ex_g_out) rspu_pipeline_call_110_ex_packed <= ((((rspu_pipeline_call_110_ex_out_p & 15) << 36) | ((rspu_pipeline_call_110_ex_out_t & 15) << 32)) | (rspu_pipeline_call_110_ex_out_d & 4294967295));
      if (rspu_pipeline_call_110_is_load_in_g_out) rspu_pipeline_call_110_ex_packed <= (4294967296 | (io_in_0 & 4294967295));
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_ex_t1 (@clk)
  initial begin
    rspu_pipeline_call_110_ex_t1 = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_ex_t1 <= '0;
    end else begin
      if (1'b1) rspu_pipeline_call_110_ex_t1 <= ((rspu_pipeline_call_110_id_ex_val1 >> 32) & 15);
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_ex_t2 (@clk)
  initial begin
    rspu_pipeline_call_110_ex_t2 = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_ex_t2 <= '0;
    end else begin
      if (1'b1) rspu_pipeline_call_110_ex_t2 <= ((rspu_pipeline_call_110_id_ex_val2 >> 32) & 15);
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_ex_trap (@clk)
  initial begin
    rspu_pipeline_call_110_ex_trap = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_ex_trap <= '0;
    end else begin
      if (1'b1) rspu_pipeline_call_110_ex_trap <= alu_core_call_328_is_trap;
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_id_ex_op (@clk)
  initial begin
    rspu_pipeline_call_110_id_ex_op = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_id_ex_op <= '0;
    end else begin
      if (rspu_pipeline_call_110_fetch_active_out) rspu_pipeline_call_110_id_ex_op <= rspu_pipeline_call_110_dec_op;
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_id_ex_pc (@clk)
  initial begin
    rspu_pipeline_call_110_id_ex_pc = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_id_ex_pc <= '0;
    end else begin
      if (rspu_pipeline_call_110_fetch_active_out) rspu_pipeline_call_110_id_ex_pc <= rspu_pipeline_call_110_if_id_pc;
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_id_ex_rd (@clk)
  initial begin
    rspu_pipeline_call_110_id_ex_rd = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_id_ex_rd <= '0;
    end else begin
      if (rspu_pipeline_call_110_fetch_active_out) rspu_pipeline_call_110_id_ex_rd <= rspu_pipeline_call_110_dec_rd;
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_id_ex_rs1 (@clk)
  initial begin
    rspu_pipeline_call_110_id_ex_rs1 = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_id_ex_rs1 <= '0;
    end else begin
      if (rspu_pipeline_call_110_fetch_active_out) rspu_pipeline_call_110_id_ex_rs1 <= rspu_pipeline_call_110_dec_rs1;
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_id_ex_rs2 (@clk)
  initial begin
    rspu_pipeline_call_110_id_ex_rs2 = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_id_ex_rs2 <= '0;
    end else begin
      if (rspu_pipeline_call_110_fetch_active_out) rspu_pipeline_call_110_id_ex_rs2 <= rspu_pipeline_call_110_dec_rs2;
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_id_ex_val1 (@clk)
  initial begin
    rspu_pipeline_call_110_id_ex_val1 = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_id_ex_val1 <= '0;
    end else begin
      if (rspu_pipeline_call_110_fetch_active_out) rspu_pipeline_call_110_id_ex_val1 <= rspu_pipeline_call_110_id_val1;
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_id_ex_val2 (@clk)
  initial begin
    rspu_pipeline_call_110_id_ex_val2 = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_id_ex_val2 <= '0;
    end else begin
      if (rspu_pipeline_call_110_fetch_active_out) rspu_pipeline_call_110_id_ex_val2 <= rspu_pipeline_call_110_id_val2;
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_if_id_instr (@clk)
  initial begin
    rspu_pipeline_call_110_if_id_instr = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_if_id_instr <= '0;
    end else begin
      if (rspu_pipeline_call_110_fetch_active_out) rspu_pipeline_call_110_if_id_instr <= core_top_call_41_current_instr;
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_if_id_pc (@clk)
  initial begin
    rspu_pipeline_call_110_if_id_pc = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_if_id_pc <= '0;
    end else begin
      if (rspu_pipeline_call_110_fetch_active_out) rspu_pipeline_call_110_if_id_pc <= rspu_pipeline_call_110_pipe_pc;
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_is_load (@clk)
  initial begin
    rspu_pipeline_call_110_is_load = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_is_load <= '0;
    end else begin
      if (1'b1) rspu_pipeline_call_110_is_load <= (rspu_pipeline_call_110_ex_mem_op == 6);
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_is_load_in (@clk)
  initial begin
    rspu_pipeline_call_110_is_load_in = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_is_load_in <= '0;
    end else begin
      if (1'b1) rspu_pipeline_call_110_is_load_in <= (rspu_pipeline_call_110_id_ex_op == 0);
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_is_normal_ex (@clk)
  initial begin
    rspu_pipeline_call_110_is_normal_ex = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_is_normal_ex <= '0;
    end else begin
      if (1'b1) rspu_pipeline_call_110_is_normal_ex <= (rspu_pipeline_call_110_id_ex_op != 0);
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_is_not_load (@clk)
  initial begin
    rspu_pipeline_call_110_is_not_load = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_is_not_load <= '0;
    end else begin
      if (1'b1) rspu_pipeline_call_110_is_not_load <= (rspu_pipeline_call_110_ex_mem_op != 6);
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_is_store_out (@clk)
  initial begin
    rspu_pipeline_call_110_is_store_out = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_is_store_out <= '0;
    end else begin
      if (1'b1) rspu_pipeline_call_110_is_store_out <= (rspu_pipeline_call_110_id_ex_op == 1);
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_mem_wb_rd (@clk)
  initial begin
    rspu_pipeline_call_110_mem_wb_rd = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_mem_wb_rd <= '0;
    end else begin
      if (rspu_pipeline_call_110_fetch_active_out) rspu_pipeline_call_110_mem_wb_rd <= rspu_pipeline_call_110_ex_mem_rd;
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_mem_wb_res (@clk)
  initial begin
    rspu_pipeline_call_110_mem_wb_res = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_mem_wb_res <= '0;
    end else begin
      if (rspu_pipeline_call_110_is_load_g_out) rspu_pipeline_call_110_mem_wb_res <= rspu_pipeline_call_110_mem_out;
      if (rspu_pipeline_call_110_is_not_load_g_out) rspu_pipeline_call_110_mem_wb_res <= rspu_pipeline_call_110_ex_mem_res;
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_mem_wb_we (@clk)
  initial begin
    rspu_pipeline_call_110_mem_wb_we = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_mem_wb_we <= '0;
    end else begin
      if (rspu_pipeline_call_110_fetch_active_out) rspu_pipeline_call_110_mem_wb_we <= 1'b1;
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_pcc_fault (@clk)
  initial begin
    rspu_pipeline_call_110_pcc_fault = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_pcc_fault <= '0;
    end else begin
      if (1'b1) rspu_pipeline_call_110_pcc_fault <= pcc_verifier_call_312_is_invalid;
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_pcc_valid (@clk)
  initial begin
    rspu_pipeline_call_110_pcc_valid = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_pcc_valid <= '0;
    end else begin
      if (1'b1) rspu_pipeline_call_110_pcc_valid <= (!pcc_verifier_call_312_is_invalid);
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_pipe_pc (@clk)
  initial begin
    rspu_pipeline_call_110_pipe_pc = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_pipe_pc <= '0;
    end else begin
      if (rspu_pipeline_call_110_fetch_active_out) rspu_pipeline_call_110_pipe_pc <= ((rspu_pipeline_call_110_pipe_pc + 1) & 4294967295);
    end
  end

  // Unified Reflex Block for: rspu_pipeline_call_110_ram_addr (@clk)
  initial begin
    rspu_pipeline_call_110_ram_addr = '0;
  end
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rspu_pipeline_call_110_ram_addr <= '0;
    end else begin
      if (rspu_pipeline_call_110_fetch_active_out) rspu_pipeline_call_110_ram_addr <= (rspu_pipeline_call_110_id_ex_pc & 16383);
    end
  end

  // ── Structural Module Instantiations ──

  regfile reg_regfile_inst_314 (
    .clk(core_top_call_41_gated_clk),
    .rs1(rspu_pipeline_call_110_dec_rs1),
    .rs2(rspu_pipeline_call_110_dec_rs2),
    .rd(rspu_pipeline_call_110_mem_wb_rd),
    .we(rspu_pipeline_call_110_mem_wb_we),
    .din(rspu_pipeline_call_110_mem_wb_res),
    .dout1(rspu_pipeline_call_110_id_val1),
    .dout2(rspu_pipeline_call_110_id_val2)
  );

  // ── Safety Properties (SVA) ──

  // Enforce reset sequence for formal verification
  reg f_past_valid = 0;
  always_ff @(posedge clk) begin
    f_past_valid <= 1;
  end
  always_comb begin
    if (!f_past_valid) assume (!rst_n);
  end

  // source: <unknown>:28
  // property: exception_tx_format
  always @(posedge clk) begin
    if (rst_n) begin
      exception_tx_format: assert((!(noc_tx_valid)) || (((noc_tx_data >> 32) == 2147483662)));
    end
  end

endmodule
