// Auto-generated SVA bind file from MIRR compiler
// Bind target: rspu_top
// Use with: read_verilog -sv <this_file> (formal verification only)

module rspu_top_sva (
  input  logic        clk,
  input  logic        rst_n,
  input  logic        stream_rx_valid,
  input  logic [63:0] stream_rx_data,
  input  logic [63:0] instr_0,
  input  logic [31:0] pc_0,
  input  logic [63:0] core_data_0,
  input  logic        rx_valid_0,
  input  logic [63:0] rx_data_0,
  input  logic        tx_valid_0,
  input  logic [63:0] tx_data_0,
  input  logic [31:0] out_pc_0,
  input  logic [63:0] out_data_0,
  input  logic [63:0] instr_1,
  input  logic [31:0] pc_1,
  input  logic [63:0] core_data_1,
  input  logic        rx_valid_1,
  input  logic [63:0] rx_data_1,
  input  logic        tx_valid_1,
  input  logic [63:0] tx_data_1,
  input  logic [31:0] out_pc_1,
  input  logic [63:0] out_data_1,
  input  logic [63:0] instr_2,
  input  logic [31:0] pc_2,
  input  logic [63:0] core_data_2,
  input  logic        rx_valid_2,
  input  logic [63:0] rx_data_2,
  input  logic        tx_valid_2,
  input  logic [63:0] tx_data_2,
  input  logic [31:0] out_pc_2,
  input  logic [63:0] out_data_2,
  input  logic [63:0] instr_3,
  input  logic [31:0] pc_3,
  input  logic [63:0] core_data_3,
  input  logic        rx_valid_3,
  input  logic [63:0] rx_data_3,
  input  logic        tx_valid_3,
  input  logic [63:0] tx_data_3,
  input  logic [31:0] out_pc_3,
  input  logic [63:0] out_data_3,
  input  logic [63:0] instr_4,
  input  logic [31:0] pc_4,
  input  logic [63:0] core_data_4,
  input  logic        rx_valid_4,
  input  logic [63:0] rx_data_4,
  input  logic        tx_valid_4,
  input  logic [63:0] tx_data_4,
  input  logic [31:0] out_pc_4,
  input  logic [63:0] out_data_4,
  input  logic [63:0] instr_5,
  input  logic [31:0] pc_5,
  input  logic [63:0] core_data_5,
  input  logic        rx_valid_5,
  input  logic [63:0] rx_data_5,
  input  logic        tx_valid_5,
  input  logic [63:0] tx_data_5,
  input  logic [31:0] out_pc_5,
  input  logic [63:0] out_data_5,
  input  logic [63:0] instr_6,
  input  logic [31:0] pc_6,
  input  logic [63:0] core_data_6,
  input  logic        rx_valid_6,
  input  logic [63:0] rx_data_6,
  input  logic        tx_valid_6,
  input  logic [63:0] tx_data_6,
  input  logic [31:0] out_pc_6,
  input  logic [63:0] out_data_6,
  input  logic [63:0] instr_7,
  input  logic [31:0] pc_7,
  input  logic [63:0] core_data_7,
  input  logic        rx_valid_7,
  input  logic [63:0] rx_data_7,
  input  logic        tx_valid_7,
  input  logic [63:0] tx_data_7,
  input  logic [31:0] out_pc_7,
  input  logic [63:0] out_data_7,
  input  logic [63:0] instr_8,
  input  logic [31:0] pc_8,
  input  logic [63:0] core_data_8,
  input  logic        rx_valid_8,
  input  logic [63:0] rx_data_8,
  input  logic        tx_valid_8,
  input  logic [63:0] tx_data_8,
  input  logic [31:0] out_pc_8,
  input  logic [63:0] out_data_8,
  input  logic [63:0] instr_9,
  input  logic [31:0] pc_9,
  input  logic [63:0] core_data_9,
  input  logic        rx_valid_9,
  input  logic [63:0] rx_data_9,
  input  logic        tx_valid_9,
  input  logic [63:0] tx_data_9,
  input  logic [31:0] out_pc_9,
  input  logic [63:0] out_data_9,
  input  logic [63:0] instr_10,
  input  logic [31:0] pc_10,
  input  logic [63:0] core_data_10,
  input  logic        rx_valid_10,
  input  logic [63:0] rx_data_10,
  input  logic        tx_valid_10,
  input  logic [63:0] tx_data_10,
  input  logic [31:0] out_pc_10,
  input  logic [63:0] out_data_10,
  input  logic [63:0] instr_11,
  input  logic [31:0] pc_11,
  input  logic [63:0] core_data_11,
  input  logic        rx_valid_11,
  input  logic [63:0] rx_data_11,
  input  logic        tx_valid_11,
  input  logic [63:0] tx_data_11,
  input  logic [31:0] out_pc_11,
  input  logic [63:0] out_data_11,
  input  logic [63:0] instr_12,
  input  logic [31:0] pc_12,
  input  logic [63:0] core_data_12,
  input  logic        rx_valid_12,
  input  logic [63:0] rx_data_12,
  input  logic        tx_valid_12,
  input  logic [63:0] tx_data_12,
  input  logic [31:0] out_pc_12,
  input  logic [63:0] out_data_12,
  input  logic [63:0] instr_13,
  input  logic [31:0] pc_13,
  input  logic [63:0] core_data_13,
  input  logic        rx_valid_13,
  input  logic [63:0] rx_data_13,
  input  logic        tx_valid_13,
  input  logic [63:0] tx_data_13,
  input  logic [31:0] out_pc_13,
  input  logic [63:0] out_data_13,
  input  logic [63:0] instr_14,
  input  logic [31:0] pc_14,
  input  logic [63:0] core_data_14,
  input  logic        rx_valid_14,
  input  logic [63:0] rx_data_14,
  input  logic        tx_valid_14,
  input  logic [63:0] tx_data_14,
  input  logic [31:0] out_pc_14,
  input  logic [63:0] out_data_14,
  input  logic [63:0] instr_15,
  input  logic [31:0] pc_15,
  input  logic [63:0] core_data_15,
  input  logic        rx_valid_15,
  input  logic [63:0] rx_data_15,
  input  logic        tx_valid_15,
  input  logic [63:0] tx_data_15,
  input  logic [31:0] out_pc_15,
  input  logic [63:0] out_data_15,
  input  logic        global_trap,
  input  logic signed [63:0] robot_angle,
  input  logic signed [63:0] robot_torque,
  input  logic        fabric_noc_router_0_sv0,
  input  logic [63:0] fabric_noc_router_0_sd0,
  input  logic        fabric_noc_router_0_sv1,
  input  logic [63:0] fabric_noc_router_0_sd1,
  input  logic        fabric_noc_router_0_sv2,
  input  logic [63:0] fabric_noc_router_0_sd2,
  input  logic        fabric_noc_router_0_sv3,
  input  logic [63:0] fabric_noc_router_0_sd3,
  input  logic        fabric_noc_router_0_sv4,
  input  logic [63:0] fabric_noc_router_0_sd4,
  input  logic        fabric_noc_router_0_sv5,
  input  logic [63:0] fabric_noc_router_0_sd5,
  input  logic        fabric_noc_router_0_sv6,
  input  logic [63:0] fabric_noc_router_0_sd6,
  input  logic        fabric_noc_router_0_sv7,
  input  logic [63:0] fabric_noc_router_0_sd7,
  input  logic        fabric_noc_router_0_sv8,
  input  logic [63:0] fabric_noc_router_0_sd8,
  input  logic        fabric_noc_router_0_sv9,
  input  logic [63:0] fabric_noc_router_0_sd9,
  input  logic        fabric_noc_router_0_sv10,
  input  logic [63:0] fabric_noc_router_0_sd10,
  input  logic        fabric_noc_router_0_sv11,
  input  logic [63:0] fabric_noc_router_0_sd11,
  input  logic        fabric_noc_router_0_sv12,
  input  logic [63:0] fabric_noc_router_0_sd12,
  input  logic        fabric_noc_router_0_sv13,
  input  logic [63:0] fabric_noc_router_0_sd13,
  input  logic        fabric_noc_router_0_sv14,
  input  logic [63:0] fabric_noc_router_0_sd14,
  input  logic        fabric_noc_router_0_sv15,
  input  logic [63:0] fabric_noc_router_0_sd15,
  input  logic        fabric_noc_router_0_sv16,
  input  logic [63:0] fabric_noc_router_0_sd16,
  input  logic [63:0] fabric_noc_router_0_dest_id,
  input  logic [63:0] fabric_noc_router_0_payload,
  input  logic        core_core_top_1_trap_signal,
  input  logic [63:0] core_core_top_1_current_instr,
  input  logic        core_core_top_1_core_halted,
  input  logic [31:0] pipe_rspu_pipeline_2_pipe_pc,
  input  logic        pipe_rspu_pipeline_2_pcc_valid,
  input  logic        pipe_rspu_pipeline_2_pcc_fault,
  input  logic [15:0] pipe_rspu_pipeline_2_cert_i,
  input  logic [15:0] pipe_rspu_pipeline_2_cert_r,
  input  logic [15:0] pipe_rspu_pipeline_2_cert_g,
  input  logic        pipe_rspu_pipeline_2_cert_h,
  input  logic        pipe_rspu_pipeline_2_cert_v,
  input  logic [15:0] pipe_rspu_pipeline_2_id_rs1,
  input  logic [15:0] pipe_rspu_pipeline_2_id_rs2,
  input  logic [15:0] pipe_rspu_pipeline_2_id_rd,
  input  logic [63:0] pipe_rspu_pipeline_2_id_val1,
  input  logic [63:0] pipe_rspu_pipeline_2_id_val2,
  input  logic        pipe_rspu_pipeline_2_reg_we,
  input  logic [63:0] pipe_rspu_pipeline_2_reg_din,
  input  logic [63:0] pipe_rspu_pipeline_2_ex_d1,
  input  logic [63:0] pipe_rspu_pipeline_2_ex_t1,
  input  logic [63:0] pipe_rspu_pipeline_2_ex_p1,
  input  logic [63:0] pipe_rspu_pipeline_2_ex_d2,
  input  logic [63:0] pipe_rspu_pipeline_2_ex_t2,
  input  logic [63:0] pipe_rspu_pipeline_2_ex_p2,
  input  logic [63:0] pipe_rspu_pipeline_2_ex_out_d,
  input  logic [63:0] pipe_rspu_pipeline_2_ex_out_t,
  input  logic [63:0] pipe_rspu_pipeline_2_ex_out_p,
  input  logic        pipe_rspu_pipeline_2_ex_trap,
  input  logic [15:0] pipe_rspu_pipeline_2_alu_op,
  input  logic [63:0] pipe_rspu_pipeline_2_ex_packed,
  input  logic [63:0] pipe_rspu_pipeline_2_mem_out,
  input  logic [31:0] pipe_rspu_pipeline_2_ram_addr,
  input  logic [63:0] alu_alu_core_4_res_data,
  input  logic [63:0] alu_alu_core_4_res_tag,
  input  logic [63:0] alu_alu_core_4_res_prov,
  input  logic        alu_alu_core_4_is_trap,
  input  logic        alu_alu_core_4_is_add,
  input  logic        alu_alu_core_4_is_sub,
  input  logic        alu_alu_core_4_is_relu_pos,
  input  logic        alu_alu_core_4_is_relu_neg,
  input  logic        alu_alu_core_4_is_tag_gate,
  input  logic [15:0] pcc_pcc_verifier_12_MAX_INSTRUCTIONS,
  input  logic [15:0] pcc_pcc_verifier_12_MAX_REGISTERS,
  input  logic [15:0] pcc_pcc_verifier_12_MAX_GUARDS,
  input  logic        pcc_pcc_verifier_12_bounds_ok,
  input  logic        core_core_top_13_trap_signal,
  input  logic [63:0] core_core_top_13_current_instr,
  input  logic        core_core_top_13_core_halted,
  input  logic [31:0] pipe_rspu_pipeline_14_pipe_pc,
  input  logic        pipe_rspu_pipeline_14_pcc_valid,
  input  logic        pipe_rspu_pipeline_14_pcc_fault,
  input  logic [15:0] pipe_rspu_pipeline_14_cert_i,
  input  logic [15:0] pipe_rspu_pipeline_14_cert_r,
  input  logic [15:0] pipe_rspu_pipeline_14_cert_g,
  input  logic        pipe_rspu_pipeline_14_cert_h,
  input  logic        pipe_rspu_pipeline_14_cert_v,
  input  logic [15:0] pipe_rspu_pipeline_14_id_rs1,
  input  logic [15:0] pipe_rspu_pipeline_14_id_rs2,
  input  logic [15:0] pipe_rspu_pipeline_14_id_rd,
  input  logic [63:0] pipe_rspu_pipeline_14_id_val1,
  input  logic [63:0] pipe_rspu_pipeline_14_id_val2,
  input  logic        pipe_rspu_pipeline_14_reg_we,
  input  logic [63:0] pipe_rspu_pipeline_14_reg_din,
  input  logic [63:0] pipe_rspu_pipeline_14_ex_d1,
  input  logic [63:0] pipe_rspu_pipeline_14_ex_t1,
  input  logic [63:0] pipe_rspu_pipeline_14_ex_p1,
  input  logic [63:0] pipe_rspu_pipeline_14_ex_d2,
  input  logic [63:0] pipe_rspu_pipeline_14_ex_t2,
  input  logic [63:0] pipe_rspu_pipeline_14_ex_p2,
  input  logic [63:0] pipe_rspu_pipeline_14_ex_out_d,
  input  logic [63:0] pipe_rspu_pipeline_14_ex_out_t,
  input  logic [63:0] pipe_rspu_pipeline_14_ex_out_p,
  input  logic        pipe_rspu_pipeline_14_ex_trap,
  input  logic [15:0] pipe_rspu_pipeline_14_alu_op,
  input  logic [63:0] pipe_rspu_pipeline_14_ex_packed,
  input  logic [63:0] pipe_rspu_pipeline_14_mem_out,
  input  logic [31:0] pipe_rspu_pipeline_14_ram_addr,
  input  logic [63:0] alu_alu_core_16_res_data,
  input  logic [63:0] alu_alu_core_16_res_tag,
  input  logic [63:0] alu_alu_core_16_res_prov,
  input  logic        alu_alu_core_16_is_trap,
  input  logic        alu_alu_core_16_is_add,
  input  logic        alu_alu_core_16_is_sub,
  input  logic        alu_alu_core_16_is_relu_pos,
  input  logic        alu_alu_core_16_is_relu_neg,
  input  logic        alu_alu_core_16_is_tag_gate,
  input  logic [15:0] pcc_pcc_verifier_24_MAX_INSTRUCTIONS,
  input  logic [15:0] pcc_pcc_verifier_24_MAX_REGISTERS,
  input  logic [15:0] pcc_pcc_verifier_24_MAX_GUARDS,
  input  logic        pcc_pcc_verifier_24_bounds_ok,
  input  logic        core_core_top_25_trap_signal,
  input  logic [63:0] core_core_top_25_current_instr,
  input  logic        core_core_top_25_core_halted,
  input  logic [31:0] pipe_rspu_pipeline_26_pipe_pc,
  input  logic        pipe_rspu_pipeline_26_pcc_valid,
  input  logic        pipe_rspu_pipeline_26_pcc_fault,
  input  logic [15:0] pipe_rspu_pipeline_26_cert_i,
  input  logic [15:0] pipe_rspu_pipeline_26_cert_r,
  input  logic [15:0] pipe_rspu_pipeline_26_cert_g,
  input  logic        pipe_rspu_pipeline_26_cert_h,
  input  logic        pipe_rspu_pipeline_26_cert_v,
  input  logic [15:0] pipe_rspu_pipeline_26_id_rs1,
  input  logic [15:0] pipe_rspu_pipeline_26_id_rs2,
  input  logic [15:0] pipe_rspu_pipeline_26_id_rd,
  input  logic [63:0] pipe_rspu_pipeline_26_id_val1,
  input  logic [63:0] pipe_rspu_pipeline_26_id_val2,
  input  logic        pipe_rspu_pipeline_26_reg_we,
  input  logic [63:0] pipe_rspu_pipeline_26_reg_din,
  input  logic [63:0] pipe_rspu_pipeline_26_ex_d1,
  input  logic [63:0] pipe_rspu_pipeline_26_ex_t1,
  input  logic [63:0] pipe_rspu_pipeline_26_ex_p1,
  input  logic [63:0] pipe_rspu_pipeline_26_ex_d2,
  input  logic [63:0] pipe_rspu_pipeline_26_ex_t2,
  input  logic [63:0] pipe_rspu_pipeline_26_ex_p2,
  input  logic [63:0] pipe_rspu_pipeline_26_ex_out_d,
  input  logic [63:0] pipe_rspu_pipeline_26_ex_out_t,
  input  logic [63:0] pipe_rspu_pipeline_26_ex_out_p,
  input  logic        pipe_rspu_pipeline_26_ex_trap,
  input  logic [15:0] pipe_rspu_pipeline_26_alu_op,
  input  logic [63:0] pipe_rspu_pipeline_26_ex_packed,
  input  logic [63:0] pipe_rspu_pipeline_26_mem_out,
  input  logic [31:0] pipe_rspu_pipeline_26_ram_addr,
  input  logic [63:0] alu_alu_core_28_res_data,
  input  logic [63:0] alu_alu_core_28_res_tag,
  input  logic [63:0] alu_alu_core_28_res_prov,
  input  logic        alu_alu_core_28_is_trap,
  input  logic        alu_alu_core_28_is_add,
  input  logic        alu_alu_core_28_is_sub,
  input  logic        alu_alu_core_28_is_relu_pos,
  input  logic        alu_alu_core_28_is_relu_neg,
  input  logic        alu_alu_core_28_is_tag_gate,
  input  logic [15:0] pcc_pcc_verifier_36_MAX_INSTRUCTIONS,
  input  logic [15:0] pcc_pcc_verifier_36_MAX_REGISTERS,
  input  logic [15:0] pcc_pcc_verifier_36_MAX_GUARDS,
  input  logic        pcc_pcc_verifier_36_bounds_ok,
  input  logic        core_core_top_37_trap_signal,
  input  logic [63:0] core_core_top_37_current_instr,
  input  logic        core_core_top_37_core_halted,
  input  logic [31:0] pipe_rspu_pipeline_38_pipe_pc,
  input  logic        pipe_rspu_pipeline_38_pcc_valid,
  input  logic        pipe_rspu_pipeline_38_pcc_fault,
  input  logic [15:0] pipe_rspu_pipeline_38_cert_i,
  input  logic [15:0] pipe_rspu_pipeline_38_cert_r,
  input  logic [15:0] pipe_rspu_pipeline_38_cert_g,
  input  logic        pipe_rspu_pipeline_38_cert_h,
  input  logic        pipe_rspu_pipeline_38_cert_v,
  input  logic [15:0] pipe_rspu_pipeline_38_id_rs1,
  input  logic [15:0] pipe_rspu_pipeline_38_id_rs2,
  input  logic [15:0] pipe_rspu_pipeline_38_id_rd,
  input  logic [63:0] pipe_rspu_pipeline_38_id_val1,
  input  logic [63:0] pipe_rspu_pipeline_38_id_val2,
  input  logic        pipe_rspu_pipeline_38_reg_we,
  input  logic [63:0] pipe_rspu_pipeline_38_reg_din,
  input  logic [63:0] pipe_rspu_pipeline_38_ex_d1,
  input  logic [63:0] pipe_rspu_pipeline_38_ex_t1,
  input  logic [63:0] pipe_rspu_pipeline_38_ex_p1,
  input  logic [63:0] pipe_rspu_pipeline_38_ex_d2,
  input  logic [63:0] pipe_rspu_pipeline_38_ex_t2,
  input  logic [63:0] pipe_rspu_pipeline_38_ex_p2,
  input  logic [63:0] pipe_rspu_pipeline_38_ex_out_d,
  input  logic [63:0] pipe_rspu_pipeline_38_ex_out_t,
  input  logic [63:0] pipe_rspu_pipeline_38_ex_out_p,
  input  logic        pipe_rspu_pipeline_38_ex_trap,
  input  logic [15:0] pipe_rspu_pipeline_38_alu_op,
  input  logic [63:0] pipe_rspu_pipeline_38_ex_packed,
  input  logic [63:0] pipe_rspu_pipeline_38_mem_out,
  input  logic [31:0] pipe_rspu_pipeline_38_ram_addr,
  input  logic [63:0] alu_alu_core_40_res_data,
  input  logic [63:0] alu_alu_core_40_res_tag,
  input  logic [63:0] alu_alu_core_40_res_prov,
  input  logic        alu_alu_core_40_is_trap,
  input  logic        alu_alu_core_40_is_add,
  input  logic        alu_alu_core_40_is_sub,
  input  logic        alu_alu_core_40_is_relu_pos,
  input  logic        alu_alu_core_40_is_relu_neg,
  input  logic        alu_alu_core_40_is_tag_gate,
  input  logic [15:0] pcc_pcc_verifier_48_MAX_INSTRUCTIONS,
  input  logic [15:0] pcc_pcc_verifier_48_MAX_REGISTERS,
  input  logic [15:0] pcc_pcc_verifier_48_MAX_GUARDS,
  input  logic        pcc_pcc_verifier_48_bounds_ok,
  input  logic        core_core_top_49_trap_signal,
  input  logic [63:0] core_core_top_49_current_instr,
  input  logic        core_core_top_49_core_halted,
  input  logic [31:0] pipe_rspu_pipeline_50_pipe_pc,
  input  logic        pipe_rspu_pipeline_50_pcc_valid,
  input  logic        pipe_rspu_pipeline_50_pcc_fault,
  input  logic [15:0] pipe_rspu_pipeline_50_cert_i,
  input  logic [15:0] pipe_rspu_pipeline_50_cert_r,
  input  logic [15:0] pipe_rspu_pipeline_50_cert_g,
  input  logic        pipe_rspu_pipeline_50_cert_h,
  input  logic        pipe_rspu_pipeline_50_cert_v,
  input  logic [15:0] pipe_rspu_pipeline_50_id_rs1,
  input  logic [15:0] pipe_rspu_pipeline_50_id_rs2,
  input  logic [15:0] pipe_rspu_pipeline_50_id_rd,
  input  logic [63:0] pipe_rspu_pipeline_50_id_val1,
  input  logic [63:0] pipe_rspu_pipeline_50_id_val2,
  input  logic        pipe_rspu_pipeline_50_reg_we,
  input  logic [63:0] pipe_rspu_pipeline_50_reg_din,
  input  logic [63:0] pipe_rspu_pipeline_50_ex_d1,
  input  logic [63:0] pipe_rspu_pipeline_50_ex_t1,
  input  logic [63:0] pipe_rspu_pipeline_50_ex_p1,
  input  logic [63:0] pipe_rspu_pipeline_50_ex_d2,
  input  logic [63:0] pipe_rspu_pipeline_50_ex_t2,
  input  logic [63:0] pipe_rspu_pipeline_50_ex_p2,
  input  logic [63:0] pipe_rspu_pipeline_50_ex_out_d,
  input  logic [63:0] pipe_rspu_pipeline_50_ex_out_t,
  input  logic [63:0] pipe_rspu_pipeline_50_ex_out_p,
  input  logic        pipe_rspu_pipeline_50_ex_trap,
  input  logic [15:0] pipe_rspu_pipeline_50_alu_op,
  input  logic [63:0] pipe_rspu_pipeline_50_ex_packed,
  input  logic [63:0] pipe_rspu_pipeline_50_mem_out,
  input  logic [31:0] pipe_rspu_pipeline_50_ram_addr,
  input  logic [63:0] alu_alu_core_52_res_data,
  input  logic [63:0] alu_alu_core_52_res_tag,
  input  logic [63:0] alu_alu_core_52_res_prov,
  input  logic        alu_alu_core_52_is_trap,
  input  logic        alu_alu_core_52_is_add,
  input  logic        alu_alu_core_52_is_sub,
  input  logic        alu_alu_core_52_is_relu_pos,
  input  logic        alu_alu_core_52_is_relu_neg,
  input  logic        alu_alu_core_52_is_tag_gate,
  input  logic [15:0] pcc_pcc_verifier_60_MAX_INSTRUCTIONS,
  input  logic [15:0] pcc_pcc_verifier_60_MAX_REGISTERS,
  input  logic [15:0] pcc_pcc_verifier_60_MAX_GUARDS,
  input  logic        pcc_pcc_verifier_60_bounds_ok,
  input  logic        core_core_top_61_trap_signal,
  input  logic [63:0] core_core_top_61_current_instr,
  input  logic        core_core_top_61_core_halted,
  input  logic [31:0] pipe_rspu_pipeline_62_pipe_pc,
  input  logic        pipe_rspu_pipeline_62_pcc_valid,
  input  logic        pipe_rspu_pipeline_62_pcc_fault,
  input  logic [15:0] pipe_rspu_pipeline_62_cert_i,
  input  logic [15:0] pipe_rspu_pipeline_62_cert_r,
  input  logic [15:0] pipe_rspu_pipeline_62_cert_g,
  input  logic        pipe_rspu_pipeline_62_cert_h,
  input  logic        pipe_rspu_pipeline_62_cert_v,
  input  logic [15:0] pipe_rspu_pipeline_62_id_rs1,
  input  logic [15:0] pipe_rspu_pipeline_62_id_rs2,
  input  logic [15:0] pipe_rspu_pipeline_62_id_rd,
  input  logic [63:0] pipe_rspu_pipeline_62_id_val1,
  input  logic [63:0] pipe_rspu_pipeline_62_id_val2,
  input  logic        pipe_rspu_pipeline_62_reg_we,
  input  logic [63:0] pipe_rspu_pipeline_62_reg_din,
  input  logic [63:0] pipe_rspu_pipeline_62_ex_d1,
  input  logic [63:0] pipe_rspu_pipeline_62_ex_t1,
  input  logic [63:0] pipe_rspu_pipeline_62_ex_p1,
  input  logic [63:0] pipe_rspu_pipeline_62_ex_d2,
  input  logic [63:0] pipe_rspu_pipeline_62_ex_t2,
  input  logic [63:0] pipe_rspu_pipeline_62_ex_p2,
  input  logic [63:0] pipe_rspu_pipeline_62_ex_out_d,
  input  logic [63:0] pipe_rspu_pipeline_62_ex_out_t,
  input  logic [63:0] pipe_rspu_pipeline_62_ex_out_p,
  input  logic        pipe_rspu_pipeline_62_ex_trap,
  input  logic [15:0] pipe_rspu_pipeline_62_alu_op,
  input  logic [63:0] pipe_rspu_pipeline_62_ex_packed,
  input  logic [63:0] pipe_rspu_pipeline_62_mem_out,
  input  logic [31:0] pipe_rspu_pipeline_62_ram_addr,
  input  logic [63:0] alu_alu_core_64_res_data,
  input  logic [63:0] alu_alu_core_64_res_tag,
  input  logic [63:0] alu_alu_core_64_res_prov,
  input  logic        alu_alu_core_64_is_trap,
  input  logic        alu_alu_core_64_is_add,
  input  logic        alu_alu_core_64_is_sub,
  input  logic        alu_alu_core_64_is_relu_pos,
  input  logic        alu_alu_core_64_is_relu_neg,
  input  logic        alu_alu_core_64_is_tag_gate,
  input  logic [15:0] pcc_pcc_verifier_72_MAX_INSTRUCTIONS,
  input  logic [15:0] pcc_pcc_verifier_72_MAX_REGISTERS,
  input  logic [15:0] pcc_pcc_verifier_72_MAX_GUARDS,
  input  logic        pcc_pcc_verifier_72_bounds_ok,
  input  logic        core_core_top_73_trap_signal,
  input  logic [63:0] core_core_top_73_current_instr,
  input  logic        core_core_top_73_core_halted,
  input  logic [31:0] pipe_rspu_pipeline_74_pipe_pc,
  input  logic        pipe_rspu_pipeline_74_pcc_valid,
  input  logic        pipe_rspu_pipeline_74_pcc_fault,
  input  logic [15:0] pipe_rspu_pipeline_74_cert_i,
  input  logic [15:0] pipe_rspu_pipeline_74_cert_r,
  input  logic [15:0] pipe_rspu_pipeline_74_cert_g,
  input  logic        pipe_rspu_pipeline_74_cert_h,
  input  logic        pipe_rspu_pipeline_74_cert_v,
  input  logic [15:0] pipe_rspu_pipeline_74_id_rs1,
  input  logic [15:0] pipe_rspu_pipeline_74_id_rs2,
  input  logic [15:0] pipe_rspu_pipeline_74_id_rd,
  input  logic [63:0] pipe_rspu_pipeline_74_id_val1,
  input  logic [63:0] pipe_rspu_pipeline_74_id_val2,
  input  logic        pipe_rspu_pipeline_74_reg_we,
  input  logic [63:0] pipe_rspu_pipeline_74_reg_din,
  input  logic [63:0] pipe_rspu_pipeline_74_ex_d1,
  input  logic [63:0] pipe_rspu_pipeline_74_ex_t1,
  input  logic [63:0] pipe_rspu_pipeline_74_ex_p1,
  input  logic [63:0] pipe_rspu_pipeline_74_ex_d2,
  input  logic [63:0] pipe_rspu_pipeline_74_ex_t2,
  input  logic [63:0] pipe_rspu_pipeline_74_ex_p2,
  input  logic [63:0] pipe_rspu_pipeline_74_ex_out_d,
  input  logic [63:0] pipe_rspu_pipeline_74_ex_out_t,
  input  logic [63:0] pipe_rspu_pipeline_74_ex_out_p,
  input  logic        pipe_rspu_pipeline_74_ex_trap,
  input  logic [15:0] pipe_rspu_pipeline_74_alu_op,
  input  logic [63:0] pipe_rspu_pipeline_74_ex_packed,
  input  logic [63:0] pipe_rspu_pipeline_74_mem_out,
  input  logic [31:0] pipe_rspu_pipeline_74_ram_addr,
  input  logic [63:0] alu_alu_core_76_res_data,
  input  logic [63:0] alu_alu_core_76_res_tag,
  input  logic [63:0] alu_alu_core_76_res_prov,
  input  logic        alu_alu_core_76_is_trap,
  input  logic        alu_alu_core_76_is_add,
  input  logic        alu_alu_core_76_is_sub,
  input  logic        alu_alu_core_76_is_relu_pos,
  input  logic        alu_alu_core_76_is_relu_neg,
  input  logic        alu_alu_core_76_is_tag_gate,
  input  logic [15:0] pcc_pcc_verifier_84_MAX_INSTRUCTIONS,
  input  logic [15:0] pcc_pcc_verifier_84_MAX_REGISTERS,
  input  logic [15:0] pcc_pcc_verifier_84_MAX_GUARDS,
  input  logic        pcc_pcc_verifier_84_bounds_ok,
  input  logic        core_core_top_85_trap_signal,
  input  logic [63:0] core_core_top_85_current_instr,
  input  logic        core_core_top_85_core_halted,
  input  logic [31:0] pipe_rspu_pipeline_86_pipe_pc,
  input  logic        pipe_rspu_pipeline_86_pcc_valid,
  input  logic        pipe_rspu_pipeline_86_pcc_fault,
  input  logic [15:0] pipe_rspu_pipeline_86_cert_i,
  input  logic [15:0] pipe_rspu_pipeline_86_cert_r,
  input  logic [15:0] pipe_rspu_pipeline_86_cert_g,
  input  logic        pipe_rspu_pipeline_86_cert_h,
  input  logic        pipe_rspu_pipeline_86_cert_v,
  input  logic [15:0] pipe_rspu_pipeline_86_id_rs1,
  input  logic [15:0] pipe_rspu_pipeline_86_id_rs2,
  input  logic [15:0] pipe_rspu_pipeline_86_id_rd,
  input  logic [63:0] pipe_rspu_pipeline_86_id_val1,
  input  logic [63:0] pipe_rspu_pipeline_86_id_val2,
  input  logic        pipe_rspu_pipeline_86_reg_we,
  input  logic [63:0] pipe_rspu_pipeline_86_reg_din,
  input  logic [63:0] pipe_rspu_pipeline_86_ex_d1,
  input  logic [63:0] pipe_rspu_pipeline_86_ex_t1,
  input  logic [63:0] pipe_rspu_pipeline_86_ex_p1,
  input  logic [63:0] pipe_rspu_pipeline_86_ex_d2,
  input  logic [63:0] pipe_rspu_pipeline_86_ex_t2,
  input  logic [63:0] pipe_rspu_pipeline_86_ex_p2,
  input  logic [63:0] pipe_rspu_pipeline_86_ex_out_d,
  input  logic [63:0] pipe_rspu_pipeline_86_ex_out_t,
  input  logic [63:0] pipe_rspu_pipeline_86_ex_out_p,
  input  logic        pipe_rspu_pipeline_86_ex_trap,
  input  logic [15:0] pipe_rspu_pipeline_86_alu_op,
  input  logic [63:0] pipe_rspu_pipeline_86_ex_packed,
  input  logic [63:0] pipe_rspu_pipeline_86_mem_out,
  input  logic [31:0] pipe_rspu_pipeline_86_ram_addr,
  input  logic [63:0] alu_alu_core_88_res_data,
  input  logic [63:0] alu_alu_core_88_res_tag,
  input  logic [63:0] alu_alu_core_88_res_prov,
  input  logic        alu_alu_core_88_is_trap,
  input  logic        alu_alu_core_88_is_add,
  input  logic        alu_alu_core_88_is_sub,
  input  logic        alu_alu_core_88_is_relu_pos,
  input  logic        alu_alu_core_88_is_relu_neg,
  input  logic        alu_alu_core_88_is_tag_gate,
  input  logic [15:0] pcc_pcc_verifier_96_MAX_INSTRUCTIONS,
  input  logic [15:0] pcc_pcc_verifier_96_MAX_REGISTERS,
  input  logic [15:0] pcc_pcc_verifier_96_MAX_GUARDS,
  input  logic        pcc_pcc_verifier_96_bounds_ok,
  input  logic        core_core_top_97_trap_signal,
  input  logic [63:0] core_core_top_97_current_instr,
  input  logic        core_core_top_97_core_halted,
  input  logic [31:0] pipe_rspu_pipeline_98_pipe_pc,
  input  logic        pipe_rspu_pipeline_98_pcc_valid,
  input  logic        pipe_rspu_pipeline_98_pcc_fault,
  input  logic [15:0] pipe_rspu_pipeline_98_cert_i,
  input  logic [15:0] pipe_rspu_pipeline_98_cert_r,
  input  logic [15:0] pipe_rspu_pipeline_98_cert_g,
  input  logic        pipe_rspu_pipeline_98_cert_h,
  input  logic        pipe_rspu_pipeline_98_cert_v,
  input  logic [15:0] pipe_rspu_pipeline_98_id_rs1,
  input  logic [15:0] pipe_rspu_pipeline_98_id_rs2,
  input  logic [15:0] pipe_rspu_pipeline_98_id_rd,
  input  logic [63:0] pipe_rspu_pipeline_98_id_val1,
  input  logic [63:0] pipe_rspu_pipeline_98_id_val2,
  input  logic        pipe_rspu_pipeline_98_reg_we,
  input  logic [63:0] pipe_rspu_pipeline_98_reg_din,
  input  logic [63:0] pipe_rspu_pipeline_98_ex_d1,
  input  logic [63:0] pipe_rspu_pipeline_98_ex_t1,
  input  logic [63:0] pipe_rspu_pipeline_98_ex_p1,
  input  logic [63:0] pipe_rspu_pipeline_98_ex_d2,
  input  logic [63:0] pipe_rspu_pipeline_98_ex_t2,
  input  logic [63:0] pipe_rspu_pipeline_98_ex_p2,
  input  logic [63:0] pipe_rspu_pipeline_98_ex_out_d,
  input  logic [63:0] pipe_rspu_pipeline_98_ex_out_t,
  input  logic [63:0] pipe_rspu_pipeline_98_ex_out_p,
  input  logic        pipe_rspu_pipeline_98_ex_trap,
  input  logic [15:0] pipe_rspu_pipeline_98_alu_op,
  input  logic [63:0] pipe_rspu_pipeline_98_ex_packed,
  input  logic [63:0] pipe_rspu_pipeline_98_mem_out,
  input  logic [31:0] pipe_rspu_pipeline_98_ram_addr,
  input  logic [63:0] alu_alu_core_100_res_data,
  input  logic [63:0] alu_alu_core_100_res_tag,
  input  logic [63:0] alu_alu_core_100_res_prov,
  input  logic        alu_alu_core_100_is_trap,
  input  logic        alu_alu_core_100_is_add,
  input  logic        alu_alu_core_100_is_sub,
  input  logic        alu_alu_core_100_is_relu_pos,
  input  logic        alu_alu_core_100_is_relu_neg,
  input  logic        alu_alu_core_100_is_tag_gate,
  input  logic [15:0] pcc_pcc_verifier_108_MAX_INSTRUCTIONS,
  input  logic [15:0] pcc_pcc_verifier_108_MAX_REGISTERS,
  input  logic [15:0] pcc_pcc_verifier_108_MAX_GUARDS,
  input  logic        pcc_pcc_verifier_108_bounds_ok,
  input  logic        core_core_top_109_trap_signal,
  input  logic [63:0] core_core_top_109_current_instr,
  input  logic        core_core_top_109_core_halted,
  input  logic [31:0] pipe_rspu_pipeline_110_pipe_pc,
  input  logic        pipe_rspu_pipeline_110_pcc_valid,
  input  logic        pipe_rspu_pipeline_110_pcc_fault,
  input  logic [15:0] pipe_rspu_pipeline_110_cert_i,
  input  logic [15:0] pipe_rspu_pipeline_110_cert_r,
  input  logic [15:0] pipe_rspu_pipeline_110_cert_g,
  input  logic        pipe_rspu_pipeline_110_cert_h,
  input  logic        pipe_rspu_pipeline_110_cert_v,
  input  logic [15:0] pipe_rspu_pipeline_110_id_rs1,
  input  logic [15:0] pipe_rspu_pipeline_110_id_rs2,
  input  logic [15:0] pipe_rspu_pipeline_110_id_rd,
  input  logic [63:0] pipe_rspu_pipeline_110_id_val1,
  input  logic [63:0] pipe_rspu_pipeline_110_id_val2,
  input  logic        pipe_rspu_pipeline_110_reg_we,
  input  logic [63:0] pipe_rspu_pipeline_110_reg_din,
  input  logic [63:0] pipe_rspu_pipeline_110_ex_d1,
  input  logic [63:0] pipe_rspu_pipeline_110_ex_t1,
  input  logic [63:0] pipe_rspu_pipeline_110_ex_p1,
  input  logic [63:0] pipe_rspu_pipeline_110_ex_d2,
  input  logic [63:0] pipe_rspu_pipeline_110_ex_t2,
  input  logic [63:0] pipe_rspu_pipeline_110_ex_p2,
  input  logic [63:0] pipe_rspu_pipeline_110_ex_out_d,
  input  logic [63:0] pipe_rspu_pipeline_110_ex_out_t,
  input  logic [63:0] pipe_rspu_pipeline_110_ex_out_p,
  input  logic        pipe_rspu_pipeline_110_ex_trap,
  input  logic [15:0] pipe_rspu_pipeline_110_alu_op,
  input  logic [63:0] pipe_rspu_pipeline_110_ex_packed,
  input  logic [63:0] pipe_rspu_pipeline_110_mem_out,
  input  logic [31:0] pipe_rspu_pipeline_110_ram_addr,
  input  logic [63:0] alu_alu_core_112_res_data,
  input  logic [63:0] alu_alu_core_112_res_tag,
  input  logic [63:0] alu_alu_core_112_res_prov,
  input  logic        alu_alu_core_112_is_trap,
  input  logic        alu_alu_core_112_is_add,
  input  logic        alu_alu_core_112_is_sub,
  input  logic        alu_alu_core_112_is_relu_pos,
  input  logic        alu_alu_core_112_is_relu_neg,
  input  logic        alu_alu_core_112_is_tag_gate,
  input  logic [15:0] pcc_pcc_verifier_120_MAX_INSTRUCTIONS,
  input  logic [15:0] pcc_pcc_verifier_120_MAX_REGISTERS,
  input  logic [15:0] pcc_pcc_verifier_120_MAX_GUARDS,
  input  logic        pcc_pcc_verifier_120_bounds_ok,
  input  logic        core_core_top_121_trap_signal,
  input  logic [63:0] core_core_top_121_current_instr,
  input  logic        core_core_top_121_core_halted,
  input  logic [31:0] pipe_rspu_pipeline_122_pipe_pc,
  input  logic        pipe_rspu_pipeline_122_pcc_valid,
  input  logic        pipe_rspu_pipeline_122_pcc_fault,
  input  logic [15:0] pipe_rspu_pipeline_122_cert_i,
  input  logic [15:0] pipe_rspu_pipeline_122_cert_r,
  input  logic [15:0] pipe_rspu_pipeline_122_cert_g,
  input  logic        pipe_rspu_pipeline_122_cert_h,
  input  logic        pipe_rspu_pipeline_122_cert_v,
  input  logic [15:0] pipe_rspu_pipeline_122_id_rs1,
  input  logic [15:0] pipe_rspu_pipeline_122_id_rs2,
  input  logic [15:0] pipe_rspu_pipeline_122_id_rd,
  input  logic [63:0] pipe_rspu_pipeline_122_id_val1,
  input  logic [63:0] pipe_rspu_pipeline_122_id_val2,
  input  logic        pipe_rspu_pipeline_122_reg_we,
  input  logic [63:0] pipe_rspu_pipeline_122_reg_din,
  input  logic [63:0] pipe_rspu_pipeline_122_ex_d1,
  input  logic [63:0] pipe_rspu_pipeline_122_ex_t1,
  input  logic [63:0] pipe_rspu_pipeline_122_ex_p1,
  input  logic [63:0] pipe_rspu_pipeline_122_ex_d2,
  input  logic [63:0] pipe_rspu_pipeline_122_ex_t2,
  input  logic [63:0] pipe_rspu_pipeline_122_ex_p2,
  input  logic [63:0] pipe_rspu_pipeline_122_ex_out_d,
  input  logic [63:0] pipe_rspu_pipeline_122_ex_out_t,
  input  logic [63:0] pipe_rspu_pipeline_122_ex_out_p,
  input  logic        pipe_rspu_pipeline_122_ex_trap,
  input  logic [15:0] pipe_rspu_pipeline_122_alu_op,
  input  logic [63:0] pipe_rspu_pipeline_122_ex_packed,
  input  logic [63:0] pipe_rspu_pipeline_122_mem_out,
  input  logic [31:0] pipe_rspu_pipeline_122_ram_addr,
  input  logic [63:0] alu_alu_core_124_res_data,
  input  logic [63:0] alu_alu_core_124_res_tag,
  input  logic [63:0] alu_alu_core_124_res_prov,
  input  logic        alu_alu_core_124_is_trap,
  input  logic        alu_alu_core_124_is_add,
  input  logic        alu_alu_core_124_is_sub,
  input  logic        alu_alu_core_124_is_relu_pos,
  input  logic        alu_alu_core_124_is_relu_neg,
  input  logic        alu_alu_core_124_is_tag_gate,
  input  logic [15:0] pcc_pcc_verifier_132_MAX_INSTRUCTIONS,
  input  logic [15:0] pcc_pcc_verifier_132_MAX_REGISTERS,
  input  logic [15:0] pcc_pcc_verifier_132_MAX_GUARDS,
  input  logic        pcc_pcc_verifier_132_bounds_ok,
  input  logic        core_core_top_133_trap_signal,
  input  logic [63:0] core_core_top_133_current_instr,
  input  logic        core_core_top_133_core_halted,
  input  logic [31:0] pipe_rspu_pipeline_134_pipe_pc,
  input  logic        pipe_rspu_pipeline_134_pcc_valid,
  input  logic        pipe_rspu_pipeline_134_pcc_fault,
  input  logic [15:0] pipe_rspu_pipeline_134_cert_i,
  input  logic [15:0] pipe_rspu_pipeline_134_cert_r,
  input  logic [15:0] pipe_rspu_pipeline_134_cert_g,
  input  logic        pipe_rspu_pipeline_134_cert_h,
  input  logic        pipe_rspu_pipeline_134_cert_v,
  input  logic [15:0] pipe_rspu_pipeline_134_id_rs1,
  input  logic [15:0] pipe_rspu_pipeline_134_id_rs2,
  input  logic [15:0] pipe_rspu_pipeline_134_id_rd,
  input  logic [63:0] pipe_rspu_pipeline_134_id_val1,
  input  logic [63:0] pipe_rspu_pipeline_134_id_val2,
  input  logic        pipe_rspu_pipeline_134_reg_we,
  input  logic [63:0] pipe_rspu_pipeline_134_reg_din,
  input  logic [63:0] pipe_rspu_pipeline_134_ex_d1,
  input  logic [63:0] pipe_rspu_pipeline_134_ex_t1,
  input  logic [63:0] pipe_rspu_pipeline_134_ex_p1,
  input  logic [63:0] pipe_rspu_pipeline_134_ex_d2,
  input  logic [63:0] pipe_rspu_pipeline_134_ex_t2,
  input  logic [63:0] pipe_rspu_pipeline_134_ex_p2,
  input  logic [63:0] pipe_rspu_pipeline_134_ex_out_d,
  input  logic [63:0] pipe_rspu_pipeline_134_ex_out_t,
  input  logic [63:0] pipe_rspu_pipeline_134_ex_out_p,
  input  logic        pipe_rspu_pipeline_134_ex_trap,
  input  logic [15:0] pipe_rspu_pipeline_134_alu_op,
  input  logic [63:0] pipe_rspu_pipeline_134_ex_packed,
  input  logic [63:0] pipe_rspu_pipeline_134_mem_out,
  input  logic [31:0] pipe_rspu_pipeline_134_ram_addr,
  input  logic [63:0] alu_alu_core_136_res_data,
  input  logic [63:0] alu_alu_core_136_res_tag,
  input  logic [63:0] alu_alu_core_136_res_prov,
  input  logic        alu_alu_core_136_is_trap,
  input  logic        alu_alu_core_136_is_add,
  input  logic        alu_alu_core_136_is_sub,
  input  logic        alu_alu_core_136_is_relu_pos,
  input  logic        alu_alu_core_136_is_relu_neg,
  input  logic        alu_alu_core_136_is_tag_gate,
  input  logic [15:0] pcc_pcc_verifier_144_MAX_INSTRUCTIONS,
  input  logic [15:0] pcc_pcc_verifier_144_MAX_REGISTERS,
  input  logic [15:0] pcc_pcc_verifier_144_MAX_GUARDS,
  input  logic        pcc_pcc_verifier_144_bounds_ok,
  input  logic        core_core_top_145_trap_signal,
  input  logic [63:0] core_core_top_145_current_instr,
  input  logic        core_core_top_145_core_halted,
  input  logic [31:0] pipe_rspu_pipeline_146_pipe_pc,
  input  logic        pipe_rspu_pipeline_146_pcc_valid,
  input  logic        pipe_rspu_pipeline_146_pcc_fault,
  input  logic [15:0] pipe_rspu_pipeline_146_cert_i,
  input  logic [15:0] pipe_rspu_pipeline_146_cert_r,
  input  logic [15:0] pipe_rspu_pipeline_146_cert_g,
  input  logic        pipe_rspu_pipeline_146_cert_h,
  input  logic        pipe_rspu_pipeline_146_cert_v,
  input  logic [15:0] pipe_rspu_pipeline_146_id_rs1,
  input  logic [15:0] pipe_rspu_pipeline_146_id_rs2,
  input  logic [15:0] pipe_rspu_pipeline_146_id_rd,
  input  logic [63:0] pipe_rspu_pipeline_146_id_val1,
  input  logic [63:0] pipe_rspu_pipeline_146_id_val2,
  input  logic        pipe_rspu_pipeline_146_reg_we,
  input  logic [63:0] pipe_rspu_pipeline_146_reg_din,
  input  logic [63:0] pipe_rspu_pipeline_146_ex_d1,
  input  logic [63:0] pipe_rspu_pipeline_146_ex_t1,
  input  logic [63:0] pipe_rspu_pipeline_146_ex_p1,
  input  logic [63:0] pipe_rspu_pipeline_146_ex_d2,
  input  logic [63:0] pipe_rspu_pipeline_146_ex_t2,
  input  logic [63:0] pipe_rspu_pipeline_146_ex_p2,
  input  logic [63:0] pipe_rspu_pipeline_146_ex_out_d,
  input  logic [63:0] pipe_rspu_pipeline_146_ex_out_t,
  input  logic [63:0] pipe_rspu_pipeline_146_ex_out_p,
  input  logic        pipe_rspu_pipeline_146_ex_trap,
  input  logic [15:0] pipe_rspu_pipeline_146_alu_op,
  input  logic [63:0] pipe_rspu_pipeline_146_ex_packed,
  input  logic [63:0] pipe_rspu_pipeline_146_mem_out,
  input  logic [31:0] pipe_rspu_pipeline_146_ram_addr,
  input  logic [63:0] alu_alu_core_148_res_data,
  input  logic [63:0] alu_alu_core_148_res_tag,
  input  logic [63:0] alu_alu_core_148_res_prov,
  input  logic        alu_alu_core_148_is_trap,
  input  logic        alu_alu_core_148_is_add,
  input  logic        alu_alu_core_148_is_sub,
  input  logic        alu_alu_core_148_is_relu_pos,
  input  logic        alu_alu_core_148_is_relu_neg,
  input  logic        alu_alu_core_148_is_tag_gate,
  input  logic [15:0] pcc_pcc_verifier_156_MAX_INSTRUCTIONS,
  input  logic [15:0] pcc_pcc_verifier_156_MAX_REGISTERS,
  input  logic [15:0] pcc_pcc_verifier_156_MAX_GUARDS,
  input  logic        pcc_pcc_verifier_156_bounds_ok,
  input  logic        core_core_top_157_trap_signal,
  input  logic [63:0] core_core_top_157_current_instr,
  input  logic        core_core_top_157_core_halted,
  input  logic [31:0] pipe_rspu_pipeline_158_pipe_pc,
  input  logic        pipe_rspu_pipeline_158_pcc_valid,
  input  logic        pipe_rspu_pipeline_158_pcc_fault,
  input  logic [15:0] pipe_rspu_pipeline_158_cert_i,
  input  logic [15:0] pipe_rspu_pipeline_158_cert_r,
  input  logic [15:0] pipe_rspu_pipeline_158_cert_g,
  input  logic        pipe_rspu_pipeline_158_cert_h,
  input  logic        pipe_rspu_pipeline_158_cert_v,
  input  logic [15:0] pipe_rspu_pipeline_158_id_rs1,
  input  logic [15:0] pipe_rspu_pipeline_158_id_rs2,
  input  logic [15:0] pipe_rspu_pipeline_158_id_rd,
  input  logic [63:0] pipe_rspu_pipeline_158_id_val1,
  input  logic [63:0] pipe_rspu_pipeline_158_id_val2,
  input  logic        pipe_rspu_pipeline_158_reg_we,
  input  logic [63:0] pipe_rspu_pipeline_158_reg_din,
  input  logic [63:0] pipe_rspu_pipeline_158_ex_d1,
  input  logic [63:0] pipe_rspu_pipeline_158_ex_t1,
  input  logic [63:0] pipe_rspu_pipeline_158_ex_p1,
  input  logic [63:0] pipe_rspu_pipeline_158_ex_d2,
  input  logic [63:0] pipe_rspu_pipeline_158_ex_t2,
  input  logic [63:0] pipe_rspu_pipeline_158_ex_p2,
  input  logic [63:0] pipe_rspu_pipeline_158_ex_out_d,
  input  logic [63:0] pipe_rspu_pipeline_158_ex_out_t,
  input  logic [63:0] pipe_rspu_pipeline_158_ex_out_p,
  input  logic        pipe_rspu_pipeline_158_ex_trap,
  input  logic [15:0] pipe_rspu_pipeline_158_alu_op,
  input  logic [63:0] pipe_rspu_pipeline_158_ex_packed,
  input  logic [63:0] pipe_rspu_pipeline_158_mem_out,
  input  logic [31:0] pipe_rspu_pipeline_158_ram_addr,
  input  logic [63:0] alu_alu_core_160_res_data,
  input  logic [63:0] alu_alu_core_160_res_tag,
  input  logic [63:0] alu_alu_core_160_res_prov,
  input  logic        alu_alu_core_160_is_trap,
  input  logic        alu_alu_core_160_is_add,
  input  logic        alu_alu_core_160_is_sub,
  input  logic        alu_alu_core_160_is_relu_pos,
  input  logic        alu_alu_core_160_is_relu_neg,
  input  logic        alu_alu_core_160_is_tag_gate,
  input  logic [15:0] pcc_pcc_verifier_168_MAX_INSTRUCTIONS,
  input  logic [15:0] pcc_pcc_verifier_168_MAX_REGISTERS,
  input  logic [15:0] pcc_pcc_verifier_168_MAX_GUARDS,
  input  logic        pcc_pcc_verifier_168_bounds_ok,
  input  logic        core_core_top_169_trap_signal,
  input  logic [63:0] core_core_top_169_current_instr,
  input  logic        core_core_top_169_core_halted,
  input  logic [31:0] pipe_rspu_pipeline_170_pipe_pc,
  input  logic        pipe_rspu_pipeline_170_pcc_valid,
  input  logic        pipe_rspu_pipeline_170_pcc_fault,
  input  logic [15:0] pipe_rspu_pipeline_170_cert_i,
  input  logic [15:0] pipe_rspu_pipeline_170_cert_r,
  input  logic [15:0] pipe_rspu_pipeline_170_cert_g,
  input  logic        pipe_rspu_pipeline_170_cert_h,
  input  logic        pipe_rspu_pipeline_170_cert_v,
  input  logic [15:0] pipe_rspu_pipeline_170_id_rs1,
  input  logic [15:0] pipe_rspu_pipeline_170_id_rs2,
  input  logic [15:0] pipe_rspu_pipeline_170_id_rd,
  input  logic [63:0] pipe_rspu_pipeline_170_id_val1,
  input  logic [63:0] pipe_rspu_pipeline_170_id_val2,
  input  logic        pipe_rspu_pipeline_170_reg_we,
  input  logic [63:0] pipe_rspu_pipeline_170_reg_din,
  input  logic [63:0] pipe_rspu_pipeline_170_ex_d1,
  input  logic [63:0] pipe_rspu_pipeline_170_ex_t1,
  input  logic [63:0] pipe_rspu_pipeline_170_ex_p1,
  input  logic [63:0] pipe_rspu_pipeline_170_ex_d2,
  input  logic [63:0] pipe_rspu_pipeline_170_ex_t2,
  input  logic [63:0] pipe_rspu_pipeline_170_ex_p2,
  input  logic [63:0] pipe_rspu_pipeline_170_ex_out_d,
  input  logic [63:0] pipe_rspu_pipeline_170_ex_out_t,
  input  logic [63:0] pipe_rspu_pipeline_170_ex_out_p,
  input  logic        pipe_rspu_pipeline_170_ex_trap,
  input  logic [15:0] pipe_rspu_pipeline_170_alu_op,
  input  logic [63:0] pipe_rspu_pipeline_170_ex_packed,
  input  logic [63:0] pipe_rspu_pipeline_170_mem_out,
  input  logic [31:0] pipe_rspu_pipeline_170_ram_addr,
  input  logic [63:0] alu_alu_core_172_res_data,
  input  logic [63:0] alu_alu_core_172_res_tag,
  input  logic [63:0] alu_alu_core_172_res_prov,
  input  logic        alu_alu_core_172_is_trap,
  input  logic        alu_alu_core_172_is_add,
  input  logic        alu_alu_core_172_is_sub,
  input  logic        alu_alu_core_172_is_relu_pos,
  input  logic        alu_alu_core_172_is_relu_neg,
  input  logic        alu_alu_core_172_is_tag_gate,
  input  logic [15:0] pcc_pcc_verifier_180_MAX_INSTRUCTIONS,
  input  logic [15:0] pcc_pcc_verifier_180_MAX_REGISTERS,
  input  logic [15:0] pcc_pcc_verifier_180_MAX_GUARDS,
  input  logic        pcc_pcc_verifier_180_bounds_ok,
  input  logic        core_core_top_181_trap_signal,
  input  logic [63:0] core_core_top_181_current_instr,
  input  logic        core_core_top_181_core_halted,
  input  logic [31:0] pipe_rspu_pipeline_182_pipe_pc,
  input  logic        pipe_rspu_pipeline_182_pcc_valid,
  input  logic        pipe_rspu_pipeline_182_pcc_fault,
  input  logic [15:0] pipe_rspu_pipeline_182_cert_i,
  input  logic [15:0] pipe_rspu_pipeline_182_cert_r,
  input  logic [15:0] pipe_rspu_pipeline_182_cert_g,
  input  logic        pipe_rspu_pipeline_182_cert_h,
  input  logic        pipe_rspu_pipeline_182_cert_v,
  input  logic [15:0] pipe_rspu_pipeline_182_id_rs1,
  input  logic [15:0] pipe_rspu_pipeline_182_id_rs2,
  input  logic [15:0] pipe_rspu_pipeline_182_id_rd,
  input  logic [63:0] pipe_rspu_pipeline_182_id_val1,
  input  logic [63:0] pipe_rspu_pipeline_182_id_val2,
  input  logic        pipe_rspu_pipeline_182_reg_we,
  input  logic [63:0] pipe_rspu_pipeline_182_reg_din,
  input  logic [63:0] pipe_rspu_pipeline_182_ex_d1,
  input  logic [63:0] pipe_rspu_pipeline_182_ex_t1,
  input  logic [63:0] pipe_rspu_pipeline_182_ex_p1,
  input  logic [63:0] pipe_rspu_pipeline_182_ex_d2,
  input  logic [63:0] pipe_rspu_pipeline_182_ex_t2,
  input  logic [63:0] pipe_rspu_pipeline_182_ex_p2,
  input  logic [63:0] pipe_rspu_pipeline_182_ex_out_d,
  input  logic [63:0] pipe_rspu_pipeline_182_ex_out_t,
  input  logic [63:0] pipe_rspu_pipeline_182_ex_out_p,
  input  logic        pipe_rspu_pipeline_182_ex_trap,
  input  logic [15:0] pipe_rspu_pipeline_182_alu_op,
  input  logic [63:0] pipe_rspu_pipeline_182_ex_packed,
  input  logic [63:0] pipe_rspu_pipeline_182_mem_out,
  input  logic [31:0] pipe_rspu_pipeline_182_ram_addr,
  input  logic [63:0] alu_alu_core_184_res_data,
  input  logic [63:0] alu_alu_core_184_res_tag,
  input  logic [63:0] alu_alu_core_184_res_prov,
  input  logic        alu_alu_core_184_is_trap,
  input  logic        alu_alu_core_184_is_add,
  input  logic        alu_alu_core_184_is_sub,
  input  logic        alu_alu_core_184_is_relu_pos,
  input  logic        alu_alu_core_184_is_relu_neg,
  input  logic        alu_alu_core_184_is_tag_gate,
  input  logic [15:0] pcc_pcc_verifier_192_MAX_INSTRUCTIONS,
  input  logic [15:0] pcc_pcc_verifier_192_MAX_REGISTERS,
  input  logic [15:0] pcc_pcc_verifier_192_MAX_GUARDS,
  input  logic        pcc_pcc_verifier_192_bounds_ok,
  input  logic signed [63:0] ctrl_controller_193_kp_torque,
  input  logic signed [63:0] ctrl_controller_193_kd_torque,
  input  logic signed [63:0] ctrl_controller_193_t_next,
  input  logic signed [63:0] physics_pendulum_194_angular_velocity,
  input  logic signed [63:0] physics_pendulum_194_angle_internal,
  input  logic signed [63:0] physics_pendulum_194_v_next,
  input  logic signed [63:0] physics_pendulum_194_p_next
);

  // property: system_stability
  assert property (@(posedge clk) disable iff (!rst_n) (((robot_angle < (-(-100000))) & (robot_angle > (-100000)))));

  // property: physics_pendulum_194_balance_limit
  assert property (@(posedge clk) disable iff (!rst_n) ((((-physics_pendulum_194_angle_internal) > (-102891)) & (physics_pendulum_194_angle_internal > (-102891)))));

endmodule

bind rspu_top rspu_top_sva u_sva (.*);
