//! SVA property assertion emission, module structure helpers,
//! and input synchronizer chain generation.

#![forbid(unsafe_code)]

use crate::ast::property::{PropertyDirective, PropertyFormula};
use crate::ast::types::SignalKind;
use crate::emit::fpga_target::MAX_SYNC_STAGES;
use crate::emit::verilog::emit_source_comment;
use crate::pipeline::PipelineResult;
use crate::span::{FileTable, Span};

// -----------------------------------------------------------------------
// Module structure helpers
// -----------------------------------------------------------------------

pub(super) fn emit_header(out: &mut String) {
    out.push_str("// Auto-generated by MIRR compiler (Phase 6)\n");
    out.push_str("// Do not edit — regenerate from .mirr source.\n");
    out.push_str("// Target: SystemVerilog (.sv)\n\n");
}

/// Emit pattern expansion annotations as SV comments using the registry.
pub(super) fn emit_pattern_annotations_ecs(registry: &crate::ecs::Registry, out: &mut String) {
    if registry.pattern_origins.is_empty() {
        return;
    }
    out.push_str("// ── Pattern Expansions ──\n");
    for origin in &registry.pattern_origins {
        out.push_str(&format!(
            "// Pattern: {}({})\n",
            origin.pattern_name, origin.call_args_summary
        ));
    }
    out.push('\n');
}

pub(super) fn emit_module_decl(
    module_name: &str,
    registry: &crate::ecs::Registry,
    ft: &FileTable,
    out: &mut String,
    span: Option<&Span>,
) {
    emit_source_comment(span, ft, out);
    out.push_str(&format!("module {} (\n", module_name));

    let has_clk = registry
        .names
        .iter()
        .any(|n| n.as_ref().is_some_and(|nc| registry.resolve_name(nc.0) == "clk"));
    let has_rst_n = module_has_rst_n(registry);

    // Check if temporal guards exist
    let mut needs_temporal = false;
    for k in &registry.kinds {
        if let Some(crate::ecs::components::KindComponent(crate::ecs::EntityKind::GUARD)) = k {
            needs_temporal = true;
            break;
        }
    }

    let mut ports: Vec<String> = Vec::new();

    // Auto-inject clk and rst_n when temporal guards exist.
    if needs_temporal && !has_clk {
        ports.push("  input  logic        clk".to_string());
    }
    if needs_temporal && !has_rst_n {
        ports.push("  input  logic        rst_n".to_string());
    }

    for i in 0..registry.names.len() {
        if let (Some(nc), Some(kind_comp), Some(type_comp)) =
            (registry.names[i], &registry.kinds[i], &registry.types[i])
        {
            if let crate::ecs::EntityKind::SIGNAL(sig_kind) = kind_comp.0 {
                let name = registry.resolve_name(nc.0);
                if sig_kind == SignalKind::Input || sig_kind == SignalKind::Output {
                    let dir = match sig_kind {
                        SignalKind::Input => "input ",
                        SignalKind::Output => "output",
                        SignalKind::Internal => "internal",
                    };
                    let type_str = super::super::sv_type(&type_comp.0.signal_type());
                    ports.push(format!("  {dir} {type_str} {}", name));
                }
            }
        }
    }

    let port_count = ports.len();
    for (i, port) in ports.iter().enumerate() {
        let comma = if i + 1 < port_count { "," } else { "" };
        out.push_str(&format!("{port}{comma}\n"));
    }

    out.push_str(");\n\n");
}

pub(super) fn emit_internal_signals(
    registry: &crate::ecs::Registry,
    ft: &FileTable,
    out: &mut String,
) {
    let mut has_internals = false;
    for i in 0..registry.names.len() {
        if let Some(crate::ecs::components::KindComponent(crate::ecs::EntityKind::SIGNAL(
            SignalKind::Internal,
        ))) = registry.kinds[i]
        {
            has_internals = true;
            break;
        }
    }

    if !has_internals {
        return;
    }

    out.push_str("  // Internal signals\n");
    for i in 0..registry.names.len() {
        if let (Some(nc), Some(kind_comp), Some(type_comp)) =
            (registry.names[i], &registry.kinds[i], &registry.types[i])
        {
            if let crate::ecs::EntityKind::SIGNAL(SignalKind::Internal) = kind_comp.0 {
                let name = registry.resolve_name(nc.0);
                let span = registry.spans[i].as_ref().map(|s| &s.0);
                emit_source_comment(span, ft, out);
                let type_str = super::super::sv_type(&type_comp.0.signal_type());
                out.push_str(&format!("  {type_str} {};\n", name));
            }
        }
    }
    out.push('\n');
}

pub(super) fn emit_module_end(out: &mut String) {
    out.push_str("endmodule\n");
}

// -----------------------------------------------------------------------
// Safety Property Assertions (SVA)
// -----------------------------------------------------------------------

/// Check if the registry declares an input signal named `rst_n`.
pub(super) fn module_has_rst_n(registry: &crate::ecs::Registry) -> bool {
    for i in 0..registry.names.len() {
        if let (Some(name_comp), Some(kind_comp)) = (&registry.names[i], &registry.kinds[i]) {
            let sname = registry.resolve_name(name_comp.0);
            if sname == "rst_n" {
                if let crate::ecs::EntityKind::SIGNAL(SignalKind::Input) = kind_comp.0 {
                    return true;
                }
            }
        }
    }
    false
}

/// Emit SVA assertion blocks for all property declarations.
pub(super) fn emit_property_assertions(
    registry: &crate::ecs::Registry,
    has_rst_n: bool,
    ft: &FileTable,
    out: &mut String,
) {
    let mut has_properties = false;
    for kind_comp in registry.kinds.iter() {
        if let Some(crate::ecs::components::KindComponent(crate::ecs::EntityKind::PROPERTY)) =
            kind_comp
        {
            has_properties = true;
            break;
        }
    }

    if !has_properties {
        return;
    }

    out.push_str("  // ── Safety Properties (SVA) ──\n\n");

    for i in 0..registry.names.len() {
        if let (Some(nc), Some(kind_comp), Some(prop_comp)) =
            (registry.names[i], &registry.kinds[i], &registry.property_comps[i])
        {
            if let crate::ecs::EntityKind::PROPERTY = kind_comp.0 {
                let name = registry.resolve_name(nc.0);
                let span = registry.spans[i].as_ref().map(|s| &s.0);
                emit_single_property(name, prop_comp, has_rst_n, registry, ft, out, span);
            }
        }
    }
}

/// Emit a single SVA `assert property` statement.
pub(super) fn emit_single_property(
    prop_name: &str,
    prop: &crate::ecs::components::PropertyComponent,
    has_rst_n: bool,
    registry: &crate::ecs::Registry,
    ft: &FileTable,
    out: &mut String,
    span: Option<&Span>,
) {
    emit_source_comment(span, ft, out);
    if let Some(ref origin) = prop.origin {
        out.push_str(&format!("  // Pattern: {origin}\n"));
    }
    out.push_str(&format!("  // property: {}\n", prop_name));

    let sva_keyword = match prop.directive {
        PropertyDirective::Assert => "assert property",
        PropertyDirective::Cover => "cover property",
        PropertyDirective::Assume => "assume property",
    };

    let disable_clause = if has_rst_n { "disable iff (!rst_n) " } else { "" };
    let prefix = format!("{sva_keyword} (@(posedge clk) {disable_clause}");

    match &prop.formula {
        PropertyFormula::Always(_) => {
            let sv_expr = super::emit_expr_inline(prop.formula_exprs[0], registry);
            out.push_str(&format!("  {prefix}({sv_expr}));\n\n"));
        }
        PropertyFormula::Never(_) => {
            let sv_expr = super::emit_expr_inline(prop.formula_exprs[0], registry);
            out.push_str(&format!("  {prefix}!({sv_expr}));\n\n"));
        }
        PropertyFormula::AlwaysImplies { .. } => {
            let ante_sv = super::emit_expr_inline(prop.formula_exprs[0], registry);
            let cons_sv = super::emit_expr_inline(prop.formula_exprs[1], registry);
            out.push_str(&format!("  {prefix}({ante_sv}) |-> ({cons_sv}));\n\n"));
        }
        PropertyFormula::NeverImplies { .. } => {
            let ante_sv = super::emit_expr_inline(prop.formula_exprs[0], registry);
            let cons_sv = super::emit_expr_inline(prop.formula_exprs[1], registry);
            out.push_str(&format!("  {prefix}({ante_sv}) |-> !({cons_sv}));\n\n"));
        }
        PropertyFormula::EventuallyWithin { expr: _, cycles } => {
            let sv_expr = super::emit_expr_inline(prop.formula_exprs[0], registry);
            out.push_str(&format!("  reg [31:0] prop_{prop_name}_timer;\n"));
            out.push_str("  always @(posedge clk) begin\n");
            if has_rst_n {
                out.push_str(&format!("    if (!rst_n) prop_{prop_name}_timer <= 0;\n"));
                out.push_str(&format!("    else if ({sv_expr}) prop_{prop_name}_timer <= 0;\n"));
                out.push_str(&format!(
                    "    else prop_{prop_name}_timer <= prop_{prop_name}_timer + 1;\n"
                ));
            } else {
                out.push_str(&format!("    if ({sv_expr}) prop_{prop_name}_timer <= 0;\n"));
                out.push_str(&format!(
                    "    else prop_{prop_name}_timer <= prop_{prop_name}_timer + 1;\n"
                ));
            }
            out.push_str("  end\n");
            out.push_str(&format!("  {prefix}(prop_{prop_name}_timer < {cycles}));\n\n"));
        }
        PropertyFormula::AlwaysFollowedBy { trigger: _, response: _, delay_cycles } => {
            let trig_sv = super::emit_expr_inline(prop.formula_exprs[0], registry);
            let resp_sv = super::emit_expr_inline(prop.formula_exprs[1], registry);

            if *delay_cycles == 0 {
                out.push_str(&format!("  {prefix}({trig_sv}) |-> ({resp_sv}));\n\n"));
            } else if *delay_cycles == 1 {
                out.push_str(&format!("  reg prop_{prop_name}_trig_d1;\n"));
                out.push_str("  always @(posedge clk) begin\n");
                if has_rst_n {
                    out.push_str(&format!("    if (!rst_n) prop_{prop_name}_trig_d1 <= 0;\n"));
                    out.push_str(&format!("    else prop_{prop_name}_trig_d1 <= {trig_sv};\n"));
                } else {
                    out.push_str(&format!("    prop_{prop_name}_trig_d1 <= {trig_sv};\n"));
                }
                out.push_str("  end\n");
                out.push_str(&format!(
                    "  {prefix}(prop_{prop_name}_trig_d1) |-> ({resp_sv}));\n\n"
                ));
            } else {
                let msb = delay_cycles - 1;
                out.push_str(&format!("  reg [{msb}:0] prop_{prop_name}_trig_shift;\n"));
                out.push_str("  always @(posedge clk) begin\n");
                let shift_expr = if *delay_cycles == 2 {
                    format!("{{prop_{prop_name}_trig_shift[0], {trig_sv}}}")
                } else {
                    format!("{{prop_{prop_name}_trig_shift[{}:0], {trig_sv}}}", msb - 1)
                };
                if has_rst_n {
                    out.push_str(&format!("    if (!rst_n) prop_{prop_name}_trig_shift <= 0;\n"));
                    out.push_str(&format!(
                        "    else prop_{prop_name}_trig_shift <= {shift_expr};\n"
                    ));
                } else {
                    out.push_str(&format!("    prop_{prop_name}_trig_shift <= {shift_expr};\n"));
                }
                out.push_str("  end\n");
                out.push_str(&format!(
                    "  {prefix}(prop_{prop_name}_trig_shift[{msb}]) |-> ({resp_sv}));\n\n"
                ));
            }
        }
    }
}

// -----------------------------------------------------------------------
// Input Synchronizer Chains
// -----------------------------------------------------------------------

/// Emit 2-stage (or N-stage) synchronizer chains for all input signals
/// except `clk` and `rst_n`. Returns a mapping of original signal names
/// to their synchronized versions (_s suffix).
pub fn emit_synchronizer_chains(
    registry: &crate::ecs::Registry,
    sync_stages: u32,
    out: &mut String,
) -> Vec<(String, String)> {
    if sync_stages == 0 {
        return Vec::new();
    }
    let stages = sync_stages.min(MAX_SYNC_STAGES);

    let mut mappings = Vec::new();
    out.push_str("  // ── Input Synchronizer Chains ──\n\n");

    for i in 0..registry.names.len() {
        if let (Some(nc), Some(kind_comp), Some(type_comp)) =
            (registry.names[i], &registry.kinds[i], &registry.types[i])
        {
            if let crate::ecs::EntityKind::SIGNAL(SignalKind::Input) = kind_comp.0 {
                let name = registry.resolve_name(nc.0);
                if name == "clk" || name == "rst_n" {
                    continue;
                }

                let width = type_comp.0.signal_type().width();
                let sync_name = format!("{}_s", name);
                let sync_reg = format!("{}_sync", name);

                // Declare synchronizer register chain.
                let total_bits = width * stages;
                out.push_str(&format!("  // {}-stage synchronizer for {}\n", stages, name));
                out.push_str(&format!(
                    "  logic [{}:0] {};\n",
                    total_bits.saturating_sub(1),
                    sync_reg,
                ));

                // Sequential synchronizer logic.
                out.push_str("  always_ff @(posedge clk or negedge rst_n) begin\n");
                out.push_str(&format!("    if (!rst_n)\n      {} <= '0;\n", sync_reg));
                if stages == 1 {
                    out.push_str(&format!("    else\n      {} <= {};\n", sync_reg, name));
                } else {
                    // Shift chain: {input, sync[high:width]}
                    out.push_str(&format!(
                        "    else\n      {} <= {{{}, {}[{}:{}]}};\n",
                        sync_reg,
                        name,
                        sync_reg,
                        total_bits.saturating_sub(1),
                        width,
                    ));
                }
                out.push_str("  end\n");

                // Output: synchronized signal is the last stage.
                let type_str = super::super::sv_type(&type_comp.0.signal_type());
                out.push_str(&format!(
                    "  {} {} = {}[{}:0];\n\n",
                    type_str,
                    sync_name,
                    sync_reg,
                    width.saturating_sub(1),
                ));

                mappings.push((name.to_string(), sync_name));
            }
        }
    }

    mappings
}

/// Emit only the SVA assertion block (no module wrapper).
///
/// Used by `--emit sva` standalone mode.
pub fn emit_sva_only(result: &PipelineResult) -> String {
    let registry = result.ecs_registry.as_ref().expect("ECS registry required");
    let module_name = registry.get_module_name().unwrap_or_else(|| "unnamed".to_string());
    let ft = &result.file_table;
    let mut out = String::with_capacity(1024);

    out.push_str("// Auto-generated SVA assertions from MIRR compiler\n");
    out.push_str(&format!("// Module: {}\n\n", module_name));

    let has_rst_n = module_has_rst_n(registry);

    emit_property_assertions(registry, has_rst_n, ft, &mut out);

    out
}
