//! SVA property assertion emission, module structure helpers,
//! and input synchronizer chain generation.

#![forbid(unsafe_code)]

use crate::ast::property::{PropertyDirective, PropertyFormula};
use crate::ast::types::SignalKind;
use crate::emit::fpga_target::MAX_SYNC_STAGES;
use crate::emit::verilog::emit_source_comment;
use crate::pipeline::PipelineResult;
use crate::span::{FileTable, Span};
use std::fmt::Write;

// -----------------------------------------------------------------------
// Module structure helpers
// -----------------------------------------------------------------------

pub(super) fn emit_header(out: &mut String) {
    out.push_str("// Auto-generated by MIRR compiler (Phase 6)\n");
    out.push_str("// Do not edit — regenerate from .mirr source.\n");
    out.push_str("// Target: SystemVerilog (.sv)\n\n");
}

/// Emit pattern expansion annotations as SV comments using the registry.
pub(super) fn emit_pattern_annotations_ecs(registry: &crate::ecs::Registry, out: &mut String) {
    if registry.pattern_origins.is_empty() {
        return;
    }
    out.push_str("// ── Pattern Expansions ──\n");
    for origin in &registry.pattern_origins {
        writeln!(out, "// Pattern: {}({})", origin.pattern_name, origin.call_args_summary).unwrap();
    }
    out.push('\n');
}

pub(super) fn emit_module_decl(
    module_name: &str,
    registry: &crate::ecs::Registry,
    ft: &FileTable,
    out: &mut String,
    span: Option<&Span>,
) {
    emit_source_comment(span, ft, out);

    // Silence benign Verilator lints for generated code
    out.push_str("/* verilator lint_off UNOPTFLAT */\n");
    out.push_str("/* verilator lint_off DECLFILENAME */\n");
    out.push_str("/* verilator lint_off WIDTH */\n");
    out.push_str("/* verilator lint_off WIDTHTRUNC */\n");
    out.push_str("/* verilator lint_off WIDTHEXPAND */\n");
    out.push_str("/* verilator lint_off SYNCASYNCNET */\n");
    out.push_str("/* verilator lint_off PINCONNECTEMPTY */\n");
    out.push_str("/* verilator lint_off UNDRIVEN */\n");
    out.push_str("/* verilator lint_off UNUSED */\n\n");

    writeln!(out, "module {} (", module_name).unwrap();

    // Check if temporal guards exist
    let mut needs_temporal = false;
    for k in &registry.kinds {
        if let Some(crate::ecs::components::KindComponent(crate::ecs::EntityKind::GUARD)) = k {
            needs_temporal = true;
            break;
        }
    }

    let top_module_id = registry.kinds.iter().enumerate().rev().find_map(|(i, k)| {
        if let Some(crate::ecs::components::KindComponent(crate::ecs::EntityKind::MODULE)) = k {
            Some(crate::ecs::EntityId(i as u32))
        } else {
            None
        }
    });

    let mut declared_ports: Vec<String> = Vec::new();
    let mut has_clk = false;
    let mut has_rst_n = false;

    for i in 0..registry.names.len() {
        // Only include signals belonging to the top-level module
        if let Some(top_id) = top_module_id {
            if let Some(crate::ecs::components::ModuleComponent(parent_id)) = &registry.modules[i] {
                if *parent_id != top_id {
                    continue;
                }
            } else {
                continue; // No parent module means it's not a signal of the top module
            }
        }

        if let (Some(nc), Some(kind_comp), Some(type_comp)) =
            (registry.names[i], &registry.kinds[i], &registry.types[i])
        {
            if let crate::ecs::EntityKind::SIGNAL(sig_kind) = kind_comp.0 {
                let name = registry.resolve_name(nc.0);
                if sig_kind == SignalKind::Input || sig_kind == SignalKind::Output {
                    if name == "clk" {
                        has_clk = true;
                    }
                    if name == "rst_n" {
                        has_rst_n = true;
                    }
                    let dir = match sig_kind {
                        SignalKind::Input => "input ",
                        SignalKind::Output => "output",
                        SignalKind::Internal => "internal",
                    };
                    let type_str = super::super::sv_type(&type_comp.0.signal_type());
                    declared_ports.push(format!("  {dir} {type_str} {}", name));
                }
            }
        }
    }

    let mut ports: Vec<String> = Vec::new();
    if needs_temporal && !has_clk {
        ports.push("  input  logic        clk".to_string());
    }
    if needs_temporal && !has_rst_n {
        ports.push("  input  logic        rst_n".to_string());
    }
    ports.extend(declared_ports);

    let port_count = ports.len();
    for (i, port) in ports.iter().enumerate() {
        let comma = if i + 1 < port_count { "," } else { "" };
        writeln!(out, "{port}{comma}").unwrap();
    }

    out.push_str(");\n\n");
}

pub(super) fn emit_internal_signals(
    registry: &crate::ecs::Registry,
    ft: &FileTable,
    out: &mut String,
) {
    let top_module_id = registry.kinds.iter().enumerate().rev().find_map(|(i, k)| {
        if let Some(crate::ecs::components::KindComponent(crate::ecs::EntityKind::MODULE)) = k {
            Some(crate::ecs::EntityId(i as u32))
        } else {
            None
        }
    });

    let mut has_internals = false;
    for i in 0..registry.names.len() {
        if let Some(top_id) = top_module_id {
            if let Some(crate::ecs::components::ModuleComponent(parent_id)) = &registry.modules[i] {
                if *parent_id != top_id {
                    continue;
                }
            } else {
                continue;
            }
        }

        if let Some(crate::ecs::components::KindComponent(crate::ecs::EntityKind::SIGNAL(
            SignalKind::Internal,
        ))) = registry.kinds[i]
        {
            has_internals = true;
            break;
        }
    }

    if !has_internals {
        return;
    }

    out.push_str("  // Internal signals\n");
    for i in 0..registry.names.len() {
        if let Some(top_id) = top_module_id {
            if let Some(crate::ecs::components::ModuleComponent(parent_id)) = &registry.modules[i] {
                if *parent_id != top_id {
                    continue;
                }
            } else {
                continue;
            }
        }

        if let (Some(nc), Some(kind_comp), Some(type_comp)) =
            (registry.names[i], &registry.kinds[i], &registry.types[i])
        {
            if let crate::ecs::EntityKind::SIGNAL(SignalKind::Internal) = kind_comp.0 {
                let name = registry.resolve_name(nc.0);
                let span = registry.spans[i].as_ref().map(|s| &s.0);
                emit_source_comment(span, ft, out);
                let type_str = super::super::sv_type(&type_comp.0.signal_type());
                writeln!(out, "  {type_str} {};", name).unwrap();
            }
        }
    }
    out.push('\n');

    out.push_str("  // Physical Power-On Reset Initialization (Matches FPGA target reality)\n");
    out.push_str("  initial begin\n");
    for i in 0..registry.names.len() {
        if let Some(top_id) = top_module_id {
            if let Some(crate::ecs::components::ModuleComponent(parent_id)) = &registry.modules[i] {
                if *parent_id != top_id {
                    continue;
                }
            } else {
                continue;
            }
        }

        if let (Some(nc), Some(kind_comp)) = (&registry.names[i], &registry.kinds[i]) {
            if let crate::ecs::EntityKind::SIGNAL(SignalKind::Internal) = kind_comp.0 {
                let name = registry.resolve_name(nc.0);
                writeln!(out, "    {} = '0;", name).unwrap();
            }
        }
    }
    out.push_str("  end\n\n");
}

pub(super) fn emit_module_end(out: &mut String) {
    out.push_str("endmodule\n");
}

// -----------------------------------------------------------------------
// Safety Property Assertions (SVA)
// -----------------------------------------------------------------------

/// Check if the registry declares an input signal named `rst_n`.
pub(super) fn module_has_rst_n(registry: &crate::ecs::Registry) -> bool {
    let top_module_id = registry.kinds.iter().enumerate().rev().find_map(|(i, k)| {
        if let Some(crate::ecs::components::KindComponent(crate::ecs::EntityKind::MODULE)) = k {
            Some(crate::ecs::EntityId(i as u32))
        } else {
            None
        }
    });

    for i in 0..registry.names.len() {
        if let Some(top_id) = top_module_id {
            if let Some(crate::ecs::components::ModuleComponent(parent_id)) = &registry.modules[i] {
                if *parent_id != top_id {
                    continue;
                }
            } else {
                continue;
            }
        }

        if let (Some(name_comp), Some(kind_comp)) = (&registry.names[i], &registry.kinds[i]) {
            let sname = registry.resolve_name(name_comp.0);
            if sname == "rst_n" {
                if let crate::ecs::EntityKind::SIGNAL(SignalKind::Input) = kind_comp.0 {
                    return true;
                }
            }
        }
    }
    false
}

/// Emit SVA assertion blocks for all property declarations.
pub(super) fn emit_property_assertions(
    registry: &crate::ecs::Registry,
    has_rst_n: bool,
    sync_map: &std::collections::HashMap<String, String>,
    ft: &FileTable,
    out: &mut String,
) {
    let top_module_id = registry.kinds.iter().enumerate().rev().find_map(|(i, k)| {
        if let Some(crate::ecs::components::KindComponent(crate::ecs::EntityKind::MODULE)) = k {
            Some(crate::ecs::EntityId(i as u32))
        } else {
            None
        }
    });

    let mut has_properties = false;
    for i in 0..registry.names.len() {
        if let Some(top_id) = top_module_id {
            if let Some(crate::ecs::components::ModuleComponent(parent_id)) = &registry.modules[i] {
                if *parent_id != top_id {
                    continue;
                }
            } else {
                continue;
            }
        }

        if let Some(crate::ecs::components::KindComponent(crate::ecs::EntityKind::PROPERTY)) =
            registry.kinds[i]
        {
            has_properties = true;
            break;
        }
    }

    if !has_properties {
        return;
    }

    out.push_str("  // ── Safety Properties (SVA) ──\n\n");

    if has_rst_n {
        out.push_str("  // Enforce reset sequence for formal verification\n");
        out.push_str("  reg f_past_valid = 0;\n");
        out.push_str("  always_ff @(posedge clk) begin\n");
        out.push_str("    f_past_valid <= 1;\n");
        out.push_str("  end\n");
        out.push_str("  always_comb begin\n");
        out.push_str("    if (!f_past_valid) assume (!rst_n);\n");
        out.push_str("  end\n\n");
    }

    for i in 0..registry.names.len() {
        if let Some(top_id) = top_module_id {
            if let Some(crate::ecs::components::ModuleComponent(parent_id)) = &registry.modules[i] {
                if *parent_id != top_id {
                    continue;
                }
            } else {
                continue;
            }
        }

        if let (Some(nc), Some(kind_comp), Some(prop_comp)) =
            (registry.names[i], &registry.kinds[i], &registry.property_comps[i])
        {
            if let crate::ecs::EntityKind::PROPERTY = kind_comp.0 {
                let name = registry.resolve_name(nc.0);
                let span = registry.spans[i].as_ref().map(|s| &s.0);

                let mut clock_domain = "clk";
                if let Some(tc) = &registry.types[i] {
                    if let Some(cd) = tc.0.annotations.clock_domain.as_deref() {
                        clock_domain = cd;
                    }
                }

                emit_single_property(
                    name,
                    prop_comp,
                    clock_domain,
                    has_rst_n,
                    registry,
                    sync_map,
                    ft,
                    out,
                    span,
                );
            }
        }
    }
}

/// Emit a single SVA `assert property` statement.
#[allow(clippy::too_many_arguments)]
pub(super) fn emit_single_property(
    prop_name: &str,
    prop: &crate::ecs::components::PropertyComponent,
    clock: &str,
    has_rst_n: bool,
    registry: &crate::ecs::Registry,
    sync_map: &std::collections::HashMap<String, String>,
    ft: &FileTable,
    out: &mut String,
    span: Option<&Span>,
) {
    emit_source_comment(span, ft, out);
    if let Some(ref origin) = prop.origin {
        writeln!(out, "  // Pattern: {origin}").unwrap();
    }
    writeln!(out, "  // property: {}", prop_name).unwrap();

    let sva_keyword = match prop.directive {
        PropertyDirective::Assert => "assert",
        PropertyDirective::Cover => "cover",
        PropertyDirective::Assume => "assume",
    };

    let prefix = if has_rst_n {
        format!("  always @(posedge {clock}) begin\n    if (rst_n) begin\n      {prop_name}: {sva_keyword}(")
    } else {
        format!("  always @(posedge {clock}) begin\n    {prop_name}: {sva_keyword}(")
    };
    let suffix = if has_rst_n { ");\n    end\n  end\n\n" } else { ");\n  end\n\n" };

    match &prop.formula {
        PropertyFormula::Always(_) => {
            let sv_expr = super::emit_expr_inline(prop.formula_exprs[0], registry, sync_map);
            write!(out, "{prefix}{sv_expr}{suffix}").unwrap();
        }
        PropertyFormula::Never(_) => {
            let sv_expr = super::emit_expr_inline(prop.formula_exprs[0], registry, sync_map);
            write!(out, "{prefix}!({sv_expr}){suffix}").unwrap();
        }
        PropertyFormula::AlwaysImplies { .. } => {
            let ante_sv = super::emit_expr_inline(prop.formula_exprs[0], registry, sync_map);
            let cons_sv = super::emit_expr_inline(prop.formula_exprs[1], registry, sync_map);
            write!(out, "{prefix}(!({ante_sv})) || ({cons_sv}){suffix}").unwrap();
        }
        PropertyFormula::NeverImplies { .. } => {
            let ante_sv = super::emit_expr_inline(prop.formula_exprs[0], registry, sync_map);
            let cons_sv = super::emit_expr_inline(prop.formula_exprs[1], registry, sync_map);
            write!(out, "{prefix}(!({ante_sv})) || (!({cons_sv})){suffix}").unwrap();
        }
        PropertyFormula::EventuallyWithin { expr: _, cycles } => {
            let sv_expr = super::emit_expr_inline(prop.formula_exprs[0], registry, sync_map);
            writeln!(out, "  reg [31:0] prop_{prop_name}_timer;").unwrap();
            writeln!(out, "  always @(posedge {clock}) begin").unwrap();
            if has_rst_n {
                writeln!(out, "    if (!rst_n) prop_{prop_name}_timer <= 0;").unwrap();
                writeln!(out, "    else if ({sv_expr}) prop_{prop_name}_timer <= 0;").unwrap();
                writeln!(out, "    else prop_{prop_name}_timer <= prop_{prop_name}_timer + 1;")
                    .unwrap();
            } else {
                writeln!(out, "    if ({sv_expr}) prop_{prop_name}_timer <= 0;").unwrap();
                writeln!(out, "    else prop_{prop_name}_timer <= prop_{prop_name}_timer + 1;")
                    .unwrap();
            }
            out.push_str("  end\n");
            write!(out, "{prefix}prop_{prop_name}_timer < {cycles}{suffix}").unwrap();
        }
        PropertyFormula::AlwaysFollowedBy { trigger: _, response: _, delay_cycles } => {
            let trig_sv = super::emit_expr_inline(prop.formula_exprs[0], registry, sync_map);
            let resp_sv = super::emit_expr_inline(prop.formula_exprs[1], registry, sync_map);

            if *delay_cycles == 0 {
                write!(out, "{prefix}(!({trig_sv})) || ({resp_sv}){suffix}").unwrap();
            } else if *delay_cycles == 1 {
                writeln!(out, "  reg prop_{prop_name}_trig_d1;").unwrap();
                writeln!(out, "  always @(posedge {clock}) begin").unwrap();
                if has_rst_n {
                    writeln!(out, "    if (!rst_n) prop_{prop_name}_trig_d1 <= 0;").unwrap();
                    writeln!(out, "    else prop_{prop_name}_trig_d1 <= {trig_sv};").unwrap();
                } else {
                    writeln!(out, "    prop_{prop_name}_trig_d1 <= {trig_sv};").unwrap();
                }
                out.push_str("  end\n");
                write!(out, "{prefix}(!(prop_{prop_name}_trig_d1)) || ({resp_sv}){suffix}")
                    .unwrap();
            } else {
                let msb = delay_cycles - 1;
                writeln!(out, "  reg [{msb}:0] prop_{prop_name}_trig_shift;").unwrap();
                writeln!(out, "  always @(posedge {clock}) begin").unwrap();
                let shift_expr = if *delay_cycles == 2 {
                    format!("{{prop_{prop_name}_trig_shift[0], {trig_sv}}}")
                } else {
                    format!("{{prop_{prop_name}_trig_shift[{}:0], {trig_sv}}}", msb - 1)
                };
                if has_rst_n {
                    writeln!(out, "    if (!rst_n) prop_{prop_name}_trig_shift <= 0;").unwrap();
                    writeln!(out, "    else prop_{prop_name}_trig_shift <= {shift_expr};").unwrap();
                } else {
                    writeln!(out, "    prop_{prop_name}_trig_shift <= {shift_expr};").unwrap();
                }
                out.push_str("  end\n");
                write!(
                    out,
                    "{prefix}(!(prop_{prop_name}_trig_shift[{msb}])) || ({resp_sv}){suffix}"
                )
                .unwrap();
            }
        }
    }
}

// -----------------------------------------------------------------------
// Input Synchronizer Chains
// -----------------------------------------------------------------------

/// Emit 2-stage (or N-stage) synchronizer chains for all input signals
/// except `clk` and `rst_n`. Returns a mapping of original signal names
/// to their synchronized versions (_s suffix).
pub fn emit_synchronizer_chains(
    registry: &crate::ecs::Registry,
    top_module_id: Option<crate::ecs::EntityId>,
    sync_stages: u32,
    out: &mut String,
) -> Vec<(String, String)> {
    if sync_stages == 0 {
        return Vec::new();
    }
    let stages = sync_stages.min(MAX_SYNC_STAGES);

    let mut mappings = Vec::new();
    out.push_str("  // ── Input Synchronizer Chains ──\n\n");

    for i in 0..registry.names.len() {
        if let (Some(nc), Some(kind_comp), Some(type_comp)) =
            (registry.names[i], &registry.kinds[i], &registry.types[i])
        {
            if let crate::ecs::EntityKind::SIGNAL(SignalKind::Input) = kind_comp.0 {
                // Skip if not belonging to top_module_id
                if let Some(top_id) = top_module_id {
                    if let Some(crate::ecs::components::ModuleComponent(sig_mod_id)) =
                        &registry.modules[i]
                    {
                        if *sig_mod_id != top_id {
                            continue;
                        }
                    }
                }

                let name = registry.resolve_name(nc.0);
                if name == "clk" || name == "rst_n" {
                    continue;
                }

                let width = type_comp.0.signal_type().width();
                let sync_name = format!("{}_s", name);
                let sync_reg = format!("{}_sync", name);

                let mut clock_domain = "clk";
                if let Some(cd) = type_comp.0.annotations.clock_domain.as_deref() {
                    clock_domain = cd;
                }

                // Declare synchronizer register chain.
                let total_bits = width * stages;
                writeln!(out, "  // {}-stage synchronizer for {} (@{clock_domain})", stages, name)
                    .unwrap();
                writeln!(out, "  logic [{}:0] {};", total_bits.saturating_sub(1), sync_reg,)
                    .unwrap();
                out.push_str("  initial begin\n");
                writeln!(out, "    {} = '0;", sync_reg).unwrap();
                out.push_str("  end\n");

                // Sequential synchronizer logic.
                writeln!(out, "  always_ff @(posedge {clock_domain} or negedge rst_n) begin")
                    .unwrap();
                write!(out, "    if (!rst_n)\n      {} <= '0;\n", sync_reg).unwrap();
                if stages == 1 {
                    write!(out, "    else\n      {} <= {};\n", sync_reg, name).unwrap();
                } else {
                    // Shift chain: {input, sync[high:width]}
                    write!(
                        out,
                        "    else\n      {} <= {{{}, {}[{}:{}]}};\n",
                        sync_reg,
                        name,
                        sync_reg,
                        total_bits.saturating_sub(1),
                        width,
                    )
                    .unwrap();
                }
                out.push_str("  end\n");

                // Output: synchronized signal is the last stage.
                let type_str = super::super::sv_type(&type_comp.0.signal_type());
                write!(
                    out,
                    "  {} {} = {}[{}:0];\n\n",
                    type_str,
                    sync_name,
                    sync_reg,
                    width.saturating_sub(1),
                )
                .unwrap();

                mappings.push((name.to_string(), sync_name));
            }
        }
    }

    mappings
}

/// Emit only the SVA assertion block (no module wrapper).
///
/// Used by `--emit sva` standalone mode.
pub fn emit_sva_only(result: &PipelineResult) -> String {
    let Some(registry) = result.ecs_registry.as_ref() else {
        return "// [MIRR COMPILER ERROR] ECS registry is missing. Cannot generate SVA assertions."
            .to_string();
    };
    let module_name = registry.get_module_name().unwrap_or_else(|| "unnamed".to_string());
    let ft = &result.file_table;
    let mut out = String::with_capacity(1024);

    out.push_str("// Auto-generated SVA assertions from MIRR compiler\n");
    write!(out, "// Module: {}\n\n", module_name).unwrap();

    let has_rst_n = module_has_rst_n(registry);

    let empty_map = std::collections::HashMap::new();
    emit_property_assertions(registry, has_rst_n, &empty_map, ft, &mut out);

    out
}
