@ ARM Thumb-2 Assembly — generated by MIRR compiler
@ Registers used: 212
@ Guards used:    2
@ Instructions:   38
@
@ Register map:
@   R0 = airway_pressure
@   R64 = clamp_valve
@
@ Guard map:
@   G0 = always
@   G1 = pressure_low

.syntax unified
.thumb
.section .text
.globl _start
.type _start, %function

_start:

instr_0:
    ldr r0, =0x40000000
    ldr r0, [r0]

instr_1:
    mov r0, #16

instr_2:
    mov r64, #1

instr_3:
    mov r192, #1

instr_4:
    mov r192, #1

instr_5:
    mov r193, #50

instr_6:
    mov r193, #16

instr_7:
    cmp r193, r0
    mov r194, #0
    it lt
    movlt r194, #1

instr_8:
    ldr r12, =guard_g1
    str r194, [r12]
    ldr r12, =sr_g1
    mov r11, #0
    str r11, [r12, #0]
    str r11, [r12, #4]
    str r11, [r12, #8]

instr_9:
    ldr r12, =sr_g1
    ldr r11, =guard_g1
    ldr r10, [r11]
    mov r9, #256
shift_loop_arm_1:
    sub r9, r9, #1
    cmp r9, #0
    beq shift_done_arm_1
    lsl r8, r9, #2
    sub r7, r8, #4
    ldr r6, [r12, r7]
    str r6, [r12, r8]
    b shift_loop_arm_1
shift_done_arm_1:
    str r10, [r12]

instr_10:
    ldr r12, =guard_g1
    ldr r195, [r12]
    and r195, r195, #1

instr_11:
    mov r193, #1

instr_12:
    ldr r12, =guard_g1
    ldr r11, [r12]
    cmp r11, #0
    it ne
    movne r64, r193

instr_13:
    mov r193, #10

instr_14:
    cmp r0, r193
    mov r194, #0
    it gt
    movgt r194, #1

instr_15:
    cmp r194, #0
    bne assert_pass_2
    bkpt #200
assert_pass_2:

instr_16:
    mov r193, #200

instr_17:
    cmp r0, r193
    mov r194, #0
    it gt
    movgt r194, #1

instr_18:
    and r195, r64, r194

instr_19:
    cmp r195, #0
    beq assert_pass_3
    bkpt #301
assert_pass_3:

instr_20:
    mov r193, #50

instr_21:
    cmp r0, r193
    mov r194, #0
    it lt
    movlt r194, #1

instr_22:
    mvn r195, r194

instr_23:
    orr r196, r195, r64

instr_24:
    cmp r196, #0
    bne assert_pass_4
    bkpt #202
assert_pass_4:

instr_25:
    ldr r12, =guard_g60
    str r64, [r12]
    ldr r12, =sr_g60
    mov r11, #0
    str r11, [r12, #0]
    str r11, [r12, #4]
    str r11, [r12, #8]
    str r11, [r12, #12]
    str r11, [r12, #16]
    str r11, [r12, #20]
    str r11, [r12, #24]
    str r11, [r12, #28]
    str r11, [r12, #32]
    str r11, [r12, #36]
    str r11, [r12, #40]
    str r11, [r12, #44]
    str r11, [r12, #48]
    str r11, [r12, #52]
    str r11, [r12, #56]
    str r11, [r12, #60]
    str r11, [r12, #64]
    str r11, [r12, #68]
    str r11, [r12, #72]
    str r11, [r12, #76]
    str r11, [r12, #80]
    str r11, [r12, #84]
    str r11, [r12, #88]
    str r11, [r12, #92]
    str r11, [r12, #96]
    str r11, [r12, #100]
    str r11, [r12, #104]
    str r11, [r12, #108]
    str r11, [r12, #112]
    str r11, [r12, #116]
    str r11, [r12, #120]
    str r11, [r12, #124]
    str r11, [r12, #128]
    str r11, [r12, #132]
    str r11, [r12, #136]
    str r11, [r12, #140]
    str r11, [r12, #144]
    str r11, [r12, #148]
    str r11, [r12, #152]
    str r11, [r12, #156]
    str r11, [r12, #160]
    str r11, [r12, #164]
    str r11, [r12, #168]
    str r11, [r12, #172]
    str r11, [r12, #176]
    str r11, [r12, #180]
    str r11, [r12, #184]
    str r11, [r12, #188]
    str r11, [r12, #192]
    str r11, [r12, #196]
    str r11, [r12, #200]
    str r11, [r12, #204]
    str r11, [r12, #208]
    str r11, [r12, #212]
    str r11, [r12, #216]
    str r11, [r12, #220]
    str r11, [r12, #224]
    str r11, [r12, #228]
    str r11, [r12, #232]
    str r11, [r12, #236]
    str r11, [r12, #240]
    str r11, [r12, #244]
    str r11, [r12, #248]
    str r11, [r12, #252]
    str r11, [r12, #256]
    str r11, [r12, #260]
    str r11, [r12, #264]
    str r11, [r12, #268]
    str r11, [r12, #272]
    str r11, [r12, #276]
    str r11, [r12, #280]
    str r11, [r12, #284]
    str r11, [r12, #288]
    str r11, [r12, #292]
    str r11, [r12, #296]
    str r11, [r12, #300]
    str r11, [r12, #304]
    str r11, [r12, #308]
    str r11, [r12, #312]
    str r11, [r12, #316]
    str r11, [r12, #320]
    str r11, [r12, #324]
    str r11, [r12, #328]
    str r11, [r12, #332]
    str r11, [r12, #336]
    str r11, [r12, #340]
    str r11, [r12, #344]
    str r11, [r12, #348]
    str r11, [r12, #352]
    str r11, [r12, #356]
    str r11, [r12, #360]
    str r11, [r12, #364]
    str r11, [r12, #368]
    str r11, [r12, #372]
    str r11, [r12, #376]
    str r11, [r12, #380]
    str r11, [r12, #384]
    str r11, [r12, #388]
    str r11, [r12, #392]
    str r11, [r12, #396]

instr_26:
    ldr r12, =sr_g60
    ldr r11, =guard_g60
    ldr r10, [r11]
    mov r9, #256
shift_loop_arm_5:
    sub r9, r9, #1
    cmp r9, #0
    beq shift_done_arm_5
    lsl r8, r9, #2
    sub r7, r8, #4
    ldr r6, [r12, r7]
    str r6, [r12, r8]
    b shift_loop_arm_5
shift_done_arm_5:
    str r10, [r12]

instr_27:
    ldr r12, =guard_g60
    ldr r193, [r12]
    and r193, r193, #1

instr_28:
    cmp r193, #0
    bne assert_pass_6
    bkpt #203
assert_pass_6:

instr_29:
    mov r193, #50

instr_30:
    cmp r0, r193
    mov r194, #0
    it lt
    movlt r194, #1

instr_31:
    ldr r12, =guard_g59
    str r194, [r12]
    ldr r12, =sr_g59
    mov r11, #0
    str r11, [r12, #0]
    str r11, [r12, #4]
    str r11, [r12, #8]
    str r11, [r12, #12]
    str r11, [r12, #16]

instr_32:
    ldr r12, =sr_g59
    ldr r11, =guard_g59
    ldr r10, [r11]
    mov r9, #256
shift_loop_arm_7:
    sub r9, r9, #1
    cmp r9, #0
    beq shift_done_arm_7
    lsl r8, r9, #2
    sub r7, r8, #4
    ldr r6, [r12, r7]
    str r6, [r12, r8]
    b shift_loop_arm_7
shift_done_arm_7:
    str r10, [r12]

instr_33:
    ldr r12, =guard_g59
    ldr r195, [r12]
    and r195, r195, #1

instr_34:
    mvn r196, r195

instr_35:
    orr r197, r196, r64

instr_36:
    cmp r197, #0
    bne assert_pass_8
    bkpt #204
assert_pass_8:

instr_37:
    ldr r12, =0x40000000
    str r64, [r12]

instr_halt:
    bkpt #0

.section .data
signal_airway_pressure: .word 0
signal_clamp_valve: .word 0
guard_always: .word 0
guard_pressure_low: .word 0
sr_always: .space 1024
sr_pressure_low: .space 1024
