// =============================================================
// MAPE-K RTL — auto-generated by MIRR compiler
// Do not edit — regenerate from .mirr source.
// =============================================================

// --- Monitor (M) -------------------------------------------
module mirr_monitor #(
  parameter N_SIGNALS = 2,
  parameter TRACE_DEPTH = 64
) (
  input  logic clk,
  input  logic rst_n,
  input  logic [N_SIGNALS-1:0][31:0] sensor_in,
  output logic [N_SIGNALS-1:0][31:0] shadow,
  output logic        sample_valid
);

  logic [5:0] wr_ptr;
  logic [31:0] trace_buf [0:TRACE_DEPTH-1][0:N_SIGNALS-1];

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      wr_ptr <= 6'd0;
      sample_valid <= 1'b0;
      shadow[0] <= 32'd0;
      shadow[1] <= 32'd0;
    end else begin
      sample_valid <= 1'b1;
      shadow[0] <= sensor_in[0];
      trace_buf[wr_ptr][0] <= sensor_in[0];
      shadow[1] <= sensor_in[1];
      trace_buf[wr_ptr][1] <= sensor_in[1];
      wr_ptr <= (32'(wr_ptr) == TRACE_DEPTH-1) ? 6'd0 : wr_ptr + 1;
    end
  end

endmodule

// --- Analyze (A) -------------------------------------------
module mirr_analyze #(
  parameter N_SIGNALS    = 2,
  parameter N_PROPERTIES = 4
) (
  input  logic clk,
  input  logic rst_n,
  input  logic [N_SIGNALS-1:0][31:0] shadow,
  input  logic        sample_valid,
  output logic [3:0] violation_vec,
  output logic [1:0] top_violation_idx
);

  // Property 0: Always
  always_comb begin
    violation_vec[0] = sample_valid && !((shadow[0] > 32'd10));
  end

  // Property 1: Always
  always_comb begin
    violation_vec[1] = sample_valid && !((shadow[1] < 32'd1));
  end

  // Property 2: AlwaysImplies
  always_comb begin
    violation_vec[2] = sample_valid && ((shadow[0] < 32'd50) && !((shadow[1] != 32'd0)));
  end

  // Property 3: AlwaysFollowedBy(5)
  logic [3:0] follow_cnt_3;
  logic follow_ok_3;
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      follow_cnt_3 <= 4'd0;
      follow_ok_3  <= 1'b1;
    end else begin
      if ((shadow[0] < 32'd50)) begin
        follow_cnt_3 <= 4'd5;
        follow_ok_{pi} <= 1'b0;
      end else if (follow_cnt_{pi} > 0) begin
        follow_cnt_3 <= follow_cnt_3 - 1;
        if (follow_cnt_3 == 1 && !((shadow[1] != 32'd0))) follow_ok_3 <= 1'b0;
        else if (follow_cnt_{pi} == 1) follow_ok_{pi} <= 1'b1;
      end
    end
  end
  always_comb begin
    violation_vec[3] = sample_valid && !follow_ok_3;
  end

  // Priority encoder — lowest index wins
  always_comb begin
    top_violation_idx = 2'd0;
    if (violation_vec[3]) top_violation_idx = 2'd3;
    if (violation_vec[2]) top_violation_idx = 2'd2;
    if (violation_vec[1]) top_violation_idx = 2'd1;
    if (violation_vec[0]) top_violation_idx = 2'd0;
  end

endmodule

// --- Plan (P) ----------------------------------------------
module mirr_plan #(
  parameter N_PROPERTIES = 4,
  parameter N_ACTIONS    = 4
) (
  input  logic clk,
  input  logic rst_n,
  input  logic [3:0] violation_vec,
  output logic [1:0] selected_action_idx,
  output logic        action_valid
);

  logic [7:0] best_priority;
  logic [1:0] best_idx;
  logic        found;

  always_comb begin
    best_priority = 8'd0;
    best_idx      = 2'd0;
    found         = 1'b0;

    // action[0]: prop=0 pri=200
    if (violation_vec[0] && (8'd200 > best_priority || !found)) begin
      best_priority = 8'd200;
      best_idx      = 2'd0;
      found         = 1'b1;
    end
    // action[1]: prop=1 pri=200
    if (violation_vec[1] && (8'd200 > best_priority || !found)) begin
      best_priority = 8'd200;
      best_idx      = 2'd1;
      found         = 1'b1;
    end
    // action[2]: prop=2 pri=100
    if (violation_vec[2] && (8'd100 > best_priority || !found)) begin
      best_priority = 8'd100;
      best_idx      = 2'd2;
      found         = 1'b1;
    end
    // action[3]: prop=3 pri=64
    if (violation_vec[3] && (8'd64 > best_priority || !found)) begin
      best_priority = 8'd64;
      best_idx      = 2'd3;
      found         = 1'b1;
    end
  end

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      selected_action_idx <= 2'd0;
      action_valid        <= 1'b0;
    end else begin
      selected_action_idx <= best_idx;
      action_valid        <= found;
    end
  end

endmodule

// --- Execute (E) -------------------------------------------
module mirr_execute #(
  parameter N_SIGNALS = 2,
  parameter N_ACTIONS = 4
) (
  input  logic clk,
  input  logic rst_n,
  input  logic [1:0] selected_action_idx,
  input  logic        action_valid,
  output logic [N_SIGNALS-1:0][31:0] signal_override,
  output logic [N_SIGNALS-1:0]       override_en,
  output logic        emergency_active
);

  // Emergency latch (sticky)
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n)
      emergency_active <= 1'b0;
    else if (action_valid)
      case (selected_action_idx)
        2'd0: emergency_active <= 1'b1;
        2'd1: emergency_active <= 1'b1;
        default: ; // no change
      endcase
  end

  // Action dispatch
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      signal_override[0] <= 32'd0;
      override_en[0]     <= 1'b0;
      signal_override[1] <= 32'd0;
      override_en[1]     <= 1'b0;
    end else if (action_valid) begin
      case (selected_action_idx)
        2'd0: begin
          signal_override[0] <= 32'd0;
          override_en[0]     <= 1'b1;
          signal_override[1] <= 32'd0;
          override_en[1]     <= 1'b1;
        end
        2'd1: begin
          signal_override[0] <= 32'd0;
          override_en[0]     <= 1'b1;
          signal_override[1] <= 32'd0;
          override_en[1]     <= 1'b1;
        end
        2'd2: begin
          ; // no action (logging / reduce semantics)
        end
        2'd3: begin
          ; // no action (logging / reduce semantics)
        end
        default: ; // no action
      endcase
    end
  end

endmodule

// --- Knowledge (K) -----------------------------------------
module mirr_knowledge #(
  parameter DEPTH = 256
) (
  input  logic clk,
  input  logic rst_n,
  input  logic        wr_en,
  input  logic [1:0] wr_action_idx,
  input  logic [31:0] wr_tick,
  output logic [8:0] count,
  output logic        full
);

  logic [33:0] fifo [0:DEPTH-1];
  logic [7:0] wr_ptr;

  assign full = (count == DEPTH);

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      wr_ptr <= 8'd0;
      count  <= 9'd0;
    end else if (wr_en && !full) begin
      fifo[wr_ptr] <= {wr_tick, wr_action_idx};
      wr_ptr <= (32'(wr_ptr) == DEPTH-1) ? 8'd0 : wr_ptr + 1;
      count  <= count + 1;
    end
  end

endmodule

// --- MAPE-K Top -------------------------------------------
module mirr_mape_k_top #(
  parameter N_SIGNALS    = 2,
  parameter N_PROPERTIES = 4,
  parameter N_ACTIONS    = 4,
  parameter K_DEPTH      = 256
) (
  input  logic clk,
  input  logic rst_n,
  input  logic [N_SIGNALS-1:0][31:0] sensor_in,
  output logic        emergency_active,
  output logic [N_SIGNALS-1:0][31:0] signal_override,
  output logic [N_SIGNALS-1:0]       override_en
);

  // Monitor -> Analyze
  logic [N_SIGNALS-1:0][31:0] shadow;
  logic        sample_valid;

  // Analyze -> Plan
  logic [3:0] violation_vec;
  logic [1:0] top_violation_idx;

  // Plan -> Execute
  logic [1:0] selected_action_idx;
  logic        action_valid;

  // Knowledge write channel
  logic [8:0] k_count;
  logic        k_full;
  logic [31:0] tick_counter;

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n)
      tick_counter <= 32'd0;
    else
      tick_counter <= tick_counter + 1;
  end

  mirr_monitor #(
    .N_SIGNALS   (N_SIGNALS),
    .TRACE_DEPTH (64)
  ) u_monitor (
    .clk          (clk),
    .rst_n        (rst_n),
    .sensor_in    (sensor_in),
    .shadow       (shadow),
    .sample_valid (sample_valid)
  );

  mirr_analyze #(
    .N_SIGNALS    (N_SIGNALS),
    .N_PROPERTIES (N_PROPERTIES)
  ) u_analyze (
    .clk               (clk),
    .rst_n             (rst_n),
    .shadow            (shadow),
    .sample_valid      (sample_valid),
    .violation_vec     (violation_vec),
    .top_violation_idx (top_violation_idx)
  );

  mirr_plan #(
    .N_PROPERTIES (N_PROPERTIES),
    .N_ACTIONS    (N_ACTIONS)
  ) u_plan (
    .clk                (clk),
    .rst_n              (rst_n),
    .violation_vec      (violation_vec),
    .selected_action_idx(selected_action_idx),
    .action_valid       (action_valid)
  );

  mirr_execute #(
    .N_SIGNALS (N_SIGNALS),
    .N_ACTIONS (N_ACTIONS)
  ) u_execute (
    .clk                (clk),
    .rst_n              (rst_n),
    .selected_action_idx(selected_action_idx),
    .action_valid       (action_valid),
    .signal_override    (signal_override),
    .override_en        (override_en),
    .emergency_active   (emergency_active)
  );

  mirr_knowledge #(
    .DEPTH (K_DEPTH)
  ) u_knowledge (
    .clk           (clk),
    .rst_n         (rst_n),
    .wr_en         (action_valid),
    .wr_action_idx (selected_action_idx),
    .wr_tick       (tick_counter),
    .count         (k_count),
    .full          (k_full)
  );

endmodule
