//! ARM Thumb-2 assembly emission backend.
//!
//! Translates an R-SPU program (from `rspu.rs`) into ARM Thumb-2 assembly text.
//! Uses IT blocks for conditional execution — no backward branches.
//! Bounded execution via BKPT watchdog at program end.

#![forbid(unsafe_code)]

use std::fmt::Write;
use super::rspu::rspu_err;
use super::rspu_isa::*;
use crate::error::MirrError;

/// Memory-mapped I/O base address for ARM Cortex-M.
const MMIO_BASE: u32 = 0x4000_0000;

/// Emit ARM Thumb-2 assembly from an R-SPU program.
///
/// Returns a complete `.S` file with `.text` and `.data` sections.
pub fn emit_arm_asm(program: &RspuProgram) -> Result<String, MirrError> {
    let mut out = String::with_capacity(program.instructions.len() * 80);
    let mut label_counter: u32 = 0;

    // Header
    out.push_str("@ ARM Thumb-2 Assembly — generated by MIRR compiler\n");
    writeln!(out, "@ Registers used: {}", program.registers_used).unwrap();
    writeln!(out, "@ Guards used:    {}", program.guards_used).unwrap();
    writeln!(out, "@ Instructions:   {}", program.instructions.len()).unwrap();
    out.push_str("@\n@ Register map:\n");

    for (name, _reg) in &program.register_map {
        writeln!(out, "@   R{} = {}", _reg, name).unwrap();
    }
    out.push_str("@\n@ Guard map:\n");
    for (name, gid) in &program.guard_map {
        writeln!(out, "@   G{} = {}", gid, name).unwrap();
    }
    out.push('\n');

    // Directives
    out.push_str(".syntax unified\n");
    out.push_str(".thumb\n");
    out.push_str(".section .text\n");
    out.push_str(".globl _start\n");
    out.push_str(".type _start, %function\n\n");
    out.push_str("_start:\n");

    // Emit instructions
    for (i, instr) in program.instructions.iter().enumerate() {
        write!(out, "\ninstr_{}:\n", i).unwrap();
        emit_arm_instruction(&mut out, instr, &mut label_counter)?;
    }

    // HALT at end (safety guarantee)
    out.push_str("\ninstr_halt:\n");
    out.push_str("    bkpt #0\n");

    // Data section
    out.push_str("\n.section .data\n");
    for (name, _reg) in &program.register_map {
        writeln!(out, "signal_{}: .word 0", name).unwrap();
    }
    for (name, _) in &program.guard_map {
        writeln!(out, "guard_{}: .word 0", name).unwrap();
    }
    for (name, _) in &program.guard_map {
        writeln!(out, "sr_{}: .space 1024", name).unwrap();
    }

    Ok(out)
}

/// Emit a single ARM instruction.
fn emit_arm_instruction(
    out: &mut String,
    instr: &RspuInstruction,
    label_counter: &mut u32,
) -> Result<(), MirrError> {
    match instr {
        RspuInstruction::TagBranch { tag_value, target_pc } => {
            writeln!(out, "    @ TAG_BRANCH {}, {}", tag_value, target_pc).unwrap();
        }
        // Register tier
        RspuInstruction::LoadInput { dst, port } => {
            let addr = MMIO_BASE + (*port as u32) * 4;
            writeln!(out, "    ldr r{}, =0x{:08X}", dst, addr).unwrap();
            writeln!(out, "    ldr r{}, [r{}]", dst, dst).unwrap();
        }
        RspuInstruction::StoreOutput { src, port } => {
            let addr = MMIO_BASE + (*port as u32) * 4;
            writeln!(out, "    ldr r12, =0x{:08X}", addr).unwrap();
            writeln!(out, "    str r{}, [r12]", src).unwrap();
        }
        RspuInstruction::Mov { dst, src } => {
            writeln!(out, "    mov r{}, r{}", dst, src).unwrap();
        }
        RspuInstruction::LoadImm { dst, value, .. } => {
            if *value <= 255 {
                writeln!(out, "    mov r{}, #{}", dst, value).unwrap();
            } else {
                writeln!(out, "    ldr r{}, ={}", dst, value).unwrap();
            }
        }

        // ALU tier
        RspuInstruction::Alu { op, dst, a, b } => {
            // ARM target still uses 8-bit registers in this model.
            let d8 = (*dst)
                .try_into()
                .map_err(|_| rspu_err("ARM target only supports registers R0-R255"))?;
            let a8 = (*a)
                .try_into()
                .map_err(|_| rspu_err("ARM target only supports registers R0-R255"))?;
            let b8 = (*b)
                .try_into()
                .map_err(|_| rspu_err("ARM target only supports registers R0-R255"))?;
            emit_arm_alu(out, *op, d8, a8, b8);
        }
        RspuInstruction::AluImm { op, dst, a, imm } => {
            let d8 = (*dst)
                .try_into()
                .map_err(|_| rspu_err("ARM target only supports registers R0-R255"))?;
            let a8 = (*a)
                .try_into()
                .map_err(|_| rspu_err("ARM target only supports registers R0-R255"))?;
            emit_arm_alu_imm(out, *op, d8, a8, *imm);
        }
        RspuInstruction::AluUnary { op, dst, src } => match op {
            AluUnaryOp::Not => writeln!(out, "    mvn r{}, r{}", dst, src).unwrap(),
            AluUnaryOp::Negate => writeln!(out, "    neg r{}, r{}", dst, src).unwrap(),
            AluUnaryOp::ReductionOr => {
                writeln!(out, "    cmp r{}, #0", src).unwrap();
                writeln!(out, "    movne r{}, #1", dst).unwrap();
                writeln!(out, "    moveq r{}, #0", dst).unwrap();
            }
        },

        // Temporal tier — shift register emulation
        RspuInstruction::SrInit { guard, length, cond } => {
            // Store condition value to guard state.
            writeln!(out, "    ldr r12, =guard_g{}", guard).unwrap();
            writeln!(out, "    str r{}, [r12]", cond).unwrap();
            // Zero-fill shift register chain for `length` stages.
            writeln!(out, "    ldr r12, =sr_g{}", guard).unwrap();
            out.push_str("    mov r11, #0\n");
            let stages = (*length).min(256);
            for s in 0..stages {
                writeln!(out, "    str r11, [r12, #{}]", s * 4).unwrap();
            }
        }
        RspuInstruction::SrTick { guard } => {
            // Shift register chain: stage[i+1] = stage[i], stage[0] = guard state.
            // Shift all stages down by one position (bounded by 256 stages).
            *label_counter += 1;
            let shift_label = *label_counter;
            writeln!(out, "    ldr r12, =sr_g{}", guard).unwrap();
            writeln!(out, "    ldr r11, =guard_g{}", guard).unwrap();
            out.push_str("    ldr r10, [r11]\n"); // new value from guard state
                                                  // Shift stages 1..N ← 0..N-1 (reverse order to avoid overwrite)
            out.push_str("    mov r9, #256\n"); // max stages
            writeln!(out, "shift_loop_arm_{}:", shift_label).unwrap();
            out.push_str("    sub r9, r9, #1\n");
            out.push_str("    cmp r9, #0\n");
            writeln!(out, "    beq shift_done_arm_{}", shift_label).unwrap();
            out.push_str("    lsl r8, r9, #2\n"); // offset = i * 4
            out.push_str("    sub r7, r8, #4\n"); // prev offset = (i-1) * 4
            out.push_str("    ldr r6, [r12, r7]\n");
            out.push_str("    str r6, [r12, r8]\n");
            writeln!(out, "    b shift_loop_arm_{}", shift_label).unwrap();
            writeln!(out, "shift_done_arm_{}:", shift_label).unwrap();
            // Store new value at stage 0
            out.push_str("    str r10, [r12]\n");
        }
        RspuInstruction::SrQuery { dst, guard } => {
            writeln!(out, "    ldr r12, =guard_g{}", guard).unwrap();
            writeln!(out, "    ldr r{}, [r12]", dst).unwrap();
            writeln!(out, "    and r{}, r{}, #1", dst, dst).unwrap();
        }

        // Temporal tier — counter
        RspuInstruction::CtrInit { guard, target, cond: _ } => {
            writeln!(out, "    ldr r12, =guard_g{}", guard).unwrap();
            writeln!(out, "    ldr r11, ={}", target).unwrap();
            out.push_str("    str r11, [r12]\n");
        }
        RspuInstruction::CtrTick { guard } => {
            writeln!(out, "    ldr r12, =guard_g{}", guard).unwrap();
            out.push_str("    ldr r11, [r12]\n");
            out.push_str("    sub r11, r11, #1\n");
            out.push_str("    str r11, [r12]\n");
        }
        RspuInstruction::CtrQuery { dst, guard } => {
            writeln!(out, "    ldr r12, =guard_g{}", guard).unwrap();
            writeln!(out, "    ldr r{}, [r12]", dst).unwrap();
            writeln!(out, "    cmp r{}, #0", dst).unwrap();
            writeln!(out, "    mov r{}, #0", dst).unwrap();
            out.push_str("    it lt\n");
            writeln!(out, "    movlt r{}, #1", dst).unwrap();
        }

        // Guard combination
        RspuInstruction::GuardAnd { dst, a, b } => {
            writeln!(out, "    ldr r12, =guard_g{}", a).unwrap();
            out.push_str("    ldr r11, [r12]\n");
            writeln!(out, "    ldr r12, =guard_g{}", b).unwrap();
            out.push_str("    ldr r10, [r12]\n");
            out.push_str("    and r11, r11, r10\n");
            writeln!(out, "    ldr r12, =guard_g{}", dst).unwrap();
            out.push_str("    str r11, [r12]\n");
        }
        RspuInstruction::GuardOr { dst, a, b } => {
            writeln!(out, "    ldr r12, =guard_g{}", a).unwrap();
            out.push_str("    ldr r11, [r12]\n");
            writeln!(out, "    ldr r12, =guard_g{}", b).unwrap();
            out.push_str("    ldr r10, [r12]\n");
            out.push_str("    orr r11, r11, r10\n");
            writeln!(out, "    ldr r12, =guard_g{}", dst).unwrap();
            out.push_str("    str r11, [r12]\n");
        }

        // Reflex tier
        RspuInstruction::ReflexIf { guard, dst, src } => {
            writeln!(out, "    ldr r12, =guard_g{}", guard).unwrap();
            out.push_str("    ldr r11, [r12]\n");
            out.push_str("    cmp r11, #0\n");
            out.push_str("    it ne\n");
            writeln!(out, "    movne r{}, r{}", dst, src).unwrap();
        }
        RspuInstruction::Prev { dst, signal, delay: _ } => {
            // Prev reads a signal's value from N cycles ago.
            // Full implementation requires per-signal shift registers.
            // Current: pass-through (safe over-approximation — uses current value).
            writeln!(out, "    mov r{}, r{}", dst, signal).unwrap();
        }

        // Safety tier
        RspuInstruction::EmergencyStop => {
            out.push_str("    bkpt #0xFF\n");
        }

        // LTL assertion tier
        RspuInstruction::AssertAlways { cond, property_id } => {
            *label_counter += 1;
            let label = *label_counter;
            writeln!(out, "    cmp r{}, #0", cond).unwrap();
            writeln!(out, "    bne assert_pass_{}", label).unwrap();
            writeln!(out, "    bkpt #{}", 200 + property_id).unwrap();
            writeln!(out, "assert_pass_{}:", label).unwrap();
        }
        RspuInstruction::AssertNever { cond, property_id } => {
            *label_counter += 1;
            let label = *label_counter;
            writeln!(out, "    cmp r{}, #0", cond).unwrap();
            writeln!(out, "    beq assert_pass_{}", label).unwrap();
            writeln!(out, "    bkpt #{}", 300 + property_id).unwrap();
            writeln!(out, "assert_pass_{}:", label).unwrap();
        }

        // Exception tier
        RspuInstruction::Trap { code } => {
            writeln!(out, "    bkpt #{}", code).unwrap();
        }
        RspuInstruction::TrapIf { cond, code } => {
            *label_counter += 1;
            let label = *label_counter;
            writeln!(out, "    cmp r{}, #0", cond).unwrap();
            writeln!(out, "    beq skip_trap_{}", label).unwrap();
            writeln!(out, "    bkpt #{}", code).unwrap();
            writeln!(out, "skip_trap_{}:", label).unwrap();
        }
        RspuInstruction::Halt => {
            out.push_str("    bkpt #0\n");
        }

        // Control tier
        RspuInstruction::ModeSwitch { mode } => {
            writeln!(out, "    @ MODE_SWITCH {}", mode).unwrap();
        }
        RspuInstruction::Nop => {
            out.push_str("    nop\n");
        }
        RspuInstruction::Fence => {
            out.push_str("    dmb\n");
        }

        // Tagged tier
        RspuInstruction::TagLoad { dst, tag } => {
            writeln!(out, "    mov r{}, #{}", dst, tag).unwrap();
        }
        RspuInstruction::TagCheck { src, expected } => {
            *label_counter += 1;
            let label = *label_counter;
            writeln!(out, "    cmp r{}, #{}", src, expected).unwrap();
            writeln!(out, "    beq tag_ok_{}", label).unwrap();
            out.push_str("    bkpt #708\n");
            writeln!(out, "tag_ok_{}:", label).unwrap();
        }
        RspuInstruction::TagRead { dst, src } => {
            writeln!(out, "    mov r{}, r{}", dst, src).unwrap();
        }

        // Deadline
        RspuInstruction::DeadlineSet { cycles } => {
            writeln!(out, "    @ DEADLINE_SET {}", cycles).unwrap();
        }

        // Totality engine tier
        RspuInstruction::Verify { cert_offset } => {
            writeln!(out, "    @ VERIFY offset={}", cert_offset).unwrap();
        }
        RspuInstruction::Certify { dst } => {
            writeln!(out, "    mov r{}, #1", dst).unwrap();
        }
        RspuInstruction::TotalCheck { expected_properties } => {
            writeln!(out, "    @ TOTAL_CHECK {}", expected_properties).unwrap();
        }

        // Symbolic tier
        RspuInstruction::Match { dst, src, table_offset } => {
            writeln!(out, "    @ MATCH r{}, r{}, table=#{}", dst, src, table_offset).unwrap();
            writeln!(out, "    mov r{}, r{}", dst, src).unwrap();
        }
        RspuInstruction::IntervalLo { dst, src } => {
            writeln!(out, "    mov r{}, r{}", dst, src).unwrap();
        }
        RspuInstruction::IntervalHi { dst, src } => {
            writeln!(out, "    mov r{}, r{}", dst, src).unwrap();
        }
        RspuInstruction::IntervalCheck { src, bounds } => {
            writeln!(out, "    @ INTERVAL_CHECK r{}, r{}", src, bounds).unwrap();
        }
    }
    Ok(())
}

/// Emit ARM ALU operation.
fn emit_arm_alu(out: &mut String, op: AluOp, dst: u8, a: u8, b: u8) {
    match op {
        AluOp::Add => writeln!(out, "    add r{}, r{}, r{}", dst, a, b).unwrap(),
        AluOp::Sub => writeln!(out, "    sub r{}, r{}, r{}", dst, a, b).unwrap(),
        AluOp::Mul => writeln!(out, "    mul r{}, r{}, r{}", dst, a, b).unwrap(),
        AluOp::And => writeln!(out, "    and r{}, r{}, r{}", dst, a, b).unwrap(),
        AluOp::Or => writeln!(out, "    orr r{}, r{}, r{}", dst, a, b).unwrap(),
        AluOp::Xor => writeln!(out, "    eor r{}, r{}, r{}", dst, a, b).unwrap(),
        AluOp::Shl => writeln!(out, "    lsl r{}, r{}, r{}", dst, a, b).unwrap(),
        AluOp::Shr => writeln!(out, "    lsr r{}, r{}, r{}", dst, a, b).unwrap(),
        AluOp::Eq => {
            writeln!(out, "    cmp r{}, r{}", a, b).unwrap();
            writeln!(out, "    mov r{}, #0", dst).unwrap();
            out.push_str("    it eq\n");
            writeln!(out, "    moveq r{}, #1", dst).unwrap();
        }
        AluOp::Ne => {
            writeln!(out, "    cmp r{}, r{}", a, b).unwrap();
            writeln!(out, "    mov r{}, #0", dst).unwrap();
            out.push_str("    it ne\n");
            writeln!(out, "    movne r{}, #1", dst).unwrap();
        }
        AluOp::Lt => {
            writeln!(out, "    cmp r{}, r{}", a, b).unwrap();
            writeln!(out, "    mov r{}, #0", dst).unwrap();
            out.push_str("    it lt\n");
            writeln!(out, "    movlt r{}, #1", dst).unwrap();
        }
        AluOp::Gt => {
            writeln!(out, "    cmp r{}, r{}", a, b).unwrap();
            writeln!(out, "    mov r{}, #0", dst).unwrap();
            out.push_str("    it gt\n");
            writeln!(out, "    movgt r{}, #1", dst).unwrap();
        }
        AluOp::Le => {
            writeln!(out, "    cmp r{}, r{}", a, b).unwrap();
            writeln!(out, "    mov r{}, #0", dst).unwrap();
            out.push_str("    it le\n");
            writeln!(out, "    movle r{}, #1", dst).unwrap();
        }
        AluOp::Ge => {
            writeln!(out, "    cmp r{}, r{}", a, b).unwrap();
            writeln!(out, "    mov r{}, #0", dst).unwrap();
            out.push_str("    it ge\n");
            writeln!(out, "    movge r{}, #1", dst).unwrap();
        }
    }
}

/// Emit ARM ALU with immediate.
fn emit_arm_alu_imm(out: &mut String, op: AluOp, dst: u8, a: u8, imm: u64) {
    match op {
        AluOp::Add => writeln!(out, "    add r{}, r{}, #{}", dst, a, imm).unwrap(),
        AluOp::Sub => writeln!(out, "    sub r{}, r{}, #{}", dst, a, imm).unwrap(),
        AluOp::And => writeln!(out, "    and r{}, r{}, #{}", dst, a, imm).unwrap(),
        AluOp::Or => writeln!(out, "    orr r{}, r{}, #{}", dst, a, imm).unwrap(),
        AluOp::Xor => writeln!(out, "    eor r{}, r{}, #{}", dst, a, imm).unwrap(),
        AluOp::Shl => writeln!(out, "    lsl r{}, r{}, #{}", dst, a, imm & 31).unwrap(),
        AluOp::Shr => writeln!(out, "    lsr r{}, r{}, #{}", dst, a, imm & 31).unwrap(),
        _ => {
            writeln!(out, "    ldr r11, ={}", imm).unwrap();
            emit_arm_alu(out, op, dst, a, 11);
        }
    }
}
