//! FIRRTL emitter for MIRR IR.
//!
//! Produces FIRRTL (Flexible Intermediate Representation for RTL) output
//! from the compiled pipeline result. FIRRTL is the intermediate language
//! used by the CHIPS Alliance / CIRCT ecosystem.
//!
//! Mapping notes:
//! - Signals → FIRRTL `input`/`output`/`wire` declarations
//! - Guards → shift-register or counter hardware (from temporal netlist)
//! - Reflexes → conditional `connect` statements under `when` blocks
//! - Properties → FIRRTL `assert` intrinsics (limited; SVA has no FIRRTL
//!   equivalent, so properties emit as verification comments)
//!
//! Width mapping: `bool` → `UInt<1>`, `uN` → `UInt<N>`.

#![forbid(unsafe_code)]

use std::fmt::Write;
use crate::ast::types::{BinaryOp, LiteralValue, SignalKind, SignalType, UnaryOp};
use crate::ast::MAX_EXPR_NODES;
use crate::pipeline::PipelineResult;
use crate::temporal::low_level_ir::{CompiledGuard, TemporalNetlist};

use crate::error::MirrError;
use crate::error_codes::{mirrcode, ErrorCode};

/// Emit FIRRTL from pipeline results.
pub fn emit_firrtl(result: &PipelineResult) -> Result<String, MirrError> {
    let mut out = String::with_capacity(4096);
    let registry = result.ecs_registry.as_ref().ok_or_else(|| {
        mirrcode(ErrorCode::RspuFallback, "ECS registry must be populated for FIRRTL emission")
    })?;
    let circuit_name = registry.get_module_name().unwrap_or_else(|| "unknown_circuit".to_string());

    emit_header(&mut out);
    out.push_str("circuit ");
    out.push_str(&circuit_name);
    out.push_str(" :\n");

    for i in 0..registry.names.len() {
        if let (Some(nc), Some(kc)) = (&registry.names[i], &registry.kinds[i]) {
            if let crate::ecs::components::EntityKind::MODULE = kc.0 {
                let mod_name = registry.resolve_name(nc.0);
                emit_module(
                    mod_name,
                    crate::ecs::components::EntityId(i as u32),
                    registry,
                    result.temporal_netlist.as_ref(),
                    &mut out,
                );
            }
        }
    }

    Ok(out)
}

// -----------------------------------------------------------------------
// Internal helpers
// -----------------------------------------------------------------------

fn emit_header(out: &mut String) {
    out.push_str("; Auto-generated by MIRR compiler\n");
    out.push_str("; Do not edit — regenerate from .mirr source.\n");
    out.push_str("; Target: FIRRTL\n");
    out.push_str("FIRRTL version 1.1.0\n");
}

fn emit_module(
    module_name: &str,
    mod_id: crate::ecs::components::EntityId,
    registry: &crate::ecs::Registry,
    temporal_netlist: Option<&TemporalNetlist>,
    out: &mut String,
) {
    out.push_str("  module ");
    out.push_str(module_name);
    out.push_str(" :\n");

    let mut has_clk = false;
    let mut has_rst_n = false;
    for i in 0..registry.names.len() {
        if registry.modules[i].map(|m| m.0) != Some(mod_id) {
            continue;
        }
        if let (Some(nc), Some(kc)) = (&registry.names[i], &registry.kinds[i]) {
            if let crate::ecs::components::EntityKind::SIGNAL(
                crate::ast::types::SignalKind::Input,
            ) = kc.0
            {
                let name = registry.resolve_name(nc.0);
                if name == "clk" {
                    has_clk = true;
                }
                if name == "rst_n" {
                    has_rst_n = true;
                }
            }
        }
    }

    if temporal_netlist.is_some() {
        if !has_clk {
            out.push_str("    input clk : Clock\n");
        }
        if !has_rst_n {
            out.push_str("    input rst_n : UInt<1>\n");
        }
    }

    emit_ports(mod_id, registry, out);
    emit_internal_wires(mod_id, registry, out);
    out.push('\n');

    if let Some(netlist) = temporal_netlist {
        emit_temporal_logic(mod_id, registry, netlist, out);
    }

    emit_reflex_logic(mod_id, registry, out);
    emit_property_comments(mod_id, registry, out);
}

fn emit_ports(
    mod_id: crate::ecs::components::EntityId,
    registry: &crate::ecs::Registry,
    out: &mut String,
) {
    for i in 0..registry.names.len() {
        if registry.modules[i].map(|m| m.0) != Some(mod_id) {
            continue;
        }
        if let (Some(nc), Some(kind_comp), Some(ty_comp)) =
            (registry.names[i], &registry.kinds[i], &registry.types[i])
        {
            if let crate::ecs::EntityKind::SIGNAL(sig_kind) = kind_comp.0 {
                let dir = match sig_kind {
                    SignalKind::Input => "input",
                    SignalKind::Output => "output",
                    SignalKind::Internal => continue, // handled as wires
                };
                let name = registry.resolve_name(nc.0);

                // If it's an explicit clock domain port, emit as Clock instead of UInt<1>
                let mut is_clock = false;
                if name == "clk" {
                    is_clock = true;
                } else {
                    for j in 0..registry.types.len() {
                        if registry.modules[j].map(|m| m.0) != Some(mod_id) {
                            continue;
                        }
                        if let Some(t) = &registry.types[j] {
                            if t.0.annotations.clock_domain.as_deref() == Some(name) {
                                is_clock = true;
                                break;
                            }
                        }
                    }
                }

                let ty = if is_clock { "Clock".to_string() } else { firrtl_type(&ty_comp.0.core) };
                writeln!(out, "    {} {} : {}", dir, name, ty).unwrap();
            }
        }
    }
}

fn emit_internal_wires(
    mod_id: crate::ecs::components::EntityId,
    registry: &crate::ecs::Registry,
    out: &mut String,
) {
    let mut has_internals = false;
    for i in 0..registry.names.len() {
        if registry.modules[i].map(|m| m.0) != Some(mod_id) {
            continue;
        }
        if let (Some(nc), Some(kind_comp), Some(ty_comp)) =
            (registry.names[i], &registry.kinds[i], &registry.types[i])
        {
            if let crate::ecs::EntityKind::SIGNAL(SignalKind::Internal) = kind_comp.0 {
                if !has_internals {
                    out.push_str("\n    ; Internal signals\n");
                    has_internals = true;
                }
                let ty = firrtl_type(&ty_comp.0.core);
                writeln!(out, "    wire {} : {}", registry.resolve_name(nc.0), ty).unwrap();
            }
        }
    }
}

fn emit_temporal_logic(
    mod_id: crate::ecs::components::EntityId,
    registry: &crate::ecs::Registry,
    netlist: &TemporalNetlist,
    out: &mut String,
) {
    out.push_str("\n    ; ── Temporal Guards ──\n");

    for guard in &netlist.guards {
        let output_signal = match guard {
            CompiledGuard::ShiftRegister(sr) => &sr.output_signal,
            CompiledGuard::Counter(cg) => &cg.output_signal,
            CompiledGuard::Complex(cx) => &cx.output_signal,
            CompiledGuard::DynamicCounter(dc) => &dc.output_signal,
        };

        let mut clock_domain = "clk";
        let mod_name = registry.resolve_name(registry.names[mod_id.0 as usize].unwrap().0);
        let scoped_name = format!("{}::{}", mod_name, output_signal);
        let resolved_id = registry
            .get_entity_by_name(&scoped_name)
            .or_else(|| registry.get_entity_by_name(output_signal));
        if let Some(id) = resolved_id {
            if let Some(tc) = &registry.types[id.0 as usize] {
                if let Some(cd) = tc.0.annotations.clock_domain.as_deref() {
                    clock_domain = cd;
                }
            }
        }

        match guard {
            CompiledGuard::ShiftRegister(sr) => {
                emit_shift_register_firrtl(sr, clock_domain, out);
            }
            CompiledGuard::Counter(cg) => {
                emit_counter_firrtl(cg, clock_domain, out);
            }
            CompiledGuard::Complex(cx) => {
                write!(out, 
                    "\n    ; Complex guard: {} (sub-guards combined)\n",
                    cx.name
                ).unwrap();
                let ty = "UInt<1>";
                writeln!(out, "    wire {} : {}", cx.output_signal, ty).unwrap();
                let expr = emit_logic_expr_firrtl(&cx.combination_logic);
                writeln!(out, "    connect {} , {}", cx.output_signal, expr).unwrap();
            }
            CompiledGuard::DynamicCounter(dc) => {
                write!(out, 
                    "\n    ; Dynamic counter guard: {} (max {} cycles)\n",
                    dc.name, dc.max_delay
                ).unwrap();
                let width = dc.counter_width();
                writeln!(out, 
                    "    reg {} : UInt<{}>, {}",
                    dc.counter_signal, width, clock_domain
                ).unwrap();
                writeln!(out, "    wire {} : UInt<1>", dc.output_signal).unwrap();
            }
        }
    }
}

fn emit_shift_register_firrtl(
    sr: &crate::temporal::low_level_ir::ShiftRegisterGuard,
    clock_domain: &str,
    out: &mut String,
) {
    let stage_count = sr.delay_cycles.min(super::verilog::MAX_SR_STAGES_INLINE);
    let cond = emit_condition_firrtl(&sr.condition_kind);

    write!(out, 
        "\n    ; Guard: {} — {} for {} cycles\n",
        sr.name,
        sr.condition_kind.describe(),
        sr.delay_cycles,
    ).unwrap();

    // Shift register as a vector of 1-bit registers.
    writeln!(out, 
        "    reg {}_sr : UInt<{}> , {} with : (reset => (not(rst_n), UInt(0)))",
        sr.name, stage_count, clock_domain,
    ).unwrap();

    // Condition wire.
    writeln!(out, "    wire {}_cond : UInt<1>", sr.name).unwrap();
    writeln!(out, "    connect {}_cond , {}", sr.name, cond).unwrap();

    // Shift operation: sr <= cat(cond, sr[high:1]).
    writeln!(out, "    connect {0}_sr , cat({0}_cond, shr({0}_sr, 1))", sr.name,).unwrap();

    // Output: guard fires when all bits are 1.
    writeln!(out, "    wire {} : UInt<1>", sr.output_signal).unwrap();
    writeln!(out, "    connect {} , andr({}_sr)", sr.output_signal, sr.name,).unwrap();
}

fn emit_counter_firrtl(
    cg: &crate::temporal::low_level_ir::CounterGuard,
    clock_domain: &str,
    out: &mut String,
) {
    let width = cg.counter_width();
    let cond = emit_condition_firrtl(&cg.condition_kind);

    write!(out, 
        "\n    ; Guard: {} — {} for {} cycles (counter)\n",
        cg.name,
        cg.condition_kind.describe(),
        cg.target_count,
    ).unwrap();

    // Counter register.
    writeln!(out, 
        "    reg {} : UInt<{}> , {} with : (reset => (not(rst_n), UInt(0)))",
        cg.counter_signal, width, clock_domain,
    ).unwrap();

    // Condition wire.
    writeln!(out, "    wire {}_cond : UInt<1>", cg.name).unwrap();
    writeln!(out, "    connect {}_cond , {}", cg.name, cond).unwrap();

    // Counter logic.
    write!(out, 
        "    when not({0}_cond) :\n      connect {1} , UInt(0)\n",
        cg.name, cg.counter_signal,
    ).unwrap();
    write!(out, 
        "    else when lt({0}, UInt({1})) :\n      connect {0} , add({0}, UInt(1))\n",
        cg.counter_signal, cg.target_count,
    ).unwrap();

    // Output: guard fires when counter >= target.
    writeln!(out, "    wire {} : UInt<1>", cg.output_signal).unwrap();
    writeln!(out, 
        "    connect {} , geq({}, UInt({}))",
        cg.output_signal, cg.counter_signal, cg.target_count,
    ).unwrap();
}

fn emit_reflex_logic(
    mod_id: crate::ecs::components::EntityId,
    registry: &crate::ecs::Registry,
    out: &mut String,
) {
    let mut has_reflex = false;
    for i in 0..registry.kinds.len() {
        if registry.modules[i].map(|m| m.0) != Some(mod_id) {
            continue;
        }
        if let Some(crate::ecs::components::KindComponent(crate::ecs::EntityKind::REFLEX)) =
            &registry.kinds[i]
        {
            has_reflex = true;
            break;
        }
    }

    if !has_reflex {
        return;
    }

    out.push_str("\n    ; ── Reflex Assignments ──\n");

    for i in 0..registry.names.len() {
        if registry.modules[i].map(|m| m.0) != Some(mod_id) {
            continue;
        }
        if let (Some(nc), Some(kind_comp), Some(r)) =
            (registry.names[i], &registry.kinds[i], &registry.reflex_comps[i])
        {
            if let crate::ecs::EntityKind::REFLEX = kind_comp.0 {
                write!(out, "\n    ; Reflex: {}\n", registry.resolve_name(nc.0)).unwrap();

                let guard_cond = if r.guards.len() == 1 {
                    let g_nc_name = registry.names[r.guards[0].0 as usize]
                        .as_ref()
                        .map(|nc| registry.resolve_name(nc.0))
                        .unwrap_or("ERR_MISSING_NAME");
                    format!("{}_out", g_nc_name)
                } else if r.guards.is_empty() {
                    "UInt<1>(1)".to_string()
                } else {
                    let g_nc_name = registry.names[r.guards[0].0 as usize]
                        .as_ref()
                        .map(|nc| registry.resolve_name(nc.0))
                        .unwrap_or("ERR_MISSING_NAME");
                    let mut expr = format!("{}_out", g_nc_name);
                    let mut j = 1;
                    while j < r.guards.len() {
                        let g_nc_name = registry.names[r.guards[j].0 as usize]
                            .as_ref()
                            .map(|nc| registry.resolve_name(nc.0))
                            .unwrap_or("ERR_MISSING_NAME");
                        expr = format!("and({}, {}_out)", expr, g_nc_name);
                        j += 1;
                    }
                    expr
                };

                for a_id in &r.assignments {
                    if let Some(assign) = &registry.assignment_comps[a_id.0 as usize] {
                        let target_name = registry.names[assign.target.0 as usize]
                            .as_ref()
                            .map(|nc| registry.resolve_name(nc.0))
                            .unwrap_or("ERR_MISSING_NAME");
                        let val = emit_expr_inline_ecs(assign.value, registry);
                        write!(out, 
                            "    when {} :\n      connect {} , {}\n    else :\n      connect {} , UInt(0)\n",
                            guard_cond, target_name, val, target_name,
                        ).unwrap();
                    }
                }
            }
        }
    }
}

fn emit_property_comments(
    mod_id: crate::ecs::components::EntityId,
    registry: &crate::ecs::Registry,
    out: &mut String,
) {
    let mut has_props = false;
    for i in 0..registry.kinds.len() {
        if registry.modules[i].map(|m| m.0) != Some(mod_id) {
            continue;
        }
        if let Some(crate::ecs::components::KindComponent(crate::ecs::EntityKind::PROPERTY)) =
            &registry.kinds[i]
        {
            has_props = true;
            break;
        }
    }

    if !has_props {
        return;
    }

    out.push_str("\n    ; ── Verification Properties ──\n");
    for i in 0..registry.names.len() {
        if registry.modules[i].map(|m| m.0) != Some(mod_id) {
            continue;
        }
        if let (Some(nc), Some(kind_comp), Some(prop)) =
            (registry.names[i], &registry.kinds[i], &registry.property_comps[i])
        {
            if let crate::ecs::EntityKind::PROPERTY = kind_comp.0 {
                let get_expr = |idx| {
                    prop.formula_exprs
                        .get(idx)
                        .map(|&e| emit_expr_inline_ecs(e, registry))
                        .unwrap_or_else(|| "UInt<1>(1)".to_string())
                };

                let desc = match &prop.formula {
                    crate::ast::property::PropertyFormula::Always(_) => {
                        format!("always ({})", get_expr(0))
                    }
                    crate::ast::property::PropertyFormula::Never(_) => {
                        format!("never ({})", get_expr(0))
                    }
                    crate::ast::property::PropertyFormula::AlwaysImplies { .. } => {
                        format!("always ({} -> {})", get_expr(0), get_expr(1))
                    }
                    crate::ast::property::PropertyFormula::NeverImplies { .. } => {
                        format!("never ({} -> {})", get_expr(0), get_expr(1))
                    }
                    crate::ast::property::PropertyFormula::EventuallyWithin { cycles, .. } => {
                        format!("eventually within {} ({})", cycles, get_expr(0))
                    }
                    crate::ast::property::PropertyFormula::AlwaysFollowedBy {
                        delay_cycles,
                        ..
                    } => {
                        format!(
                            "always ({} followed_by {} {})",
                            get_expr(0),
                            delay_cycles,
                            get_expr(1)
                        )
                    }
                };

                let directive_prefix = match prop.directive {
                    crate::ast::property::PropertyDirective::Assert => "",
                    crate::ast::property::PropertyDirective::Cover => "cover ",
                    crate::ast::property::PropertyDirective::Assume => "assume ",
                };

                writeln!(out, 
                    "    ; {directive_prefix}property {}: {desc}",
                    registry.resolve_name(nc.0)
                ).unwrap();
            }
        }
    }
}

// -----------------------------------------------------------------------
// Type mapping
// -----------------------------------------------------------------------

fn firrtl_type(ty: &SignalType) -> String {
    // Iterative to satisfy NASA P10 (no recursion). MAX_ARRAY_DIMS bounds nesting.
    const MAX_DEPTH: usize = crate::ast::types::MAX_ARRAY_DIMS + 2;
    enum Work<'a> {
        Emit(&'a SignalType),
        SuffixOwned(String),
    }
    let mut stack: Vec<Work<'_>> = Vec::with_capacity(MAX_DEPTH * 2);
    let mut result = String::new();
    stack.push(Work::Emit(ty));
    let mut iters = 0usize;
    while let Some(w) = stack.pop() {
        iters += 1;
        if iters > MAX_DEPTH * 4 {
            break;
        }
        match w {
            Work::Emit(t) => match t {
                SignalType::Bool => result.push_str("UInt<1>"),
                SignalType::Unsigned(w) => write!(result, "UInt<{}>", w).unwrap(),
                SignalType::Signed(w) => write!(result, "SInt<{}>", w).unwrap(),
                SignalType::Array { element, length } => {
                    stack.push(Work::SuffixOwned(format!("[{}]", length)));
                    stack.push(Work::Emit(element));
                }
                SignalType::Struct { fields, .. } => {
                    let mut parts = Vec::new();
                    let mut i = 0;
                    while i < fields.len() && i < crate::ast::types::MAX_STRUCT_FIELDS {
                        parts.push(format!("{}: {}", fields[i].0, firrtl_type_flat(&fields[i].1)));
                        i += 1;
                    }
                    write!(result, "{{ {} }}", parts.join(", ")).unwrap();
                }
                SignalType::FixedPoint { total_bits, frac_bits } => {
                    write!(result, "FixedPoint<{},{}>", total_bits, frac_bits).unwrap();
                }
                SignalType::Bundle(name) => {
                    write!(result, "{{ /* interface {} */ }}", name).unwrap();
                }
                SignalType::Fifo { element, depth } => {
                    let elem_ty = firrtl_type_flat(element);
                    write!(result, "{}[{}]", elem_ty, depth).unwrap();
                }
            },
            Work::SuffixOwned(s) => result.push_str(&s),
        }
    }
    result
}

/// Non-recursive helper for struct field types (limited to scalar + FixedPoint).
fn firrtl_type_flat(ty: &SignalType) -> String {
    match ty {
        SignalType::Bool => "UInt<1>".to_string(),
        SignalType::Unsigned(w) => format!("UInt<{}>", w),
        SignalType::Signed(w) => format!("SInt<{}>", w),
        SignalType::FixedPoint { total_bits, frac_bits } => {
            format!("FixedPoint<{},{}>", total_bits, frac_bits)
        }
        SignalType::Array { element, length } => {
            format!("{}[{}]", firrtl_type_flat(element), length)
        }
        SignalType::Fifo { element, depth } => {
            format!("{}[{}]", firrtl_type_flat(element), depth)
        }
        _ => format!("UInt<{}>", ty.width()),
    }
}

// -----------------------------------------------------------------------
// Expression mapping
// -----------------------------------------------------------------------

fn emit_condition_firrtl(ck: &crate::temporal::low_level_ir::ConditionKind) -> String {
    use crate::temporal::low_level_ir::ConditionKind;
    match ck {
        ConditionKind::SimpleSignal(s) => s.clone(),
        ConditionKind::NegatedSignal(s) => format!("not({})", s),
        ConditionKind::PrevSignal { signal, .. } => signal.clone(),
        ConditionKind::Comparison { signal, op, value } => {
            let op_fn = match op {
                BinaryOp::Eq => "eq",
                BinaryOp::Ne => "neq",
                BinaryOp::Lt => "lt",
                BinaryOp::Le => "leq",
                BinaryOp::Gt => "gt",
                BinaryOp::Ge => "geq",
                _ => "eq",
            };
            let val = match value {
                LiteralValue::Integer(n) => format!("UInt({})", n),
                LiteralValue::Bool(true) => "UInt(1)".to_string(),
                LiteralValue::Bool(false) => "UInt(0)".to_string(),
            };
            format!("{}({}, {})", op_fn, signal, val)
        }
        ConditionKind::AlwaysTrue => "UInt<1>(1)".to_string(),
    }
}

fn emit_logic_expr_firrtl(le: &crate::temporal::low_level_ir::LogicExpr) -> String {
    use crate::temporal::low_level_ir::LogicExpr;
    match le {
        LogicExpr::Signal(s) => s.clone(),
        LogicExpr::And(l, r) => {
            format!("and({}, {})", emit_logic_expr_firrtl(l), emit_logic_expr_firrtl(r))
        }
        LogicExpr::Or(l, r) => {
            format!("or({}, {})", emit_logic_expr_firrtl(l), emit_logic_expr_firrtl(r))
        }
    }
}

enum ExprWork {
    Eval(crate::ecs::EntityId),
    EmitUnary(UnaryOp),
    EmitBinary(BinaryOp),
    EmitArrayIndex,
    EmitFieldAccess(String),
    EmitArrayLiteral(usize),
    EmitStructLiteral(Vec<String>),
    EmitMux,
}

fn emit_expr_inline_ecs(expr_id: crate::ecs::EntityId, registry: &crate::ecs::Registry) -> String {
    let mut result_stack: Vec<String> = Vec::with_capacity(32);
    let mut work: Vec<ExprWork> = Vec::with_capacity(32);
    work.push(ExprWork::Eval(expr_id));

    let mut visited = 0usize;

    while let Some(item) = work.pop() {
        visited += 1;
        if visited > MAX_EXPR_NODES {
            return "/* truncated */".to_string();
        }

        match item {
            ExprWork::Eval(id) => {
                let idx = id.0 as usize;

                if let Some(crate::ecs::components::LiteralComponent(lit)) = &registry.literals[idx]
                {
                    match lit {
                        crate::ast::types::LiteralValue::Bool(true) => {
                            result_stack.push("UInt<1>(1)".to_string())
                        }
                        crate::ast::types::LiteralValue::Bool(false) => {
                            result_stack.push("UInt<1>(0)".to_string())
                        }
                        crate::ast::types::LiteralValue::Integer(n) => {
                            result_stack.push(format!("UInt({})", n))
                        }
                    }
                } else if let Some(crate::ecs::components::SignalRefComponent(sig_ent)) =
                    registry.signal_refs[idx]
                {
                    let sig_name = registry.names[sig_ent.0 as usize]
                        .map(|nc| registry.resolve_name(nc.0).to_string())
                        .unwrap_or_default();
                    result_stack.push(sig_name);
                } else if let Some(crate::ecs::components::PendingSignalRef(name)) =
                    &registry.pending_signal_refs[idx]
                {
                    result_stack.push(name.clone());
                } else if let Some(crate::ecs::components::PrevComponent { signal, delay }) =
                    &registry.prev_ops[idx]
                {
                    let sig_name = if let Some(crate::ecs::components::SignalRefComponent(decl)) =
                        registry.signal_refs[signal.0 as usize]
                    {
                        registry.names[decl.0 as usize]
                            .map(|nc| registry.resolve_name(nc.0).to_string())
                            .unwrap_or_default()
                    } else if let Some(crate::ecs::components::PendingSignalRef(n)) =
                        &registry.pending_signal_refs[signal.0 as usize]
                    {
                        n.clone()
                    } else {
                        String::new()
                    };
                    result_stack.push(format!("{}_d{}", sig_name, delay));
                } else if let Some(crate::ecs::components::BinaryComponent { op, left, right }) =
                    &registry.binary_ops[idx]
                {
                    work.push(ExprWork::EmitBinary(*op));
                    work.push(ExprWork::Eval(*right));
                    work.push(ExprWork::Eval(*left));
                } else if let Some(crate::ecs::components::UnaryComponent { op, operand }) =
                    &registry.unary_ops[idx]
                {
                    work.push(ExprWork::EmitUnary(*op));
                    work.push(ExprWork::Eval(*operand));
                } else if let Some(crate::ecs::components::ArrayIndexComponent { array, index }) =
                    &registry.array_indices[idx]
                {
                    work.push(ExprWork::EmitArrayIndex);
                    work.push(ExprWork::Eval(*index));
                    work.push(ExprWork::Eval(*array));
                } else if let Some(crate::ecs::components::FieldAccessComponent { object, field }) =
                    &registry.field_accesses[idx]
                {
                    work.push(ExprWork::EmitFieldAccess(field.clone()));
                    work.push(ExprWork::Eval(*object));
                } else if let Some(crate::ecs::components::ArrayLiteralComponent(elems)) =
                    &registry.array_literals[idx]
                {
                    work.push(ExprWork::EmitArrayLiteral(elems.len()));
                    for elem in elems.iter().rev() {
                        work.push(ExprWork::Eval(*elem));
                    }
                } else if let Some(crate::ecs::components::StructLiteralComponent {
                    name: _,
                    fields,
                }) = &registry.struct_literals[idx]
                {
                    work.push(ExprWork::EmitStructLiteral(
                        fields.iter().map(|(f, _)| f.clone()).collect(),
                    ));
                    for (_, val) in fields.iter().rev() {
                        work.push(ExprWork::Eval(*val));
                    }
                } else if let Some(crate::ecs::components::UnfoldIndexComponent(name)) =
                    &registry.unfold_indices[idx]
                {
                    unreachable!("UnfoldIndex '{}' reached FIRRTL emitter", name);
                } else if let Some(crate::ecs::components::MuxComponent {
                    select,
                    true_val,
                    false_val,
                }) = &registry.muxes[idx]
                {
                    work.push(ExprWork::EmitMux);
                    work.push(ExprWork::Eval(*false_val));
                    work.push(ExprWork::Eval(*true_val));
                    work.push(ExprWork::Eval(*select));
                } else {
                    result_stack.push("/* unknown_expr */".to_string());
                }
            }
            ExprWork::EmitUnary(op) => {
                let inner = result_stack.pop().unwrap_or_default();
                let res = match op {
                    UnaryOp::Not => format!("not({})", inner),
                    UnaryOp::Negate => format!("neg({})", inner),
                    UnaryOp::ReductionOr => format!("orr({})", inner),
                };
                result_stack.push(res);
            }
            ExprWork::EmitBinary(op) => {
                let r = result_stack.pop().unwrap_or_default();
                let l = result_stack.pop().unwrap_or_default();
                let op_fn = match op {
                    BinaryOp::And => "and",
                    BinaryOp::Or => "or",
                    BinaryOp::BitwiseOr => "or",
                    BinaryOp::BitwiseAnd => "and",
                    BinaryOp::Xor => "xor",
                    BinaryOp::Lt => "lt",
                    BinaryOp::Le => "leq",
                    BinaryOp::Gt => "gt",
                    BinaryOp::Ge => "geq",
                    BinaryOp::Eq => "eq",
                    BinaryOp::Ne => "neq",
                    BinaryOp::Add => "add",
                    BinaryOp::Sub => "sub",
                    BinaryOp::Mul => "mul",
                    BinaryOp::Shl => "dshl",
                    BinaryOp::Shr => "dshr",
                };
                result_stack.push(format!("{}({}, {})", op_fn, l, r));
            }
            ExprWork::EmitArrayIndex => {
                let i = result_stack.pop().unwrap_or_default();
                let a = result_stack.pop().unwrap_or_default();
                result_stack.push(format!("{}[{}]", a, i));
            }
            ExprWork::EmitFieldAccess(field) => {
                let o = result_stack.pop().unwrap_or_default();
                result_stack.push(format!("{}.{}", o, field));
            }
            ExprWork::EmitArrayLiteral(len) => {
                let mut parts = Vec::with_capacity(len);
                for _ in 0..len {
                    parts.push(result_stack.pop().unwrap_or_default());
                }
                if parts.is_empty() {
                    result_stack.push("UInt(0)".to_string());
                } else {
                    result_stack.push(format!("cat({})", parts.join(", ")));
                }
            }
            ExprWork::EmitStructLiteral(fields) => {
                let mut parts = Vec::with_capacity(fields.len());
                for _ in &fields {
                    parts.push(result_stack.pop().unwrap_or_default());
                }
                if parts.is_empty() {
                    result_stack.push("UInt(0)".to_string());
                } else {
                    result_stack.push(format!("cat({})", parts.join(", ")));
                }
            }
            ExprWork::EmitMux => {
                let cond = result_stack.pop().unwrap_or_default();
                let t = result_stack.pop().unwrap_or_default();
                let f = result_stack.pop().unwrap_or_default();
                result_stack.push(format!("mux({}, {}, {})", cond, t, f));
            }
        }
    }

    result_stack.pop().unwrap_or_default()
}
