//! FIRRTL emitter for MIRR IR.
//!
//! Produces FIRRTL (Flexible Intermediate Representation for RTL) output
//! from the compiled pipeline result. FIRRTL is the intermediate language
//! used by the CHIPS Alliance / CIRCT ecosystem.
//!
//! Mapping notes:
//! - Signals → FIRRTL `input`/`output`/`wire` declarations
//! - Guards → shift-register or counter hardware (from temporal netlist)
//! - Reflexes → conditional `connect` statements under `when` blocks
//! - Properties → FIRRTL `assert` intrinsics (limited; SVA has no FIRRTL
//!   equivalent, so properties emit as verification comments)
//!
//! Width mapping: `bool` → `UInt<1>`, `uN` → `UInt<N>`.

#![forbid(unsafe_code)]

use crate::ast::types::{BinaryOp, LiteralValue, SignalKind, SignalType, UnaryOp};
use crate::ast::MAX_EXPR_NODES;
use crate::pipeline::PipelineResult;
use crate::temporal::low_level_ir::{CompiledGuard, TemporalNetlist};

use crate::error::MirrError;
use crate::error_codes::{mirrcode, ErrorCode};

/// Emit FIRRTL from pipeline results.
pub fn emit_firrtl(result: &PipelineResult) -> Result<String, MirrError> {
    let mut out = String::with_capacity(4096);
    let registry = result.ecs_registry.as_ref().ok_or_else(|| {
        mirrcode(ErrorCode::RspuFallback, "ECS registry must be populated for FIRRTL emission")
    })?;
    let module_name = registry.get_module_name().unwrap_or_else(|| "unknown_module".to_string());

    emit_header(&mut out);
    out.push_str("circuit ");
    out.push_str(&module_name);
    out.push_str(" :\n");

    emit_module(&module_name, registry, result.temporal_netlist.as_ref(), &mut out);

    Ok(out)
}

// -----------------------------------------------------------------------
// Internal helpers
// -----------------------------------------------------------------------

fn emit_header(out: &mut String) {
    out.push_str("; Auto-generated by MIRR compiler\n");
    out.push_str("; Do not edit — regenerate from .mirr source.\n");
    out.push_str("; Target: FIRRTL\n");
    out.push_str("FIRRTL version 1.1.0\n");
}

fn emit_module(
    module_name: &str,
    registry: &crate::ecs::Registry,
    temporal_netlist: Option<&TemporalNetlist>,
    out: &mut String,
) {
    out.push_str("  module ");
    out.push_str(module_name);
    out.push_str(" :\n");

    // Clock and reset (implicit in MIRR, explicit in FIRRTL).
    out.push_str("    input clk : Clock\n");
    out.push_str("    input rst_n : UInt<1>\n");

    emit_ports(registry, out);
    emit_internal_wires(registry, out);
    out.push('\n');

    if let Some(netlist) = temporal_netlist {
        emit_temporal_logic(netlist, out);
    }

    emit_reflex_logic(registry, out);
    emit_property_comments(registry, out);
}

fn emit_ports(registry: &crate::ecs::Registry, out: &mut String) {
    for i in 0..registry.names.len() {
        if let (Some(name_comp), Some(kind_comp), Some(ty_comp)) =
            (&registry.names[i], &registry.kinds[i], &registry.types[i])
        {
            if let crate::ecs::EntityKind::SIGNAL(sig_kind) = kind_comp.0 {
                let dir = match sig_kind {
                    SignalKind::Input => "input",
                    SignalKind::Output => "output",
                    SignalKind::Internal => continue, // handled as wires
                };
                let ty = firrtl_type(&ty_comp.0.core);
                out.push_str(&format!("    {} {} : {}\n", dir, name_comp.0, ty));
            }
        }
    }
}

fn emit_internal_wires(registry: &crate::ecs::Registry, out: &mut String) {
    let mut has_internals = false;
    for i in 0..registry.names.len() {
        if let (Some(name_comp), Some(kind_comp), Some(ty_comp)) =
            (&registry.names[i], &registry.kinds[i], &registry.types[i])
        {
            if let crate::ecs::EntityKind::SIGNAL(SignalKind::Internal) = kind_comp.0 {
                if !has_internals {
                    out.push_str("\n    ; Internal signals\n");
                    has_internals = true;
                }
                let ty = firrtl_type(&ty_comp.0.core);
                out.push_str(&format!("    wire {} : {}\n", name_comp.0, ty));
            }
        }
    }
}

fn emit_temporal_logic(netlist: &TemporalNetlist, out: &mut String) {
    out.push_str("\n    ; ── Temporal Guards ──\n");

    for guard in &netlist.guards {
        match guard {
            CompiledGuard::ShiftRegister(sr) => {
                emit_shift_register_firrtl(sr, out);
            }
            CompiledGuard::Counter(cg) => {
                emit_counter_firrtl(cg, out);
            }
            CompiledGuard::Complex(cx) => {
                out.push_str(&format!(
                    "\n    ; Complex guard: {} (sub-guards combined)\n",
                    cx.name
                ));
                let ty = "UInt<1>";
                out.push_str(&format!("    wire {} : {}\n", cx.output_signal, ty));
                let expr = emit_logic_expr_firrtl(&cx.combination_logic);
                out.push_str(&format!("    connect {} , {}\n", cx.output_signal, expr));
            }
            CompiledGuard::DynamicCounter(dc) => {
                out.push_str(&format!(
                    "\n    ; Dynamic counter guard: {} (max {} cycles)\n",
                    dc.name, dc.max_delay
                ));
                let width = dc.counter_width();
                out.push_str(&format!("    reg {} : UInt<{}>, clock\n", dc.counter_signal, width));
                out.push_str(&format!("    wire {} : UInt<1>\n", dc.output_signal));
            }
        }
    }
}

fn emit_shift_register_firrtl(
    sr: &crate::temporal::low_level_ir::ShiftRegisterGuard,
    out: &mut String,
) {
    let stage_count = sr.delay_cycles.min(super::verilog::MAX_SR_STAGES_INLINE);
    let cond = emit_condition_firrtl(&sr.condition_kind);

    out.push_str(&format!(
        "\n    ; Guard: {} — {} for {} cycles\n",
        sr.name,
        sr.condition_kind.describe(),
        sr.delay_cycles,
    ));

    // Shift register as a vector of 1-bit registers.
    out.push_str(&format!(
        "    reg {}_sr : UInt<{}> , clk with : (reset => (not(rst_n), UInt(0)))\n",
        sr.name, stage_count,
    ));

    // Condition wire.
    out.push_str(&format!("    wire {}_cond : UInt<1>\n", sr.name));
    out.push_str(&format!("    connect {}_cond , {}\n", sr.name, cond));

    // Shift operation: sr <= cat(cond, sr[high:1]).
    out.push_str(&format!("    connect {0}_sr , cat({0}_cond, shr({0}_sr, 1))\n", sr.name,));

    // Output: guard fires when all bits are 1.
    out.push_str(&format!("    wire {} : UInt<1>\n", sr.output_signal));
    out.push_str(&format!("    connect {} , andr({}_sr)\n", sr.output_signal, sr.name,));
}

fn emit_counter_firrtl(cg: &crate::temporal::low_level_ir::CounterGuard, out: &mut String) {
    let width = cg.counter_width();
    let cond = emit_condition_firrtl(&cg.condition_kind);

    out.push_str(&format!(
        "\n    ; Guard: {} — {} for {} cycles (counter)\n",
        cg.name,
        cg.condition_kind.describe(),
        cg.target_count,
    ));

    // Counter register.
    out.push_str(&format!(
        "    reg {} : UInt<{}> , clk with : (reset => (not(rst_n), UInt(0)))\n",
        cg.counter_signal, width,
    ));

    // Condition wire.
    out.push_str(&format!("    wire {}_cond : UInt<1>\n", cg.name));
    out.push_str(&format!("    connect {}_cond , {}\n", cg.name, cond));

    // Counter logic.
    out.push_str(&format!(
        "    when not({0}_cond) :\n      connect {1} , UInt(0)\n",
        cg.name, cg.counter_signal,
    ));
    out.push_str(&format!(
        "    else when lt({0}, UInt({1})) :\n      connect {0} , add({0}, UInt(1))\n",
        cg.counter_signal, cg.target_count,
    ));

    // Output: guard fires when counter >= target.
    out.push_str(&format!("    wire {} : UInt<1>\n", cg.output_signal));
    out.push_str(&format!(
        "    connect {} , geq({}, UInt({}))\n",
        cg.output_signal, cg.counter_signal, cg.target_count,
    ));
}

fn emit_reflex_logic(registry: &crate::ecs::Registry, out: &mut String) {
    let mut has_reflex = false;
    for kind_comp in &registry.kinds {
        if let Some(crate::ecs::components::KindComponent(crate::ecs::EntityKind::REFLEX)) =
            kind_comp
        {
            has_reflex = true;
            break;
        }
    }

    if !has_reflex {
        return;
    }

    out.push_str("\n    ; ── Reflex Assignments ──\n");

    for i in 0..registry.names.len() {
        if let (Some(name_comp), Some(kind_comp), Some(r)) =
            (&registry.names[i], &registry.kinds[i], &registry.reflex_comps[i])
        {
            if let crate::ecs::EntityKind::REFLEX = kind_comp.0 {
                out.push_str(&format!("\n    ; Reflex: {}\n", name_comp.0));

                let guard_cond = if r.guards.len() == 1 {
                    let g_name = &registry.names[r.guards[0].0 as usize].as_ref().unwrap().0;
                    format!("{}_out", g_name)
                } else if r.guards.is_empty() {
                    "UInt<1>(1)".to_string()
                } else {
                    let mut expr = format!(
                        "{}_out",
                        registry.names[r.guards[0].0 as usize].as_ref().unwrap().0
                    );
                    let mut j = 1;
                    while j < r.guards.len() {
                        let g_name = &registry.names[r.guards[j].0 as usize].as_ref().unwrap().0;
                        expr = format!("and({}, {}_out)", expr, g_name);
                        j += 1;
                    }
                    expr
                };

                for a_id in &r.assignments {
                    if let Some(assign) = &registry.assignment_comps[a_id.0 as usize] {
                        let target_name =
                            &registry.names[assign.target.0 as usize].as_ref().unwrap().0;
                        let val = emit_expr_inline_ecs(assign.value, registry);
                        out.push_str(&format!(
                            "    when {} :\n      connect {} , {}\n    else :\n      connect {} , UInt(0)\n",
                            guard_cond, target_name, val, target_name,
                        ));
                    }
                }
            }
        }
    }
}

fn emit_property_comments(registry: &crate::ecs::Registry, out: &mut String) {
    let mut has_properties = false;
    for kind_comp in &registry.kinds {
        if let Some(crate::ecs::components::KindComponent(crate::ecs::EntityKind::PROPERTY)) =
            kind_comp
        {
            has_properties = true;
            break;
        }
    }

    if !has_properties {
        return;
    }

    out.push_str(
        "\n    ; ── Safety Properties (verification only — no FIRRTL equivalent to SVA) ──\n",
    );

    for i in 0..registry.names.len() {
        if let (Some(name_comp), Some(kind_comp), Some(prop)) =
            (&registry.names[i], &registry.kinds[i], &registry.property_comps[i])
        {
            if let crate::ecs::EntityKind::PROPERTY = kind_comp.0 {
                let desc = match &prop.formula {
                    crate::ast::property::PropertyFormula::Always(_) => {
                        format!(
                            "always ({})",
                            emit_expr_inline_ecs(prop.formula_exprs[0], registry)
                        )
                    }
                    crate::ast::property::PropertyFormula::Never(_) => {
                        format!("never ({})", emit_expr_inline_ecs(prop.formula_exprs[0], registry))
                    }
                    crate::ast::property::PropertyFormula::AlwaysImplies { .. } => {
                        format!(
                            "always ({} -> {})",
                            emit_expr_inline_ecs(prop.formula_exprs[0], registry),
                            emit_expr_inline_ecs(prop.formula_exprs[1], registry)
                        )
                    }
                    crate::ast::property::PropertyFormula::NeverImplies { .. } => {
                        format!(
                            "never ({} -> {})",
                            emit_expr_inline_ecs(prop.formula_exprs[0], registry),
                            emit_expr_inline_ecs(prop.formula_exprs[1], registry)
                        )
                    }
                    crate::ast::property::PropertyFormula::EventuallyWithin { cycles, .. } => {
                        format!(
                            "eventually within {} ({})",
                            cycles,
                            emit_expr_inline_ecs(prop.formula_exprs[0], registry)
                        )
                    }
                    crate::ast::property::PropertyFormula::AlwaysFollowedBy {
                        delay_cycles,
                        ..
                    } => {
                        format!(
                            "always ({} followed_by {} {})",
                            emit_expr_inline_ecs(prop.formula_exprs[0], registry),
                            delay_cycles,
                            emit_expr_inline_ecs(prop.formula_exprs[1], registry)
                        )
                    }
                };

                let directive_prefix = match prop.directive {
                    crate::ast::property::PropertyDirective::Assert => "",
                    crate::ast::property::PropertyDirective::Cover => "cover ",
                    crate::ast::property::PropertyDirective::Assume => "assume ",
                };

                out.push_str(&format!(
                    "    ; {directive_prefix}property {}: {desc}\n",
                    name_comp.0
                ));
            }
        }
    }
}

// -----------------------------------------------------------------------
// Type mapping
// -----------------------------------------------------------------------

fn firrtl_type(ty: &SignalType) -> String {
    // Iterative to satisfy NASA P10 (no recursion). MAX_ARRAY_DIMS bounds nesting.
    const MAX_DEPTH: usize = crate::ast::types::MAX_ARRAY_DIMS + 2;
    enum Work<'a> {
        Emit(&'a SignalType),
        SuffixOwned(String),
    }
    let mut stack: Vec<Work<'_>> = Vec::with_capacity(MAX_DEPTH * 2);
    let mut result = String::new();
    stack.push(Work::Emit(ty));
    let mut iters = 0usize;
    while let Some(w) = stack.pop() {
        iters += 1;
        if iters > MAX_DEPTH * 4 {
            break;
        }
        match w {
            Work::Emit(t) => match t {
                SignalType::Bool => result.push_str("UInt<1>"),
                SignalType::Unsigned(w) => result.push_str(&format!("UInt<{}>", w)),
                SignalType::Signed(w) => result.push_str(&format!("SInt<{}>", w)),
                SignalType::Array { element, length } => {
                    stack.push(Work::SuffixOwned(format!("[{}]", length)));
                    stack.push(Work::Emit(element));
                }
                SignalType::Struct { fields, .. } => {
                    let mut parts = Vec::new();
                    let mut i = 0;
                    while i < fields.len() && i < crate::ast::types::MAX_STRUCT_FIELDS {
                        parts.push(format!("{}: {}", fields[i].0, firrtl_type_flat(&fields[i].1)));
                        i += 1;
                    }
                    result.push_str(&format!("{{ {} }}", parts.join(", ")));
                }
                SignalType::FixedPoint { total_bits, frac_bits } => {
                    result.push_str(&format!("FixedPoint<{},{}>", total_bits, frac_bits));
                }
                SignalType::Bundle(name) => {
                    result.push_str(&format!("{{ /* interface {} */ }}", name));
                }
                SignalType::Fifo { element, depth } => {
                    let elem_ty = firrtl_type_flat(element);
                    result.push_str(&format!("{}[{}]", elem_ty, depth));
                }
            },
            Work::SuffixOwned(s) => result.push_str(&s),
        }
    }
    result
}

/// Non-recursive helper for struct field types (limited to scalar + FixedPoint).
fn firrtl_type_flat(ty: &SignalType) -> String {
    match ty {
        SignalType::Bool => "UInt<1>".to_string(),
        SignalType::Unsigned(w) => format!("UInt<{}>", w),
        SignalType::Signed(w) => format!("SInt<{}>", w),
        SignalType::FixedPoint { total_bits, frac_bits } => {
            format!("FixedPoint<{},{}>", total_bits, frac_bits)
        }
        SignalType::Array { element, length } => {
            format!("{}[{}]", firrtl_type_flat(element), length)
        }
        SignalType::Fifo { element, depth } => {
            format!("{}[{}]", firrtl_type_flat(element), depth)
        }
        _ => format!("UInt<{}>", ty.width()),
    }
}

// -----------------------------------------------------------------------
// Expression mapping
// -----------------------------------------------------------------------

fn emit_condition_firrtl(ck: &crate::temporal::low_level_ir::ConditionKind) -> String {
    use crate::temporal::low_level_ir::ConditionKind;
    match ck {
        ConditionKind::SimpleSignal(s) => s.clone(),
        ConditionKind::NegatedSignal(s) => format!("not({})", s),
        ConditionKind::PrevSignal { signal, .. } => signal.clone(),
        ConditionKind::Comparison { signal, op, value } => {
            let op_fn = match op {
                BinaryOp::Eq => "eq",
                BinaryOp::Ne => "neq",
                BinaryOp::Lt => "lt",
                BinaryOp::Le => "leq",
                BinaryOp::Gt => "gt",
                BinaryOp::Ge => "geq",
                _ => "eq",
            };
            let val = match value {
                LiteralValue::Integer(n) => format!("UInt({})", n),
                LiteralValue::Bool(true) => "UInt(1)".to_string(),
                LiteralValue::Bool(false) => "UInt(0)".to_string(),
            };
            format!("{}({}, {})", op_fn, signal, val)
        }
        ConditionKind::AlwaysTrue => "UInt<1>(1)".to_string(),
    }
}

fn emit_logic_expr_firrtl(le: &crate::temporal::low_level_ir::LogicExpr) -> String {
    use crate::temporal::low_level_ir::LogicExpr;
    match le {
        LogicExpr::Signal(s) => s.clone(),
        LogicExpr::And(l, r) => {
            format!("and({}, {})", emit_logic_expr_firrtl(l), emit_logic_expr_firrtl(r))
        }
        LogicExpr::Or(l, r) => {
            format!("or({}, {})", emit_logic_expr_firrtl(l), emit_logic_expr_firrtl(r))
        }
    }
}

enum ExprWork {
    Eval(crate::ecs::EntityId),
    EmitUnary(UnaryOp),
    EmitBinary(BinaryOp),
    EmitArrayIndex,
    EmitFieldAccess(String),
    EmitArrayLiteral(usize),
    EmitStructLiteral(Vec<String>),
    EmitMux,
}

fn emit_expr_inline_ecs(expr_id: crate::ecs::EntityId, registry: &crate::ecs::Registry) -> String {
    let mut result_stack: Vec<String> = Vec::with_capacity(32);
    let mut work: Vec<ExprWork> = Vec::with_capacity(32);
    work.push(ExprWork::Eval(expr_id));

    let mut visited = 0usize;

    while let Some(item) = work.pop() {
        visited += 1;
        if visited > MAX_EXPR_NODES {
            return "/* truncated */".to_string();
        }

        match item {
            ExprWork::Eval(id) => {
                let idx = id.0 as usize;

                if let Some(crate::ecs::components::LiteralComponent(lit)) = &registry.literals[idx]
                {
                    match lit {
                        crate::ast::types::LiteralValue::Bool(true) => {
                            result_stack.push("UInt<1>(1)".to_string())
                        }
                        crate::ast::types::LiteralValue::Bool(false) => {
                            result_stack.push("UInt<1>(0)".to_string())
                        }
                        crate::ast::types::LiteralValue::Integer(n) => {
                            result_stack.push(format!("UInt({})", n))
                        }
                    }
                } else if let Some(crate::ecs::components::SignalRefComponent(sig_ent)) =
                    registry.signal_refs[idx]
                {
                    let sig_name = registry.names[sig_ent.0 as usize]
                        .as_ref()
                        .map(|n| n.0.clone())
                        .unwrap_or_default();
                    result_stack.push(sig_name);
                } else if let Some(crate::ecs::components::PendingSignalRef(name)) =
                    &registry.pending_signal_refs[idx]
                {
                    result_stack.push(name.clone());
                } else if let Some(crate::ecs::components::PrevComponent { signal, delay }) =
                    &registry.prev_ops[idx]
                {
                    let sig_name = if let Some(crate::ecs::components::SignalRefComponent(decl)) =
                        registry.signal_refs[signal.0 as usize]
                    {
                        registry.names[decl.0 as usize]
                            .as_ref()
                            .map(|n| n.0.clone())
                            .unwrap_or_default()
                    } else if let Some(crate::ecs::components::PendingSignalRef(n)) =
                        &registry.pending_signal_refs[signal.0 as usize]
                    {
                        n.clone()
                    } else {
                        String::new()
                    };
                    result_stack.push(format!("{}_d{}", sig_name, delay));
                } else if let Some(crate::ecs::components::BinaryComponent { op, left, right }) =
                    &registry.binary_ops[idx]
                {
                    work.push(ExprWork::EmitBinary(*op));
                    work.push(ExprWork::Eval(*right));
                    work.push(ExprWork::Eval(*left));
                } else if let Some(crate::ecs::components::UnaryComponent { op, operand }) =
                    &registry.unary_ops[idx]
                {
                    work.push(ExprWork::EmitUnary(*op));
                    work.push(ExprWork::Eval(*operand));
                } else if let Some(crate::ecs::components::ArrayIndexComponent { array, index }) =
                    &registry.array_indices[idx]
                {
                    work.push(ExprWork::EmitArrayIndex);
                    work.push(ExprWork::Eval(*index));
                    work.push(ExprWork::Eval(*array));
                } else if let Some(crate::ecs::components::FieldAccessComponent { object, field }) =
                    &registry.field_accesses[idx]
                {
                    work.push(ExprWork::EmitFieldAccess(field.clone()));
                    work.push(ExprWork::Eval(*object));
                } else if let Some(crate::ecs::components::ArrayLiteralComponent(elems)) =
                    &registry.array_literals[idx]
                {
                    work.push(ExprWork::EmitArrayLiteral(elems.len()));
                    for elem in elems.iter().rev() {
                        work.push(ExprWork::Eval(*elem));
                    }
                } else if let Some(crate::ecs::components::StructLiteralComponent {
                    name: _,
                    fields,
                }) = &registry.struct_literals[idx]
                {
                    work.push(ExprWork::EmitStructLiteral(
                        fields.iter().map(|(f, _)| f.clone()).collect(),
                    ));
                    for (_, val) in fields.iter().rev() {
                        work.push(ExprWork::Eval(*val));
                    }
                } else if let Some(crate::ecs::components::UnfoldIndexComponent(name)) =
                    &registry.unfold_indices[idx]
                {
                    unreachable!("UnfoldIndex '{}' reached FIRRTL emitter", name);
                } else if let Some(crate::ecs::components::MuxComponent {
                    select,
                    true_val,
                    false_val,
                }) = &registry.muxes[idx]
                {
                    work.push(ExprWork::EmitMux);
                    work.push(ExprWork::Eval(*false_val));
                    work.push(ExprWork::Eval(*true_val));
                    work.push(ExprWork::Eval(*select));
                } else {
                    result_stack.push("/* unknown_expr */".to_string());
                }
            }
            ExprWork::EmitUnary(op) => {
                let inner = result_stack.pop().unwrap_or_default();
                let res = match op {
                    UnaryOp::Not => format!("not({})", inner),
                    UnaryOp::Negate => format!("neg({})", inner),
                    UnaryOp::ReductionOr => format!("orr({})", inner),
                };
                result_stack.push(res);
            }
            ExprWork::EmitBinary(op) => {
                let r = result_stack.pop().unwrap_or_default();
                let l = result_stack.pop().unwrap_or_default();
                let op_fn = match op {
                    BinaryOp::And => "and",
                    BinaryOp::Or => "or",
                    BinaryOp::BitwiseOr => "or",
                    BinaryOp::BitwiseAnd => "and",
                    BinaryOp::Xor => "xor",
                    BinaryOp::Lt => "lt",
                    BinaryOp::Le => "leq",
                    BinaryOp::Gt => "gt",
                    BinaryOp::Ge => "geq",
                    BinaryOp::Eq => "eq",
                    BinaryOp::Ne => "neq",
                    BinaryOp::Add => "add",
                    BinaryOp::Sub => "sub",
                    BinaryOp::Mul => "mul",
                    BinaryOp::Shl => "dshl",
                    BinaryOp::Shr => "dshr",
                };
                result_stack.push(format!("{}({}, {})", op_fn, l, r));
            }
            ExprWork::EmitArrayIndex => {
                let i = result_stack.pop().unwrap_or_default();
                let a = result_stack.pop().unwrap_or_default();
                result_stack.push(format!("{}[{}]", a, i));
            }
            ExprWork::EmitFieldAccess(field) => {
                let o = result_stack.pop().unwrap_or_default();
                result_stack.push(format!("{}.{}", o, field));
            }
            ExprWork::EmitArrayLiteral(len) => {
                let mut parts = Vec::with_capacity(len);
                for _ in 0..len {
                    parts.push(result_stack.pop().unwrap_or_default());
                }
                if parts.is_empty() {
                    result_stack.push("UInt(0)".to_string());
                } else {
                    result_stack.push(format!("cat({})", parts.join(", ")));
                }
            }
            ExprWork::EmitStructLiteral(fields) => {
                let mut parts = Vec::with_capacity(fields.len());
                for _ in &fields {
                    parts.push(result_stack.pop().unwrap_or_default());
                }
                if parts.is_empty() {
                    result_stack.push("UInt(0)".to_string());
                } else {
                    result_stack.push(format!("cat({})", parts.join(", ")));
                }
            }
            ExprWork::EmitMux => {
                let cond = result_stack.pop().unwrap_or_default();
                let t = result_stack.pop().unwrap_or_default();
                let f = result_stack.pop().unwrap_or_default();
                result_stack.push(format!("mux({}, {}, {})", cond, t, f));
            }
        }
    }

    result_stack.pop().unwrap_or_default()
}
