//! RISC-V RV32I assembly emission backend.
//!
//! Translates an R-SPU program (from `rspu.rs`) into RV32I assembly text.
//! All control flow is forward-only (BEQ/BNE) — no backward branches.
//! Bounded execution via ECALL watchdog at program end.

#![forbid(unsafe_code)]

use super::rspu::rspu_err;
use super::rspu_isa::*;
use crate::error::MirrError;
use std::fmt::Write;

/// Memory-mapped I/O base address for RISC-V soft cores.
const MMIO_BASE: u32 = 0x1000_0000;

/// Emit RISC-V RV32I assembly from an R-SPU program.
///
/// Returns a complete `.S` file with `.text` and `.data` sections.
pub fn emit_riscv_asm(program: &RspuProgram) -> Result<String, MirrError> {
    let mut out = String::with_capacity(program.instructions.len() * 80);
    let mut label_counter: u32 = 0;

    // Header
    out.push_str("# RISC-V RV32I Assembly — generated by MIRR compiler\n");
    writeln!(out, "# Registers used: {}", program.registers_used).unwrap();
    writeln!(out, "# Guards used:    {}", program.guards_used).unwrap();
    writeln!(out, "# Instructions:   {}", program.instructions.len()).unwrap();
    out.push_str("#\n# Register map:\n");

    for (name, _reg) in &program.register_map {
        writeln!(out, "#   x{:<2} = {}", _reg, name).unwrap();
    }
    out.push_str("#\n# Guard map:\n");
    for (name, gid) in &program.guard_map {
        writeln!(out, "#   G{:<2} = {}", gid, name).unwrap();
    }
    out.push('\n');

    // Text section
    out.push_str(".section .text\n.globl _start\n\n_start:\n");

    // Emit instructions
    for (i, instr) in program.instructions.iter().enumerate() {
        write!(out, "\ninstr_{}:\n", i).unwrap();
        emit_riscv_instruction(&mut out, instr, &mut label_counter)?;
    }

    // HALT at end (safety guarantee)
    out.push_str("\ninstr_halt:\n");
    out.push_str("    li a7, 0\n");
    out.push_str("    ecall\n");

    // Data section
    out.push_str("\n.section .data\n");
    for (name, _reg) in &program.register_map {
        writeln!(out, "signal_{}: .word 0", name).unwrap();
    }
    // Guard state storage
    for (name, _) in &program.guard_map {
        writeln!(out, "guard_{}: .word 0", name).unwrap();
    }
    // Shift register storage (bounded by MAX_GUARDS * 256 words)
    for (name, _) in &program.guard_map {
        writeln!(out, "sr_{}: .space 1024", name).unwrap(); // 256 words * 4 bytes
    }

    Ok(out)
}

/// Emit a single RISC-V instruction.
fn emit_riscv_instruction(
    out: &mut String,
    instr: &RspuInstruction,
    label_counter: &mut u32,
) -> Result<(), MirrError> {
    match instr {
        RspuInstruction::TagBranch { tag_value, target_pc } => {
            writeln!(out, "    # TAG_BRANCH {}, {}", tag_value, target_pc).unwrap();
        }
        // Register tier
        RspuInstruction::LoadInput { dst, port } => {
            let addr = MMIO_BASE + (*port as u32) * 4;
            writeln!(out, "    li t0, 0x{:08X}", addr).unwrap();
            writeln!(out, "    lw x{}, 0(t0)", dst).unwrap();
        }
        RspuInstruction::StoreOutput { src, port } => {
            let addr = MMIO_BASE + (*port as u32) * 4;
            writeln!(out, "    li t0, 0x{:08X}", addr).unwrap();
            writeln!(out, "    sw x{}, 0(t0)", src).unwrap();
        }
        RspuInstruction::Mov { dst, src } => {
            writeln!(out, "    addi x{}, x{}, 0", dst, src).unwrap();
        }
        RspuInstruction::LoadImm { dst, value, .. } => {
            writeln!(out, "    li x{}, {}", dst, value).unwrap();
        }

        // ALU tier
        RspuInstruction::Alu { op, dst, a, b } => {
            let d8 = (*dst)
                .try_into()
                .map_err(|_| rspu_err("RISC-V target only supports registers R0-R255"))?;
            let a8 = (*a)
                .try_into()
                .map_err(|_| rspu_err("RISC-V target only supports registers R0-R255"))?;
            let b8 = (*b)
                .try_into()
                .map_err(|_| rspu_err("RISC-V target only supports registers R0-R255"))?;
            emit_riscv_alu(out, *op, d8, a8, b8);
        }
        RspuInstruction::AluImm { op, dst, a, imm } => {
            let d8 = (*dst)
                .try_into()
                .map_err(|_| rspu_err("RISC-V target only supports registers R0-R255"))?;
            let a8 = (*a)
                .try_into()
                .map_err(|_| rspu_err("RISC-V target only supports registers R0-R255"))?;
            emit_riscv_alu_imm(out, *op, d8, a8, *imm);
        }
        RspuInstruction::AluUnary { op, dst, src } => match op {
            AluUnaryOp::Not => writeln!(out, "    xori x{}, x{}, -1", dst, src).unwrap(),
            AluUnaryOp::Negate => writeln!(out, "    sub x{}, x0, x{}", dst, src).unwrap(),
            AluUnaryOp::ReductionOr => writeln!(out, "    snez x{}, x{}", dst, src).unwrap(),
        },

        // Temporal tier — shift register emulation
        RspuInstruction::SrInit { guard, length, cond } => {
            // Store condition value to guard state.
            writeln!(out, "    la t0, guard_g{}", guard).unwrap();
            writeln!(out, "    sw x{}, 0(t0)", cond).unwrap();
            // Zero-fill shift register chain for `length` stages.
            writeln!(out, "    la t0, sr_g{}", guard).unwrap();
            out.push_str("    li t1, 0\n");
            let stages = (*length).min(256);
            for s in 0..stages {
                writeln!(out, "    sw t1, {}(t0)", s * 4).unwrap();
            }
        }
        RspuInstruction::SrTick { guard } => {
            // Shift register chain: stage[i+1] = stage[i], stage[0] = guard state.
            writeln!(out, "    la t0, sr_g{}", guard).unwrap();
            writeln!(out, "    la t3, guard_g{}", guard).unwrap();
            out.push_str("    lw t4, 0(t3)\n"); // new value from guard state
                                                // Shift stages 1..N ← 0..N-1 (reverse order to avoid overwrite)
            out.push_str("    li t5, 256\n"); // max stages
            out.push_str("shift_loop_rv_:\n");
            out.push_str("    addi t5, t5, -1\n");
            out.push_str("    beq t5, x0, shift_done_rv_\n");
            out.push_str("    slli t6, t5, 2\n"); // offset = i * 4
            out.push_str("    addi t2, t6, -4\n"); // prev offset = (i-1) * 4
            out.push_str("    add t7, t0, t2\n");
            out.push_str("    lw t1, 0(t7)\n");
            out.push_str("    add t7, t0, t6\n");
            out.push_str("    sw t1, 0(t7)\n");
            out.push_str("    j shift_loop_rv_\n");
            out.push_str("shift_done_rv_:\n");
            // Store new value at stage 0
            out.push_str("    sw t4, 0(t0)\n");
        }
        RspuInstruction::SrQuery { dst, guard } => {
            // Read LSB of guard state
            writeln!(out, "    la t0, guard_g{}", guard).unwrap();
            writeln!(out, "    lw x{}, 0(t0)", dst).unwrap();
            writeln!(out, "    andi x{}, x{}, 1", dst, dst).unwrap();
        }

        // Temporal tier — counter
        RspuInstruction::CtrInit { guard, target, cond: _ } => {
            writeln!(out, "    la t0, guard_g{}", guard).unwrap();
            writeln!(out, "    li t1, {}", target).unwrap();
            out.push_str("    sw t1, 0(t0)\n");
        }
        RspuInstruction::CtrTick { guard } => {
            writeln!(out, "    la t0, guard_g{}", guard).unwrap();
            out.push_str("    lw t1, 0(t0)\n");
            out.push_str("    addi t1, t1, -1\n");
            out.push_str("    sw t1, 0(t0)\n");
        }
        RspuInstruction::CtrQuery { dst, guard } => {
            writeln!(out, "    la t0, guard_g{}", guard).unwrap();
            writeln!(out, "    lw x{}, 0(t0)", dst).unwrap();
            writeln!(out, "    sltz x{}, x{}", dst, dst).unwrap();
        }

        // Guard combination
        RspuInstruction::GuardAnd { dst, a, b } => {
            writeln!(out, "    la t0, guard_g{}", a).unwrap();
            out.push_str("    lw t1, 0(t0)\n");
            writeln!(out, "    la t0, guard_g{}", b).unwrap();
            out.push_str("    lw t2, 0(t0)\n");
            out.push_str("    and t1, t1, t2\n");
            writeln!(out, "    la t0, guard_g{}", dst).unwrap();
            out.push_str("    sw t1, 0(t0)\n");
        }
        RspuInstruction::GuardOr { dst, a, b } => {
            writeln!(out, "    la t0, guard_g{}", a).unwrap();
            out.push_str("    lw t1, 0(t0)\n");
            writeln!(out, "    la t0, guard_g{}", b).unwrap();
            out.push_str("    lw t2, 0(t0)\n");
            out.push_str("    or t1, t1, t2\n");
            writeln!(out, "    la t0, guard_g{}", dst).unwrap();
            out.push_str("    sw t1, 0(t0)\n");
        }

        // Reflex tier
        RspuInstruction::ReflexIf { guard, dst, src } => {
            *label_counter += 1;
            let label = *label_counter;
            writeln!(out, "    la t0, guard_g{}", guard).unwrap();
            out.push_str("    lw t1, 0(t0)\n");
            writeln!(out, "    beq t1, x0, skip_reflex_{}", label).unwrap();
            writeln!(out, "    addi x{}, x{}, 0", dst, src).unwrap();
            writeln!(out, "skip_reflex_{}:", label).unwrap();
        }
        RspuInstruction::Prev { dst, signal, delay } => {
            // Read from shift register at offset
            writeln!(
                out,
                "    # PREV x{}, x{}, delay={} (shift register read)",
                dst, signal, delay
            )
            .unwrap();
            writeln!(out, "    addi x{}, x{}, 0", dst, signal).unwrap();
        }

        // Safety tier
        RspuInstruction::EmergencyStop => {
            out.push_str("    ebreak\n");
        }

        // LTL assertion tier
        RspuInstruction::AssertAlways { cond, property_id } => {
            *label_counter += 1;
            let label = *label_counter;
            writeln!(out, "    bne x{}, x0, assert_pass_{}", cond, label).unwrap();
            writeln!(out, "    li a7, {}", 200 + property_id).unwrap();
            out.push_str("    ecall\n");
            writeln!(out, "assert_pass_{}:", label).unwrap();
        }
        RspuInstruction::AssertNever { cond, property_id } => {
            *label_counter += 1;
            let label = *label_counter;
            writeln!(out, "    beq x{}, x0, assert_pass_{}", cond, label).unwrap();
            writeln!(out, "    li a7, {}", 300 + property_id).unwrap();
            out.push_str("    ecall\n");
            writeln!(out, "assert_pass_{}:", label).unwrap();
        }

        // Exception tier
        RspuInstruction::Trap { code } => {
            writeln!(out, "    li a7, {}", code).unwrap();
            out.push_str("    ecall\n");
        }
        RspuInstruction::TrapIf { cond, code } => {
            *label_counter += 1;
            let label = *label_counter;
            writeln!(out, "    beq x{}, x0, skip_trap_{}", cond, label).unwrap();
            writeln!(out, "    li a7, {}", code).unwrap();
            out.push_str("    ecall\n");
            writeln!(out, "skip_trap_{}:", label).unwrap();
        }
        RspuInstruction::Halt => {
            out.push_str("    li a7, 0\n");
            out.push_str("    ecall\n");
        }

        // Control tier
        RspuInstruction::ModeSwitch { mode } => {
            writeln!(out, "    # MODE_SWITCH {}", mode).unwrap();
        }
        RspuInstruction::Nop => {
            out.push_str("    nop\n");
        }
        RspuInstruction::Fence => {
            out.push_str("    fence\n");
        }

        // Tagged tier
        RspuInstruction::TagLoad { dst, tag } => {
            writeln!(out, "    li x{}, {}", dst, tag).unwrap();
        }
        RspuInstruction::TagCheck { src, expected } => {
            *label_counter += 1;
            let label = *label_counter;
            writeln!(out, "    li t0, {}", expected).unwrap();
            writeln!(out, "    beq x{}, t0, tag_ok_{}", src, label).unwrap();
            out.push_str("    li a7, 708\n");
            out.push_str("    ecall\n");
            writeln!(out, "tag_ok_{}:", label).unwrap();
        }
        RspuInstruction::TagRead { dst, src } => {
            writeln!(out, "    addi x{}, x{}, 0", dst, src).unwrap();
        }

        // Deadline
        RspuInstruction::DeadlineSet { cycles } => {
            writeln!(out, "    # DEADLINE_SET {}", cycles).unwrap();
        }

        // Totality engine tier
        RspuInstruction::Verify { cert_offset } => {
            writeln!(out, "    # VERIFY offset={}", cert_offset).unwrap();
        }
        RspuInstruction::Certify { dst } => {
            writeln!(out, "    li x{}, 1", dst).unwrap();
        }
        RspuInstruction::TotalCheck { expected_properties } => {
            writeln!(out, "    # TOTAL_CHECK {}", expected_properties).unwrap();
        }

        // Symbolic tier
        RspuInstruction::Match { dst, src, table_offset } => {
            writeln!(out, "    # MATCH x{}, x{}, table=#{}", dst, src, table_offset).unwrap();
            writeln!(out, "    addi x{}, x{}, 0", dst, src).unwrap();
        }
        RspuInstruction::IntervalLo { dst, src } => {
            writeln!(out, "    addi x{}, x{}, 0", dst, src).unwrap();
        }
        RspuInstruction::IntervalHi { dst, src } => {
            writeln!(out, "    addi x{}, x{}, 0", dst, src).unwrap();
        }
        RspuInstruction::IntervalCheck { src, bounds } => {
            writeln!(out, "    # INTERVAL_CHECK x{}, x{}", src, bounds).unwrap();
        }
    }
    Ok(())
}

/// Emit RISC-V ALU operation.
fn emit_riscv_alu(out: &mut String, op: AluOp, dst: u8, a: u8, b: u8) {
    match op {
        AluOp::Add => writeln!(out, "    add x{}, x{}, x{}", dst, a, b).unwrap(),
        AluOp::Sub => writeln!(out, "    sub x{}, x{}, x{}", dst, a, b).unwrap(),
        AluOp::Mul => writeln!(out, "    mul x{}, x{}, x{}", dst, a, b).unwrap(),
        AluOp::And => writeln!(out, "    and x{}, x{}, x{}", dst, a, b).unwrap(),
        AluOp::Or => writeln!(out, "    or x{}, x{}, x{}", dst, a, b).unwrap(),
        AluOp::Xor => writeln!(out, "    xor x{}, x{}, x{}", dst, a, b).unwrap(),
        AluOp::Shl => writeln!(out, "    sll x{}, x{}, x{}", dst, a, b).unwrap(),
        AluOp::Shr => writeln!(out, "    srl x{}, x{}, x{}", dst, a, b).unwrap(),
        AluOp::Eq => {
            writeln!(out, "    xor t0, x{}, x{}", a, b).unwrap();
            writeln!(out, "    seqz x{}, t0", dst).unwrap();
        }
        AluOp::Ne => {
            writeln!(out, "    xor t0, x{}, x{}", a, b).unwrap();
            writeln!(out, "    snez x{}, t0", dst).unwrap();
        }
        AluOp::Lt => writeln!(out, "    slt x{}, x{}, x{}", dst, a, b).unwrap(),
        AluOp::Gt => writeln!(out, "    slt x{}, x{}, x{}", dst, b, a).unwrap(),
        AluOp::Le => {
            writeln!(out, "    slt t0, x{}, x{}", b, a).unwrap();
            writeln!(out, "    xori x{}, t0, 1", dst).unwrap();
        }
        AluOp::Ge => {
            writeln!(out, "    slt t0, x{}, x{}", a, b).unwrap();
            writeln!(out, "    xori x{}, t0, 1", dst).unwrap();
        }
    }
}

/// Emit RISC-V ALU with immediate.
fn emit_riscv_alu_imm(out: &mut String, op: AluOp, dst: u8, a: u8, imm: u64) {
    match op {
        AluOp::Add => writeln!(out, "    addi x{}, x{}, {}", dst, a, imm).unwrap(),
        AluOp::And => writeln!(out, "    andi x{}, x{}, {}", dst, a, imm).unwrap(),
        AluOp::Or => writeln!(out, "    ori x{}, x{}, {}", dst, a, imm).unwrap(),
        AluOp::Xor => writeln!(out, "    xori x{}, x{}, {}", dst, a, imm).unwrap(),
        AluOp::Shl => writeln!(out, "    slli x{}, x{}, {}", dst, a, imm & 31).unwrap(),
        AluOp::Shr => writeln!(out, "    srli x{}, x{}, {}", dst, a, imm & 31).unwrap(),
        _ => {
            // Fallback: load immediate then apply binary op
            writeln!(out, "    li t0, {}", imm).unwrap();
            emit_riscv_alu(out, op, dst, a, 5); // t0 = x5
        }
    }
}
