// Auto-generated by MIRR compiler (Phase 6)
// Do not edit — regenerate from .mirr source.
// Target: SystemVerilog (.sv)

module ScienceHls (
  input  logic        clk,
  input  logic        rst_n,
  input  logic signed [ 7:0] a,
  input  logic signed [ 7:0] b,
  input  logic signed [ 7:0] c,
  output logic signed [16:0] out_val
);

  // Internal signals
  logic signed [ 7:0] a_d1;
  logic signed [ 7:0] a_d2;
  logic signed [ 7:0] a_d3;
  logic signed [ 7:0] b_d1;
  logic signed [ 7:0] b_d2;
  logic signed [ 7:0] b_d3;
  logic signed [ 7:0] c_d1;
  logic signed [ 7:0] c_d2;
  logic signed [ 7:0] c_d3;
  logic        rst_n_d1;
  logic        rst_n_d2;
  logic        rst_n_d3;

  // Temporal signals
  logic        always_out;

  // ── Temporal Guards ──


  // Guard: always — always for 0 cycle (combinational)
  logic always_cond;
  assign always_cond = 1'b1;
  assign always_out = always_cond;

  // ── Reflex Assignments ──

  logic always_out;

  // Unified Reflex Block for: a_d1
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      a_d1 <= '0;
    end else begin
      if (always_out) a_d1 <= a;
    end
  end

  // Unified Reflex Block for: a_d2
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      a_d2 <= '0;
    end else begin
      if (always_out) a_d2 <= a_d1;
    end
  end

  // Unified Reflex Block for: a_d3
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      a_d3 <= '0;
    end else begin
      if (always_out) a_d3 <= a_d2;
    end
  end

  // Unified Reflex Block for: b_d1
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      b_d1 <= '0;
    end else begin
      if (always_out) b_d1 <= b;
    end
  end

  // Unified Reflex Block for: b_d2
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      b_d2 <= '0;
    end else begin
      if (always_out) b_d2 <= b_d1;
    end
  end

  // Unified Reflex Block for: b_d3
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      b_d3 <= '0;
    end else begin
      if (always_out) b_d3 <= b_d2;
    end
  end

  // Unified Reflex Block for: c_d1
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      c_d1 <= '0;
    end else begin
      if (always_out) c_d1 <= c;
    end
  end

  // Unified Reflex Block for: c_d2
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      c_d2 <= '0;
    end else begin
      if (always_out) c_d2 <= c_d1;
    end
  end

  // Unified Reflex Block for: c_d3
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      c_d3 <= '0;
    end else begin
      if (always_out) c_d3 <= c_d2;
    end
  end

  // Unified Reflex Block for: out_val
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      out_val <= '0;
    end else begin
      if (always_out) out_val <= ((a + b) * c);
    end
  end

  // Unified Reflex Block for: rst_n_d1
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rst_n_d1 <= '0;
    end else begin
      if (always_out) rst_n_d1 <= rst_n;
    end
  end

  // Unified Reflex Block for: rst_n_d2
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rst_n_d2 <= '0;
    end else begin
      if (always_out) rst_n_d2 <= rst_n_d1;
    end
  end

  // Unified Reflex Block for: rst_n_d3
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rst_n_d3 <= '0;
    end else begin
      if (always_out) rst_n_d3 <= rst_n_d2;
    end
  end

  // ── Safety Properties (SVA) ──

  // property: math_check
  always @(posedge clk) begin
    if (rst_n && ((((a_d3 == a) && (b_d3 == b)) && (c_d3 == c)) && rst_n_d3)) assert ((out_val == ((a + b) * c)));
  end

endmodule
